import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createActivationPlans,DEFAULT_ACTIVATION_PLAN,normalizeActivationPlan} from '../server/dex/activation-plan.js';
import {productLaunchRequest} from '../server/product-launch-configuration.js';
const agent={id:'11111111-2222-3333-4444-555555555555',creator:'fixture-owner',strategy:'balanced'};
const scope={kind:'LAUNCHPAD',owner:agent.creator,agentId:agent.id,wallet:'fixture-wallet',mint:'fixture-mint',network:'solana:101',executionId:'fixture-execution',signature:'fixture-signature',confirmedSlot:100};
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());let binding=scope;const plans=createActivationPlans(db,{readAuthority:()=>binding,now:()=>1000});return {db,plans,set binding(v){binding=v;}};}
test('save/read never activate, alter lifecycle, or grant signing authority',t=>{const f=fixture(t);f.db.exec("CREATE TABLE dex_autonomous_lifecycle(agent_id TEXT PRIMARY KEY,data TEXT);INSERT INTO dex_autonomous_lifecycle VALUES('untouched','baseline')");assert.equal(f.plans.read(agent).plan,null);const first=f.plans.save(agent,{revision:0,policy:DEFAULT_ACTIVATION_PLAN});assert.equal(first.plan.status,'DRAFT');assert.equal(first.plan.startsAt,null);assert.equal(first.plan.expiresAt,null);assert.equal(first.activationEnabled,false);assert.equal(first.authorizationGranted,false);assert.equal(first.withdrawalEnabled,false);assert.equal(f.plans.save(agent,{revision:1,policy:DEFAULT_ACTIVATION_PLAN}).plan.revision,1);assert.equal(f.db.prepare('SELECT data FROM dex_autonomous_lifecycle').get().data,'baseline');assert.equal('approve'in f.plans,false);assert.equal('activate'in f.plans,false);assert.equal('sign'in f.plans,false);});
test('five personalities are selectable in draft without changing Paper identity or raising system limits',t=>{const f=fixture(t);let revision=0;for(const personality of ['guardian','scout','operator','hunter','berserker']){const r=f.plans.save(agent,{revision,policy:{...DEFAULT_ACTIVATION_PLAN,personality}});revision=r.plan.revision;assert.equal(r.plan.policy.personality,personality);assert.equal(r.limits.maxPerTradeLamports,'100000');assert.equal(agent.strategy,'balanced');assert.equal(r.authorizationGranted,false);}});
for(const patch of [{perTradeLamports:'100001'},{sessionDebitLamports:'500001'},{dailyDebitLamports:'500001'},{durationMinutes:1441},{maxTransactions:11},{slippageBps:101},{withdrawalEnabled:true},{mint:'other'},{personality:'__proto__'},{perTradeLamports:'1e5'},{perTradeLamports:100000},{sessionDebitLamports:'100000'}])test(`draft rejects unsupported or oversized policy ${JSON.stringify(patch)}`,()=>assert.throws(()=>normalizeActivationPlan({...DEFAULT_ACTIVATION_PLAN,...patch})));
test('stale revisions, foreign owner, changed binding and unavailable receipt fail closed; cancel never needs RPC',t=>{const f=fixture(t),first=f.plans.save(agent,{revision:0,policy:DEFAULT_ACTIVATION_PLAN});assert.throws(()=>f.plans.save(agent,{revision:0,policy:DEFAULT_ACTIVATION_PLAN}),/REVISION_CHANGED/);assert.throws(()=>f.plans.read({...agent,creator:'other'}),/CONFIRMED_LAUNCH_REQUIRED/);f.binding={...scope,mint:'changed'};assert.equal(f.plans.read(agent).current,false);f.binding={kind:'GENERAL'};assert.throws(()=>f.plans.read(agent),/CONFIRMED_LAUNCH/);assert.equal(f.plans.cancel(agent,{revision:first.plan.revision}).plan.status,'CANCELLED');});
test('durable draft/revision survives two SQLite connections, stale save cannot overwrite',()=>{const dir=mkdtempSync(join(tmpdir(),'tekkteam-activation-')),file=join(dir,'fixture.sqlite');let a=new DatabaseSync(file),b;try{const one=createActivationPlans(a,{readAuthority:()=>scope,now:()=>1000});one.save(agent,{revision:0,policy:DEFAULT_ACTIVATION_PLAN});a.close();a=new DatabaseSync(file);b=new DatabaseSync(file);const left=createActivationPlans(a,{readAuthority:()=>scope}),right=createActivationPlans(b,{readAuthority:()=>scope});assert.equal(right.read(agent).plan.revision,1);left.save(agent,{revision:1,policy:{...DEFAULT_ACTIVATION_PLAN,maxTransactions:3}});assert.throws(()=>right.save(agent,{revision:1,policy:DEFAULT_ACTIVATION_PLAN}),/REVISION_CHANGED/);assert.equal(right.read(agent).plan.revision,2);}finally{a.close();b?.close();rmSync(dir,{recursive:true,force:true});}});
test('reviewed product profile admits only inactive save/cancel, never approve/fund/trade',()=>{const configuration={origin:'https://tekkteam.tech',port:4190},req={method:'POST',headers:{host:'tekkteam.tech',origin:'https://tekkteam.tech','x-forwarded-proto':'https'},socket:{remoteAddress:'127.0.0.1'}};for(const path of ['activation-plan','activation-plan/cancel'])assert.equal(productLaunchRequest({...req,url:'/api/agents/'+agent.id+'/'+path},configuration),true);for(const path of ['activation-plan/approve','activation-plan/activate','trading/funding/prepare','trading/autonomous-real/start'])assert.equal(productLaunchRequest({...req,url:'/api/agents/'+agent.id+'/'+path},configuration),false);});
