import test from 'node:test';
import assert from 'node:assert/strict';
import { Keypair, Transaction } from '@solana/web3.js';
import { devnetChain } from '../server/chain.js';
test('devnet transaction binds owner, mint and full instruction message',async()=>{
  const owner=Keypair.generate(), mint=Keypair.generate(); let sent=false;
  const rpc={getGenesisHash:async()=> 'EtWTRABZaYq6iMfeYKouRu166VU2xqa1',getMinimumBalanceForRentExemption:async()=>1461600,getLatestBlockhash:async()=>({blockhash:Keypair.generate().publicKey.toBase58(),lastValidBlockHeight:999}),sendRawTransaction:async()=>{sent=true;return 'ok';},getSignatureStatuses:async()=>({value:[{confirmationStatus:'confirmed',err:null}]})};
  rpc.getGenesisHash=async()=> 'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG';
  rpc.getLatestBlockhash=async commitment=>{assert.equal(commitment,'finalized');return {blockhash:Keypair.generate().publicKey.toBase58(),lastValidBlockHeight:999};};
  rpc.sendRawTransaction=async(bytes,options)=>{assert.equal(options.skipPreflight,false);assert.equal(options.preflightCommitment,'finalized');sent=true;return 'ok';};
  rpc.getFeeForMessage=async()=>({value:10000});
  rpc.getBalance=async()=>1e9;
  const chain=devnetChain('http://localhost',rpc);
  const prepared=await chain.prepare({creator:owner.publicKey.toBase58()},mint.secretKey);
  const tx=Transaction.from(Buffer.from(prepared.transaction,'base64'));
  assert.equal(tx.feePayer.toBase58(),owner.publicKey.toBase58()); assert.equal(tx.instructions.length,5);
  rpc.getBlockHeight=async()=>100;
  rpc.simulateTransaction=async(transaction,config)=>{assert.equal(config.replaceRecentBlockhash,false);assert.equal(config.sigVerify,false);return {value:{err:null,unitsConsumed:14000}};};
  assert.equal((await chain.preflight(prepared,owner.publicKey.toBase58())).simulation,'passed');
  rpc.simulateTransaction=async()=>({value:{err:'BlockhashNotFound'}});
  await assert.rejects(()=>chain.preflight(prepared,owner.publicKey.toBase58()),/simulation failed/);
  rpc.getBlockHeight=async()=>1000;
  await assert.rejects(()=>chain.preflight(prepared,owner.publicKey.toBase58()),/Blockhash expired/);
  tx.partialSign(owner); assert.equal(tx.verifySignatures(),true);
  rpc.getEpochInfo=async commitment=>{assert.equal(commitment,'finalized');return {blockHeight:await rpc.getBlockHeight(),absoluteSlot:2000};};
  rpc.getBalanceAndContext=async()=>({context:{slot:2000},value:1461600});
  rpc.getSignaturesForAddress=async()=>[{signature:'wallet-signature'}];
  rpc.getTransaction=async()=>({transaction:{message:tx.compileMessage()},meta:{err:null}});
  assert.deepEqual(await chain.walletStatus(prepared),{status:'confirmed',signature:'wallet-signature'});
  rpc.getTransaction=async()=>({transaction:{message:{serialize:()=>Buffer.from('unrelated')}},meta:{err:null}});
  rpc.getBlockHeight=async()=>100;
  assert.equal((await chain.walletStatus(prepared)).status,'pending');
  rpc.getBlockHeight=async()=>1000;
  rpc.getAccountInfo=async()=>null;
  const history=rpc.getSignaturesForAddress;
  rpc.getSignaturesForAddress=async()=>{throw Error('History must not be needed for an expired missing mint');};
  rpc.getBalanceAndContext=async(key,options)=>{assert.equal(options.commitment,'finalized');assert.equal(options.minContextSlot,2000);return {context:{slot:2000},value:0};};
  assert.equal((await chain.walletStatus(prepared)).status,'expired');
  rpc.getSignaturesForAddress=history;
  rpc.getBalanceAndContext=async()=>({context:{slot:1999},value:0});
  assert.equal((await chain.walletStatus(prepared)).status,'pending');
  rpc.getBalanceAndContext=async()=>({context:{slot:2000},value:1461600});
  rpc.getAccountInfo=async()=>({});
  assert.equal((await chain.walletStatus(prepared)).status,'pending');
  const submission=await chain.submit(tx.serialize().toString('base64'),prepared.message); assert.equal(sent,false); await submission.send(); assert.equal(sent,true);
  assert.equal(await chain.status(submission.signature),'confirmed');
  assert.ok(prepared.estimatedCostSol > 0);
  rpc.getBalance=async()=>0;
  await assert.rejects(()=>chain.prepare({creator:owner.publicKey.toBase58()},mint.secretKey),/Not enough devnet SOL/);
  rpc.getSignatureStatuses=async()=>({value:[null]});
  rpc.getBlockHeight=async()=>1000;
  assert.equal(await chain.status(submission.signature,999),'expired');
  tx.instructions.pop(); tx.partialSign(owner,mint);
  await assert.rejects(()=>chain.submit(tx.serialize().toString('base64'),prepared.message),/differs/);
  rpc.getGenesisHash=async()=> 'mainnet';
  await assert.rejects(()=>chain.prepare({creator:owner.publicKey.toBase58()},mint.secretKey),/not Solana devnet/);
});
