import test from 'node:test';
import assert from 'node:assert/strict';
import {Keypair,TransactionMessage,VersionedTransaction,TransactionInstruction,ComputeBudgetProgram,SystemProgram,AddressLookupTableAccount} from '@solana/web3.js';
import {decodeDexTransaction,validateDexTransaction} from '../server/dex/transaction-validator.js';
import {createAssociatedTokenAccountIdempotentInstruction,getAssociatedTokenAddressSync} from '@solana/spl-token';
const kp=n=>Keypair.fromSeed(Uint8Array.from({length:32},(_,i)=>(n+i)%256));
const wallet=kp(1),input=kp(2).publicKey,output=kp(3).publicKey,source=kp(4).publicKey,destination=kp(5).publicKey,program=kp(6).publicKey,blockhash=kp(7).publicKey.toBase58();
const s=k=>k.toBase58();
// Synthetic route ABI exists ONLY in this fixture: [input u64, minOutput u64],
// exact ordered accounts authority/inputMint/outputMint/source/destination.
const routeData=()=>{const b=Buffer.alloc(16);b.writeBigUInt64LE(100n);b.writeBigUInt64LE(90n,8);return b;};
const route=()=>new TransactionInstruction({programId:program,keys:[wallet.publicKey,input,output,source,destination].map((pubkey,i)=>({pubkey,isSigner:i===0,isWritable:i===0||i>2})),data:routeData()});
function decoder(ix){assert.equal(ix.data.length,16);assert.equal(ix.keys.length,5);return {authority:s(ix.keys[0].pubkey),inputMint:s(ix.keys[1].pubkey),outputMint:s(ix.keys[2].pubkey),inputTokenAccount:s(ix.keys[3].pubkey),outputTokenAccount:s(ix.keys[4].pubkey),inputAmount:String(ix.data.readBigUInt64LE()),minimumOutput:String(ix.data.readBigUInt64LE(8))};}
const policy=()=>({genesisHash:'5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d',intent:{network:'solana:mainnet',agentWallet:s(wallet.publicKey),inputMint:s(input),outputMint:s(output),inputAmount:'100'},quote:{inputMint:s(input),outputMint:s(output),inputAmount:'100',minimumOutput:'90'},blockhash,computeBudget:{units:10000,microLamports:0},allowedWritableAccounts:[s(wallet.publicKey),s(source),s(destination)],inputTokenAccount:s(source),outputTokenAccount:s(destination),routeDecoders:new Map([[s(program),decoder]])});
function make({mutate=()=>{},v0=false,tables=[],sign=false,payer=wallet.publicKey,hash=blockhash}={}){const instructions=[ComputeBudgetProgram.setComputeUnitPrice({microLamports:0}),ComputeBudgetProgram.setComputeUnitLimit({units:10000}),route()];mutate(instructions);const m=new TransactionMessage({payerKey:payer,recentBlockhash:hash,instructions});const tx=new VersionedTransaction(v0?m.compileToV0Message(tables):m.compileToLegacyMessage());if(sign)tx.sign([wallet]);return Buffer.from(tx.serialize()).toString('base64');}
test('legacy and v0 exact synthetic route; production empty registry rejects',()=>{for(const v0 of [false,true])assert.ok(validateDexTransaction(make({v0}),policy()));assert.throws(()=>validateDexTransaction(make(),{...policy(),routeDecoders:new Map()}),/UNSUPPORTED/);});
test('signature verified offline and mutated signature rejected',()=>{const encoded=make({sign:true});assert.ok(validateDexTransaction(encoded,{...policy(),requireSignature:true}));const tx=VersionedTransaction.deserialize(Buffer.from(encoded,'base64'));tx.signatures[0][0]^=1;assert.throws(()=>validateDexTransaction(Buffer.from(tx.serialize()).toString('base64'),{...policy(),requireSignature:true}),/INVALID_SIGNATURE/);});
test('amount/minOut/mint/recipient mutations fail',()=>{for(const mutate of [i=>i[2].data.writeBigUInt64LE(101n),i=>i[2].data.writeBigUInt64LE(1n,8),i=>i[2].keys[1].pubkey=kp(9).publicKey,i=>i[2].keys[4].pubkey=kp(9).publicKey])assert.throws(()=>validateDexTransaction(make({mutate}),policy()));});
test('extra System transfer, unknown program, writable account fail',()=>{for(const mutate of [i=>i.push(SystemProgram.transfer({fromPubkey:wallet.publicKey,toPubkey:destination,lamports:1})),i=>i[2].programId=kp(9).publicKey,i=>i[2].keys[1].isWritable=true])assert.throws(()=>validateDexTransaction(make({mutate}),policy()));});
test('changed budget, blockhash, payer, message fail',()=>{assert.throws(()=>validateDexTransaction(make({mutate:i=>i[0]=ComputeBudgetProgram.setComputeUnitPrice({microLamports:1})}),policy()),/COMPUTE/);assert.throws(()=>validateDexTransaction(make({hash:s(kp(9).publicKey)}),policy()),/BLOCKHASH/);assert.throws(()=>validateDexTransaction(make({payer:kp(9).publicKey}),policy()),/SIGNER/);assert.throws(()=>validateDexTransaction(make(),{...policy(),expectedMessageHash:'0'.repeat(64)}),/MESSAGE/);});
test('lookup tables resolved completely; missing table fails closed',()=>{const table=new AddressLookupTableAccount({key:kp(8).publicKey,state:{deactivationSlot:18446744073709551615n,lastExtendedSlot:1,lastExtendedSlotStartIndex:0,authority:undefined,addresses:[source,destination]}});const encoded=make({v0:true,tables:[table]});assert.throws(()=>decodeDexTransaction(encoded),/LOOKUP/);assert.ok(validateDexTransaction(encoded,{...policy(),lookupTables:[table]}));});
test('network, quote amount, unsigned preexisting signature, malformed input fail',()=>{assert.throws(()=>validateDexTransaction(make(),{...policy(),genesisHash:'devnet'}),/NETWORK/);assert.throws(()=>validateDexTransaction(make(),{...policy(),quote:{...policy().quote,inputAmount:'101'}}),/QUOTE/);assert.throws(()=>validateDexTransaction(make({sign:true}),policy()),/PREEXISTING/);assert.throws(()=>decodeDexTransaction('not transaction'),/DECODE/);});
test('canonical output ATA creation allowed only when explicitly required',()=>{const ata=getAssociatedTokenAddressSync(output,wallet.publicKey);const encoded=make({mutate:i=>{i[2].keys[4].pubkey=ata;i.splice(2,0,createAssociatedTokenAccountIdempotentInstruction(wallet.publicKey,ata,wallet.publicKey,output));}});const p={...policy(),createOutputAta:true,outputTokenAccount:s(ata),allowedWritableAccounts:[s(wallet.publicKey),s(source),s(ata)]};assert.ok(validateDexTransaction(encoded,p));assert.throws(()=>validateDexTransaction(encoded,{...p,createOutputAta:false}),/ATA/);assert.throws(()=>validateDexTransaction(make(),{...policy(),createOutputAta:true}),/ATA/);});
test('SELL semantic direction reverses exact mints and accounts without relaxing validation',()=>{const p=policy();[p.intent.inputMint,p.intent.outputMint]=[p.intent.outputMint,p.intent.inputMint];[p.quote.inputMint,p.quote.outputMint]=[p.quote.outputMint,p.quote.inputMint];[p.inputTokenAccount,p.outputTokenAccount]=[p.outputTokenAccount,p.inputTokenAccount];const encoded=make({mutate:i=>{[i[2].keys[1],i[2].keys[2]]=[i[2].keys[2],i[2].keys[1]];[i[2].keys[3],i[2].keys[4]]=[i[2].keys[4],i[2].keys[3]];}});assert.ok(validateDexTransaction(encoded,p));assert.throws(()=>validateDexTransaction(encoded,policy()),/SEMANTIC/);});
test('duplicate compute, duplicate route, extra signer, same input/output account reject',()=>{for(const mutate of [i=>i.push(ComputeBudgetProgram.setComputeUnitLimit({units:10000})),i=>i.push(route()),i=>i[2].keys[3].isSigner=true])assert.throws(()=>validateDexTransaction(make({mutate}),policy()));assert.throws(()=>validateDexTransaction(make(),{...policy(),inputTokenAccount:s(destination)}),/TOKEN_ACCOUNT_POLICY/);});
test('invoked program writable escalation rejected even if manifest accidentally includes it',()=>{assert.throws(()=>validateDexTransaction(make({mutate:i=>i[2].keys.push({pubkey:program,isWritable:true,isSigner:false})}),{...policy(),allowedWritableAccounts:[...policy().allowedWritableAccounts,s(program)]}),/INVALID_PROGRAM_PRIVILEGES/);});
test('ATA changed discriminator or writable mint rejected despite broad manifest',()=>{const ata=getAssociatedTokenAddressSync(output,wallet.publicKey);for(const change of [ix=>ix.data=Buffer.from([0]),ix=>ix.keys[3].isWritable=true]){const encoded=make({mutate:i=>{i[2].keys[4].pubkey=ata;const ix=createAssociatedTokenAccountIdempotentInstruction(wallet.publicKey,ata,wallet.publicKey,output);change(ix);i.splice(2,0,ix);}});assert.throws(()=>validateDexTransaction(encoded,{...policy(),createOutputAta:true,outputTokenAccount:s(ata),allowedWritableAccounts:[s(wallet.publicKey),s(source),s(ata),s(output)]}),/ATA/);}});
