import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {observeCapitalRequirement} from '../server/dex/capital-evidence.js';
const snapshot=JSON.parse(readFileSync(new URL('./fixtures/narrow-route-chain-evidence.json',import.meta.url))).accounts;
test('observed two-ATA capital includes peak rent, fee cap and reserve without duplicating margin',()=>{const r=observeCapitalRequirement(snapshot,{hypotheticalInputLamports:'100000'});assert.equal(r.protectedReserveLamports,'2020000');assert.equal(r.accountCreationCostLamports,'2976880');assert.equal(r.capitalBeforeInputLamports,'5006880');assert.equal(r.hypothetical.conditionalRequiredBalanceLamports,'5106880');assert.equal(r.hypothetical.conditionalAdditionalLamports,'111880');assert.equal(r.maximumPolicyInputLamports,'0');assert.equal(r.minimumSafeTestInputLamports,null);assert.equal(r.minimumRequiredAgentBalanceLamports,null);assert.equal(r.executionAllowed,false);});
test('no hypothetical input means no invented required deposit',()=>{const r=observeCapitalRequirement(snapshot);assert.equal(r.hypothetical,null);assert.equal(r.additionalSolRequiredLamports,null);});
test('verified existing ATA reduces rent, but never approves a route or manufactures input floor',()=>{const s=structuredClone(snapshot);s.accounts[1].exists=true;s.ataRentLamports=s.rentPerAccountLamports;const r=observeCapitalRequirement(s);assert.equal(r.missingAtaCount,1);assert.equal(r.accountCreationCostLamports,'1488440');assert.equal(r.maximumPolicyInputLamports,'1000000');assert.equal(r.minimumSafeTestInputLamports,null);assert.equal(r.executionAllowed,false);});
test('rent mismatch, unknown existence, wrong network and invalid input reject',()=>{for(const s of [{...snapshot,ataRentLamports:'0'},{...snapshot,network:'devnet'},{...snapshot,accounts:[{...snapshot.accounts[0],exists:undefined},snapshot.accounts[1]]}])assert.throws(()=>observeCapitalRequirement(s));for(const input of ['0','-1','0.0001'])assert.throws(()=>observeCapitalRequirement(snapshot,{hypotheticalInputLamports:input}));});
