import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createAutonomousAcceptance,ENGINE_ACCEPTANCE as C} from '../server/dex/autonomous-acceptance.js';
import {SOL_MINT} from '../server/dex/intent.js';
import {createDexLedger} from '../server/dex/ledger.js';
import {createAutonomousClaim} from '../server/dex/autonomous-claim.js';

const context={ownerAuthenticated:true,ownershipVerified:true,vaultVerified:true,networkVerified:true,owner:C.owner,agentId:C.agentId,agentWallet:C.agentWallet};
const flags={acceptanceOverrideConfigured:true,realMoneyEmergencyStop:true,autonomousKillSwitch:true};
const store=(t,now=()=>1000)=>{const db=new DatabaseSync(':memory:');t.after(()=>db.close());return createAutonomousAcceptance(db,{activationConfigured:true,now});};
const buy=s=>({mode:C.mode,acceptanceCycleId:s.cycleId,network:'solana:mainnet',agentId:C.agentId,owner:C.owner,agentWallet:C.agentWallet,venue:C.venue,direction:'BUY',pool:C.pool,inputMint:SOL_MINT,outputMint:C.tokenMint,inputAmount:'100000',slippageBps:100});
const sell=(s,quantity='41715')=>({...buy(s),direction:'SELL',inputMint:C.tokenMint,outputMint:SOL_MINT,inputAmount:quantity,exitReason:'MAX_HOLD'});
const prepared=(id,intent)=>({id,intent,fingerprint:`fp-${id}`,status:'PREPARED',messageHash:`hash-${id}`,pool:C.pool,simulation:{success:true}});
const bind=(a,r)=>a.bindExecution(r,{reservation:{operationId:`dex:${r.id}`,intentHash:r.fingerprint,status:'PREPARED',resources:[{wallet:C.agentWallet,lamports:'10000'}]},riskPass:true,simulationPass:true});
test('production default cannot arm, while explicit owner activation is independent of normal Live kill',t=>{const db=new DatabaseSync(':memory:');t.after(()=>db.close());const locked=createAutonomousAcceptance(db);assert.throws(()=>locked.ownerEnable(context,flags),/ACCEPTANCE_NOT_ARMABLE/);const a=createAutonomousAcceptance(db,{activationConfigured:true});assert.throws(()=>a.ownerEnable({...context,ownerAuthenticated:false},flags),/ACCEPTANCE_NOT_ARMABLE/);assert.throws(()=>a.ownerEnable(context,{...flags,acceptanceOverrideConfigured:false}),/ACCEPTANCE_NOT_ARMABLE/);assert.equal(a.ownerEnable(context,flags).status,'ARMED');assert.throws(()=>a.ownerEnable(context,flags),/ACCEPTANCE_NOT_ARMABLE/);});
test('one exact BUY, confirmed actual position, 180s hold, exact SELL and auto-disarm',t=>{let clock=1000;const a=store(t,()=>clock),s=a.ownerEnable(context,flags),intent=buy(s);a.recordStrategy({side:'HOLD',reason:'Entry thresholds not met'});assert.equal(a.read().strategyResult.side,'HOLD');a.assertBuy(intent,{context,flags,riskPass:true,openPositions:0});const b=prepared('buy-execution',intent);bind(a,b);assert.equal(a.read().status,'BUYING');assert.throws(()=>a.assertBuy(intent,{context,flags,riskPass:true,openPositions:0,executionId:'other'}),/ACCEPTANCE_BUY_LOCKED/);const unknown={...b,status:'UNKNOWN',authorizedMessageHash:b.messageHash};a.assertClaim(unknown);a.markUnknown(unknown);assert.equal(a.read().status,'UNKNOWN');const confirmed={...b,status:'CONFIRMED',signature:'buy-signature'};a.confirmedBuy(confirmed,{signature:'buy-signature',finalized:true,actualOutput:'41715',confirmedAt:clock,slot:1},{buySignature:'buy-signature',quantity:'41715'});assert.equal(a.read().status,'POSITION_OPEN');assert.throws(()=>a.assertBuy(intent,{context,flags,riskPass:true,openPositions:0}),/ACCEPTANCE_BUY_LOCKED/);const si=sell(s),p={mint:C.tokenMint,pool:C.pool,buySignature:'buy-signature',quantity:'41715'};assert.throws(()=>a.assertSell(si,{context,flags,riskPass:true,position:p,exitReason:'MAX_HOLD'}),/ACCEPTANCE_SELL_LOCKED/);clock+=180000;a.assertSell(si,{context,flags,riskPass:true,position:p,exitReason:'MAX_HOLD'});const sr=prepared('sell-execution',si);bind(a,sr);a.confirmedSell({...sr,status:'CONFIRMED',signature:'sell-signature'},{signature:'sell-signature',finalized:true},{quantity:'0',sellSignature:'sell-signature'});assert.equal(a.read().status,'COMPLETED');assert.equal(a.read().emergencyPermission,false);assert.throws(()=>a.ownerEnable(context,flags),/ACCEPTANCE_NOT_ARMABLE/);});
test('wrong mint, pool, amount, slippage, owner, vault, and Risk reject',t=>{const a=store(t),s=a.ownerEnable(context,flags),intent=buy(s),args={context,flags,riskPass:true,openPositions:0};for(const patch of [{outputMint:SOL_MINT},{pool:SOL_MINT},{inputAmount:'100001'},{slippageBps:101},{agentWallet:SOL_MINT},{acceptanceCycleId:'other'}])assert.throws(()=>a.assertBuy({...intent,...patch},args));assert.throws(()=>a.assertBuy(intent,{...args,riskPass:false}),/ACCEPTANCE_BUY_LOCKED/);assert.throws(()=>a.assertBuy(intent,{...args,context:{...context,vaultVerified:false}}),/ACCEPTANCE_BUY_LOCKED/);assert.throws(()=>a.assertBuy(intent,{...args,flags:{acceptanceEmergencyStop:true}}),/ACCEPTANCE_BUY_LOCKED/);});
test('terminal pre-sign failure and owner emergency stop remove one-shot permission',t=>{const a=store(t),s=a.ownerEnable(context,flags),r={...prepared('failed',buy(s)),status:'REJECTED_BEFORE_SIGNING',reason:'RISK_REJECTED'};a.failUnbound(r);assert.equal(a.read().status,'FAILED');assert.equal(a.read().emergencyPermission,false);const b=store(t),second=b.ownerEnable(context,flags);assert.equal(b.ownerEmergencyStop().status,'STOPPED');assert.throws(()=>b.assertBuy(buy(second),{context,flags,riskPass:true,openPositions:0}),/ACCEPTANCE_BUY_LOCKED/);});
test('transient monitor RPC failure after confirmed BUY preserves the open position cycle and original hold time',t=>{let clock=1000;const a=store(t,()=>clock),s=a.ownerEnable(context,flags),b=prepared('buy-execution',buy(s));bind(a,b);a.confirmedBuy({...b,status:'CONFIRMED',signature:'buy-signature'},{signature:'buy-signature',finalized:true,actualOutput:'41715',confirmedAt:clock,slot:1},{buySignature:'buy-signature',quantity:'41715'});clock+=180001;const monitored=a.terminalBeforeExecution('429 Too Many Requests');assert.equal(monitored.status,'POSITION_OPEN');assert.equal(monitored.emergencyPermission,true);assert.equal(monitored.buyExecutionId,'buy-execution');assert.equal(monitored.buySignature,'buy-signature');assert.equal(monitored.boughtAt,1000);assert.equal(monitored.monitorUnavailableReason,'429 Too Many Requests');a.assertSell(sell(s),{context,flags,riskPass:true,position:{mint:C.tokenMint,pool:C.pool,buySignature:'buy-signature',quantity:'41715'},exitReason:'MAX_HOLD'});});
test('clean pre-sign RPC failure permits a new owner cycle but archives the old cycle immutably',t=>{
 const db=new DatabaseSync(':memory:');t.after(()=>db.close());const ledger=createDexLedger(db),a=createAutonomousAcceptance(db,{activationConfigured:true});
 createAutonomousClaim({db,ledger,flags:()=>({}),acceptance:a});
 const old=a.ownerEnable(context,flags),intent={...buy(old),createdAt:1000,expiresAt:31000};
 const {record}=ledger.reserve({intent,fingerprint:'first-fingerprint',requestKey:'first-request-key'});
 const rejected=ledger.transition(record.id,['QUOTED'],'REJECTED_BEFORE_SIGNING',{reason:'RPC_MIN_CONTEXT_SLOT_NOT_REACHED'});
 a.failUnbound(rejected);assert.equal(a.retryEligible(),true);
 const next=a.ownerEnable(context,flags);assert.notEqual(next.cycleId,old.cycleId);assert.equal(next.status,'ARMED');
 const history=db.prepare('SELECT data FROM dex_autonomous_acceptance_history WHERE cycle_id=?').get(old.cycleId);assert.equal(JSON.parse(history.data).status,'FAILED');
 assert.equal(ledger.get(record.id).status,'REJECTED_BEFORE_SIGNING');assert.throws(()=>a.ownerEnable(context,flags),/ACCEPTANCE_NOT_ARMABLE/);
});
test('terminal label alone cannot authorize retry when a sign claim or reservation remains',t=>{
 const db=new DatabaseSync(':memory:');t.after(()=>db.close());const ledger=createDexLedger(db),a=createAutonomousAcceptance(db,{activationConfigured:true});
 createAutonomousClaim({db,ledger,flags:()=>({}),acceptance:a});const old=a.ownerEnable(context,flags),intent={...buy(old),createdAt:1000,expiresAt:31000};
 const {record}=ledger.reserve({intent,fingerprint:'unsafe-fingerprint',requestKey:'unsafe-request-key'}),rejected=ledger.transition(record.id,['QUOTED'],'REJECTED_BEFORE_SIGNING',{reason:'RPC_MIN_CONTEXT_SLOT_NOT_REACHED'});
 a.failUnbound(rejected);db.prepare('INSERT INTO dex_autonomous_sign_claim VALUES(?,?)').run(record.id,'fixture-hash');
 assert.equal(a.retryEligible(),false);assert.throws(()=>a.ownerEnable(context,flags),/ACCEPTANCE_NOT_ARMABLE/);
});
