import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Worker} from 'node:worker_threads';
import {createRealBalanceReservations} from '../server/real-balance-reservations.js';

const spec=(id='one',patch={})=>({operationId:id,intentHash:id,kind:'CONTROLLED_DEX',status:'PREPARED',resources:[{wallet:'fixture-wallet',lamports:'100000',balanceLamports:'5000000',protectedLamports:'2020000'}],...patch});
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());return {db,r:createRealBalanceReservations(db)};}
test('reservation is idempotent and immutable, including resource amounts',t=>{const {r}=fixture(t),s=spec();r.reserve(s);r.reserve(s);assert.equal(r.reserved('fixture-wallet'),'100000');assert.throws(()=>r.reserve({...s,intentHash:'changed'}),/INTENT_CONFLICT/);assert.throws(()=>r.reserve({...s,resources:[{...s.resources[0],lamports:'100001'}]}),/RESOURCE_MUTATION/);assert.throws(()=>r.reserve(spec('two')),/REAL_BALANCE_RESERVED/);});
test('reserve requires supported active state and sufficient unreserved balance',t=>{const {r}=fixture(t);assert.throws(()=>r.reserve(spec('one',{status:'FAILED'})),/INVALID_RESERVATION/);assert.throws(()=>r.reserve(spec('one',{resources:[{wallet:'fixture-wallet',lamports:'100000',balanceLamports:'2119999',protectedLamports:'2020000'}]})),/INSUFFICIENT/);assert.equal(r.get('one'),null);});
test('UNKNOWN retains reservation, cannot downgrade or release without proof',t=>{const {r}=fixture(t),s=spec();r.reserve(s);r.reserve({...s,status:'UNKNOWN'});assert.throws(()=>r.finish('one','FAILED'),/REQUIRES_PROOF/);assert.throws(()=>r.reserve(s),/STATE_DOWNGRADE/);assert.throws(()=>r.reserve(spec('two')),/RESERVED/);r.finish('one','CONFIRMED',{provenTerminal:true,agentSolDelta:'-100000'});assert.equal(r.reserved('fixture-wallet'),'0');assert.equal(r.get('one').settlement.agentSolDelta,'-100000');assert.throws(()=>r.reserve(s),/TERMINAL/);r.reserve(spec('two'));});
test('unsigned terminal rejection releases; rollback restores original reservation',t=>{const {r,db}=fixture(t);r.reserve(spec());assert.throws(()=>r.atomic(()=>{r.finish('one','CANCELLED');throw Error('fixture rollback');}),/rollback/);assert.equal(r.reserved('fixture-wallet'),'100000');r.finish('one','REJECTED_BEFORE_SIGNING');assert.equal(db.prepare('SELECT COUNT(*) n FROM real_reserved_accounts').get().n,0);});
test('incoming funding locks both wallets without counting unconfirmed credit',t=>{const {r}=fixture(t);const funding={id:'fund',kind:'FUND',status:'PREPARED',source:'owner',destination:'fixture-wallet',ownerWallet:'owner',agentWallet:'fixture-wallet',agentId:'agent',amountLamports:'100000',network:'mainnet'};r.syncWalletRecord(funding,()=>{});assert.equal(r.reserved('owner'),'110000');assert.equal(r.reserved('fixture-wallet'),'0');assert.throws(()=>r.reserve(spec()),/RESERVED/);r.syncWalletRecord({...funding,status:'FAILED',reason:'Cancelled before submission'},()=>{});r.reserve(spec());assert.throws(()=>r.syncWalletRecord({...funding,id:'withdraw',kind:'WITHDRAW',source:'fixture-wallet',destination:'owner'},()=>{}),/RESERVED/);});
test('failed persistence rolls back reservation and pre-upgrade active request is a barrier',t=>{const {r,db}=fixture(t);assert.throws(()=>r.syncWalletRecord({id:'x',kind:'WITHDRAW',status:'PREPARED',source:'fixture-wallet',agentWallet:'fixture-wallet',amountLamports:'1'},()=>{throw Error('DB failure');}),/DB failure/);assert.equal(r.get('wallet:x'),null);db.exec('CREATE TABLE agent_funding(data TEXT)');db.prepare('INSERT INTO agent_funding VALUES(?)').run(JSON.stringify({id:'old',status:'UNKNOWN',source:'fixture-wallet'}));assert.throws(()=>r.reserve(spec()),/ACTIVE_WALLET/);});
test('two independent SQLite worker connections racing for one wallet admit exactly one',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'tekk-reservation-')),path=join(dir,'test.sqlite'),db=new DatabaseSync(path);db.exec('PRAGMA journal_mode=WAL');createRealBalanceReservations(db);db.close();t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const moduleUrl=new URL('../server/real-balance-reservations.js',import.meta.url).href,barrier=new SharedArrayBuffer(4);
 const source=`const {parentPort,workerData}=require('node:worker_threads');(async()=>{const {DatabaseSync}=await import('node:sqlite');const {createRealBalanceReservations}=await import(workerData.moduleUrl);const db=new DatabaseSync(workerData.path);db.exec('PRAGMA busy_timeout=5000');const r=createRealBalanceReservations(db);parentPort.postMessage('ready');Atomics.wait(new Int32Array(workerData.barrier),0,0);try{r.reserve(workerData.spec);parentPort.postMessage('accepted');}catch(e){parentPort.postMessage(e.code||e.message);}finally{db.close();}})();`;
 let ready=0;const results=await Promise.all(['one','two'].map(id=>new Promise((resolve,reject)=>{let result;const worker=new Worker(source,{eval:true,workerData:{path,moduleUrl,barrier,spec:spec(id)}});worker.on('error',reject);worker.on('exit',code=>code?reject(Error('worker failed')):resolve(result));worker.on('message',m=>{if(m==='ready'){if(++ready===2){Atomics.store(new Int32Array(barrier),0,1);Atomics.notify(new Int32Array(barrier),0);}}else result=m;});})));
 assert.equal(results.filter(x=>x==='accepted').length,1);assert.equal(results.filter(x=>x==='REAL_BALANCE_RESERVED').length,1);
});
