import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync}from'node:fs';
const code=readFileSync('public/app/guide-drawer.js','utf8').replace(/^import .*;\r?\n/gm,'').replace(/export /g,'');
function data(){const ctx={productIcon:id=>'<i>'+id+'</i>'};vm.runInNewContext(code+';items=categories;catalog=guideCategories',ctx);return ctx;}
test('existing six category identities and drawer interfaces retained',()=>{const d=data();assert.deepEqual(Array.from(d.catalog,x=>x.id),['getting-started','agents-guide','trading-risk','wallets-guide','tokens-guide','paper-real']);assert.equal(typeof d.mountGuideDrawer,'function');for(const c of d.items){assert.equal((c.content.match(/<article>/g)||[]).length,(c.content.match(/<\/article>/g)||[]).length);}});
test('getting started separates public connection/authentication, review, confirmation, funding and start',()=>{const h=data().items[0].content;for(const text of ['signed challenge','preview connection requests no signature','href="#/launch"','verified owner save capability is available','first immutable coin draft','Saving metadata does not launch a token','public delivery remains unverified','Preparation is not launch confirmation','Funding is separately gated and remains OFF','Paper needs no real deposit','Live stays OFF','same-signature reconciliation'])assert.ok(h.includes(text),text);assert.doesNotMatch(h,/#\/agents\/new|START AI AGENT|token setup for it is not available/);});
test('strategy and target explanation preserves rules-based presets and legacy GENERAL',()=>{const h=data().items[1].content;for(const text of ['deterministic momentum/activity rules','presets of one engine','legacy GENERAL Agents remain general','Configure does not start trading','Pause does not liquidate'])assert.ok(h.includes(text),text);});
test('custody source claims distinguish owner payer/creator, mint signer and Agent wallet',()=>{const h=data().items[3].content;for(const text of ['authenticated owner as fee payer and encoded creator','new mint is a separate required signer','not proof of a completed launch or creator-fee rights','encrypted server-side custody','not the owner browser wallet','does not create or fund it automatically','Funding and withdrawal remain OFF'])assert.ok(h.includes(text),text);});
test('uncertainty and Paper/Live economics remain truthful',()=>{const d=data();assert.match(d.items[4].content,/prepared mint is not a confirmed launch/);assert.match(d.items[4].content,/do not blindly relaunch/);assert.match(d.items[5].content,/Live stays OFF/);assert.match(d.items[5].content,/Paper PnL is not real profit/);assert.doesNotMatch(d.items[5].content,/PRIVATE BETA/);});
test('actual existing drawer opens Guide content and restores focus on close without actions',()=>{let click,dialog,focused=0,removed=0;const trigger={dataset:{guideCategory:'getting-started'},isConnected:true,focus(){focused++},addEventListener(_,fn){click=fn}};const closeButton={focus(){},onclick:null};const ctx={productIcon:()=>'',window:{scrollY:25,scrollTo(){}},document:{body:{append(){}},createElement:()=>dialog={setAttribute(){},innerHTML:'',querySelector:()=>closeButton,querySelectorAll:()=>[],addEventListener(){},showModal(){this.open=true},close(){this.open=false;this.onclose?.()},remove(){removed++}}}};vm.runInNewContext(code,ctx);const mounted=ctx.mountGuideDrawer({querySelectorAll:()=>[trigger]});assert.equal(dialog,undefined);click();assert.match(dialog.innerHTML,/COIN \+ AGENT/);assert.equal(dialog.open,true);closeButton.onclick();assert.equal(focused,1);assert.equal(removed,1);mounted.destroy();});
