import test from'node:test';import assert from'node:assert/strict';import{resolve,join}from'node:path';import{resolveTokenDraftConfiguration}from'../server/launchpad-token-configuration.js';
const root=resolve('CONFIG_FIXTURE_NEVER_CREATED'),input=()=>({dataDir:root,assetRoot:join(root,'pump-metadata-site'),journalPath:join(root,'pump-agent-launches.json'),publicOrigin:'https://owner-fixture.invalid',publisherOrigin:'https://owner-fixture.invalid'});
test('explicit aligned configuration resolves current image/publisher/journal layout without runtime authority',()=>{const d=resolveTokenDraftConfiguration(input());assert.equal(d.configurationStatus,'COMPATIBLE');assert.equal(d.reason,null);assert.deepEqual(d.options,{assetRoot:join(root,'pump-metadata-site'),journalPath:join(root,'pump-agent-launches.json'),publicOrigin:'https://owner-fixture.invalid'});assert.equal(d.asset.layout,'OWNER_AGENT_SHA256_PNG_V1');assert.equal(d.asset.configurationProvenance,'DERIVED');assert.equal(d.asset.localAsset,'UNAVAILABLE');assert.equal(d.asset.publicDelivery,'UNAVAILABLE');assert.equal(d.receiptAuthority,'UNAVAILABLE');assert.equal(d.authorizationGranted,false);});
test('missing explicit configuration never supplies default publisher, receipt journal or env configuration',()=>{for(const v of [undefined,null,{},...Object.keys(input()).map(k=>{const v=input();delete v[k];return v;})]){const d=resolveTokenDraftConfiguration(v);assert.equal(d.reason,'TOKEN_CONFIGURATION_MISSING');assert.equal(d.options,null);assert.equal(d.asset.configurationProvenance,'UNAVAILABLE');}});
test('wrong current asset root and unrelated empty journal cannot become compatible first-token authority',()=>{for(const[field,value,reason]of [['assetRoot',root,'TOKEN_CONFIGURATION_ASSET_ROOT_MISMATCH'],['assetRoot',join(root,'other-site'),'TOKEN_CONFIGURATION_ASSET_ROOT_MISMATCH'],['journalPath',join(root,'empty-other-journal.json'),'TOKEN_CONFIGURATION_JOURNAL_PATH_MISMATCH']]){const d=resolveTokenDraftConfiguration({...input(),[field]:value});assert.equal(d.reason,reason);assert.equal(d.options,null);}});
test('relative, UNC, control, ill-formed Unicode and non-string paths reject without path leakage',()=>{for(const field of ['dataDir','assetRoot','journalPath'])for(const value of ['relative/path','\\\\remote\\secret','//remote/secret',' '+root,root+'\nSECRET',root+'\ud800',7]){const d=resolveTokenDraftConfiguration({...input(),[field]:value});assert.equal(d.reason,'TOKEN_CONFIGURATION_PATH_INVALID');assert.ok(!JSON.stringify(d).includes('SECRET'));}});
test('image and publisher origins reuse reviewed schema restrictions and require plain HTTPS origins',()=>{for(const field of ['publicOrigin','publisherOrigin'])for(const value of ['http://owner-fixture.invalid','https://localhost.','https://a.localhost.','https://127.1','https://[2001:db8::1]','https://user:PRIVATE@owner-fixture.invalid','https://owner-fixture.invalid/path','https://owner-fixture.invalid/?secret=x','https://owner-fixture.invalid/#secret','https://owner-fixture.invalid\\secret',' https://owner-fixture.invalid']){const d=resolveTokenDraftConfiguration({...input(),[field]:value});assert.equal(d.reason,'TOKEN_CONFIGURATION_ORIGIN_INVALID');assert.ok(!JSON.stringify(d).includes('PRIVATE'));}});
test('canonical host case/default port/slash align but a different origin stays unavailable',()=>{const d=resolveTokenDraftConfiguration({...input(),publicOrigin:'https://OWNER-fixture.invalid:443/',publisherOrigin:'https://owner-fixture.invalid/'});assert.equal(d.configurationStatus,'COMPATIBLE');assert.equal(d.options.publicOrigin,'https://owner-fixture.invalid');assert.equal(resolveTokenDraftConfiguration({...input(),publisherOrigin:'https://other.invalid'}).reason,'TOKEN_CONFIGURATION_ORIGIN_MISMATCH');});
test('unknown/private fields and reflective failures stay fixed unavailable; getters are not invoked',()=>{let reads=0;const getter={...input()};Object.defineProperty(getter,'dataDir',{enumerable:true,get(){reads++;throw Error('PRIVATE');}});for(const value of [[],()=>{}, {...input(),credential:'PRIVATE'},getter,new Proxy({}, {ownKeys(){throw Error('PRIVATE');}})]){const d=resolveTokenDraftConfiguration(value);assert.equal(d.reason,'TOKEN_CONFIGURATION_INVALID');assert.equal(d.options,null);assert.ok(!JSON.stringify(d).includes('PRIVATE'));}assert.equal(reads,0);});
test('output/options/provenance are fresh deeply frozen and detached from input mutation',()=>{const v=input(),d=resolveTokenDraftConfiguration(v),again=resolveTokenDraftConfiguration(v);assert.notEqual(d,again);assert.notEqual(d.options,again.options);for(const part of [d,d.options,d.asset])assert.equal(Object.isFrozen(part),true);v.assetRoot='other';assert.equal(d.options.assetRoot,join(root,'pump-metadata-site'));assert.throws(()=>{d.options.publicOrigin='https://other.invalid';});assert.equal(resolveTokenDraftConfiguration(v).configurationStatus,'UNAVAILABLE');});
test('normalized lexical path segments do not imply filesystem existence, symlink identity or public availability',()=>{const d=resolveTokenDraftConfiguration({...input(),assetRoot:join(root,'unused','..','pump-metadata-site')});assert.equal(d.configurationStatus,'COMPATIBLE');assert.equal(d.asset.localAsset,'UNAVAILABLE');assert.equal(d.asset.publicDelivery,'UNAVAILABLE');assert.equal(d.receiptAuthority,'UNAVAILABLE');});
test('resolving explicitly supplied configuration does not consult environment defaults or secrets',()=>{const v=input(),previous=process.env;let d;try{process.env=new Proxy({}, {get(){throw Error('ENVIRONMENT_READ_FORBIDDEN');}});d=resolveTokenDraftConfiguration(v);}finally{process.env=previous;}assert.equal(d.configurationStatus,'COMPATIBLE');});

