import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {Keypair} from '@solana/web3.js';
import {installLaunchpadScopeLedger} from '../server/launchpad-scope.js';
import {createServer} from '../server/app.js';
const evidenceDir=mkdtempSync(join(tmpdir(),'tekkteam-scope-fixture-'));process.env.DATA_DIR=evidenceDir;
const agent={id:'LOCAL_FIXTURE',creator:'OWNER'},bound={available:true,scoped:true,reason:null},legacy={available:true,scoped:false,reason:null};
function memory(){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)');return db;}
function enter(db,ledger,a=agent,source='LAUNCHPAD_ENTRY'){db.exec('BEGIN IMMEDIATE');try{const r=ledger.insertLaunchpadScope(a,{source});db.exec('COMMIT');return r;}catch(error){db.exec('ROLLBACK');throw error;}}
test('initialized ledger absence is legacy; atomic binding is immutable/idempotent',()=>{const db=memory();try{const l=installLaunchpadScopeLedger(db,{now:()=>1});assert.deepEqual(l.readLaunchpadScope(agent),legacy);assert.throws(()=>l.insertLaunchpadScope(agent,{source:'LAUNCHPAD_ENTRY'}),/atomic transaction/);assert.deepEqual(enter(db,l),bound);assert.deepEqual(enter(db,l),bound);assert.equal(db.prepare('SELECT count(*) AS n FROM launchpad_agent_scopes').get().n,1);assert.throws(()=>db.exec("UPDATE launchpad_agent_scopes SET owner='OTHER'"),/immutable/);assert.throws(()=>db.exec('DELETE FROM launchpad_agent_scopes'),/immutable/);assert.throws(()=>enter(db,l,agent,'LAUNCHPAD_IDENTITY'),/conflict/);assert.throws(()=>enter(db,l,{...agent,creator:'OTHER'}),/conflict/);}finally{db.close();}});
test('generic Agent JSON saves cannot erase classification',()=>{const db=memory();try{const l=installLaunchpadScopeLedger(db);db.exec('CREATE TABLE agents(id TEXT PRIMARY KEY,data TEXT)');db.prepare('INSERT INTO agents VALUES(?,?)').run(agent.id,JSON.stringify(agent));enter(db,l);db.prepare('UPDATE agents SET data=? WHERE id=?').run(JSON.stringify({...agent,scope:null,targetPolicy:'GENERAL'}),agent.id);assert.deepEqual(l.readLaunchpadScope(JSON.parse(db.prepare('SELECT data FROM agents').get().data)),bound);}finally{db.close();}});
test('scope persists through closing/reopening only a disposable SQLite fixture',()=>{const path=join(evidenceDir,'restart.sqlite');let db=new DatabaseSync(path);db.exec('CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)');enter(db,installLaunchpadScopeLedger(db));db.close();db=new DatabaseSync(path);try{assert.deepEqual(installLaunchpadScopeLedger(db).readLaunchpadScope(agent),bound);}finally{db.close();}});
test('missing table/sentinel/guard never resets established authority',()=>{for(const kind of ['table','sentinel','guard']){const db=memory();try{const l=installLaunchpadScopeLedger(db);enter(db,l);if(kind==='table')db.exec('DROP TABLE launchpad_agent_scopes');if(kind==='sentinel')db.exec("DELETE FROM settings WHERE key='launchpad_scope_ledger_v1'");if(kind==='guard')db.exec('DROP TRIGGER launchpad_scope_no_delete');assert.equal(l.readLaunchpadScope(agent).available,false);assert.throws(()=>installLaunchpadScopeLedger(db),/unavailable/);assert.equal(l.readLaunchpadScope(agent).scoped,null);}finally{db.close();}}});
test('malformed version/source/timestamp/binding is unavailable rather than legacy',()=>{for(const mutation of [{version:2},{source:'UNTRUSTED'},{created_at:-1},{owner:'OTHER'}]){const db=memory();try{const l=installLaunchpadScopeLedger(db);db.exec('PRAGMA ignore_check_constraints=ON');db.prepare('INSERT INTO launchpad_agent_scopes VALUES(?,?,?,?,?,?)').run(agent.id,mutation.owner??agent.creator,mutation.version??1,'ASSOCIATED_COIN',mutation.created_at??1,mutation.source??'LAUNCHPAD_ENTRY');assert.equal(l.readLaunchpadScope(agent).available,false);assert.equal(l.readLaunchpadScope(agent).scoped,null);assert.throws(()=>enter(db,l),/conflict/);}finally{db.close();}}});
test('identity/scope transaction rollback leaves neither row',()=>{const db=memory();try{const l=installLaunchpadScopeLedger(db);db.exec('CREATE TABLE agents(id TEXT PRIMARY KEY,data TEXT)');db.exec('BEGIN IMMEDIATE');db.prepare('INSERT INTO agents VALUES(?,?)').run(agent.id,'{}');l.insertLaunchpadScope(agent,{source:'LAUNCHPAD_IDENTITY'});db.exec('ROLLBACK');assert.equal(db.prepare('SELECT count(*) AS n FROM agents').get().n,0);assert.deepEqual(l.readLaunchpadScope(agent),legacy);}finally{db.close();}});
async function apiFixture(tradingOptions={},network='mainnet'){const owner=Keypair.generate().publicKey.toBase58(),other=Keypair.generate().publicKey.toBase58(),s=createServer({dbPath:':memory:',vaultKey:Buffer.alloc(32,7).toString('base64'),network,mainnetSafetyMode:network==='mainnet',rpc:'https://api.mainnet-beta.solana.com',tradingOptions});for(const [token,address]of [['scope-fixture',owner],['other-fixture',other]])s.store.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(createHash('sha256').update(token).digest('hex'),address,Date.now()+100000);const http=s.app.listen(0,'127.0.0.1');await new Promise(r=>http.once('listening',r));const call=async(path,body,cookie='scope-fixture',key='scope-fixture-key-001',origin='http://127.0.0.1:5188')=>{const response=await fetch('http://127.0.0.1:'+http.address().port+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:'tw_session='+cookie,'Idempotency-Key':key},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()};};return {s,owner,call,close:async()=>{await new Promise(r=>http.close(r));s.close();}};}
const input={name:'Scoped Identity',character:'frank',strategy:'balanced'};
test('scoped identity is atomic, tokenless, owner-bound, idempotent and not generic cross-replay',async()=>{const f=await apiFixture();try{const r=await f.call('/launchpad/agent-identities',input);assert.equal(r.status,201);assert.equal(r.data.coin,null);assert.deepEqual(r.data.launchpadScope,bound);assert.equal((await f.call('/launchpad/agent-identities',input)).data.id,r.data.id);assert.equal((await f.call('/agent-identities',input)).status,409);assert.equal((await f.call('/launchpad/agent-identities',{...input,name:'Changed'})).status,409);const dto=await f.call('/agents/'+r.data.id+'/contract');assert.deepEqual(dto.data.launchpadScope,bound);assert.equal(JSON.stringify(dto.data.launchpadScope).includes('created_at'),false);assert.equal((await f.call('/agents/'+r.data.id+'/contract',undefined,'other-fixture')).status,404);assert.equal(f.s.store.db.prepare('SELECT secret FROM agents WHERE id=?').get(r.data.id).secret,null);for(const table of ['agent_wallets','paper_states','submissions','dex_executions'])assert.equal(f.s.store.db.prepare('SELECT count(*) AS n FROM '+table).get().n,0);}finally{await f.close();}});
test('scoped create rejects client scope/token fields and unauthenticated or wrong origin',async()=>{const f=await apiFixture();try{assert.equal((await f.call('/launchpad/agent-identities',input,'missing')).status,401);assert.equal((await f.call('/launchpad/agent-identities',input,'scope-fixture','wrong-origin-001','https://untrusted.invalid')).status,403);for(const field of ['launchpadScope','coin','targetPolicy'])assert.equal((await f.call('/launchpad/agent-identities',{...input,[field]:{}})).status,400);assert.equal((await f.call('/agents',input)).status,403);assert.equal(f.s.store.db.prepare('SELECT count(*) AS n FROM launchpad_agent_scopes').get().n,0);}finally{await f.close();}});
test('fault during scoped create rolls back Agent, request, scope and event',async()=>{const f=await apiFixture();try{f.s.store.db.exec("CREATE TRIGGER fixture_scope_fault BEFORE INSERT ON launchpad_agent_scopes BEGIN SELECT RAISE(ABORT,'LOCAL_FIXTURE_FAULT'); END");assert.equal((await f.call('/launchpad/agent-identities',input)).status,500);for(const table of ['agents','requests','launchpad_agent_scopes','events'])assert.equal(f.s.store.db.prepare('SELECT count(*) AS n FROM '+table).get().n,0);}finally{await f.close();}});
test('generic identity remains legacy; entry/replay cannot accept request opt-in or downgrade',async()=>{const f=await apiFixture();try{const generic=await f.call('/agent-identities',input);assert.equal(generic.status,201);assert.deepEqual((await f.call('/agents/'+generic.data.id+'/contract')).data.launchpadScope,legacy);assert.equal((await f.call('/launchpad/agents/'+generic.data.id+'/enter',{targetPolicy:'GENERAL'},'scope-fixture','entry-key-001')).status,400);const scoped=await f.call('/launchpad/agent-identities',input,'scope-fixture','scoped-key-002');assert.equal(scoped.status,201);const entry=await f.call('/launchpad/agents/'+scoped.data.id+'/enter',{},'scope-fixture','entry-key-002');assert.equal(entry.status,200);assert.deepEqual(entry.data.launchpadScope,bound);assert.equal((await f.call('/launchpad/agents/'+scoped.data.id+'/enter',{},'scope-fixture','entry-key-002')).status,200);assert.equal((await f.call('/launchpad/agents/'+generic.data.id+'/enter',{},'scope-fixture','entry-key-002')).status,409);assert.equal(f.s.store.db.prepare('SELECT source FROM launchpad_agent_scopes WHERE agent_id=?').get(scoped.data.id).source,'LAUNCHPAD_IDENTITY');assert.equal((await f.call('/launchpad/agents/'+scoped.data.id+'/enter',{},'other-fixture','entry-key-003')).status,404);}finally{await f.close();}});
test('entry under enabled/open-position Paper never changes scope or state',async()=>{for(const state of [{enabled:true},{enabled:false,position:{mint:'LOCAL_FIXTURE'}}]){const f=await apiFixture();try{const r=await f.call('/agent-identities',input);const before=JSON.stringify({agentId:r.data.id,mode:'paper',...state});f.s.store.db.prepare('INSERT INTO paper_states VALUES(?,?)').run(r.data.id,before);const entry=await f.call('/launchpad/agents/'+r.data.id+'/enter',{},'scope-fixture','entry-active-001');assert.equal(entry.status,409);assert.equal(f.s.store.db.prepare('SELECT data FROM paper_states WHERE agent_id=?').get(r.data.id).data,before);assert.equal(f.s.store.db.prepare('SELECT count(*) AS n FROM launchpad_agent_scopes').get().n,0);}finally{await f.close();}}});
test('duplicate INSERT/REPLACE/UPSERT/UPDATE/DELETE preserve exact immutable row',()=>{const db=memory();try{const l=installLaunchpadScopeLedger(db,{now:()=>1});enter(db,l,agent,'LAUNCHPAD_IDENTITY');const before=JSON.stringify(db.prepare('SELECT * FROM launchpad_agent_scopes').get());for(const sql of ["INSERT OR REPLACE INTO launchpad_agent_scopes VALUES('LOCAL_FIXTURE','OWNER',1,'ASSOCIATED_COIN',2,'LAUNCHPAD_ENTRY')","REPLACE INTO launchpad_agent_scopes VALUES('LOCAL_FIXTURE','OWNER',1,'ASSOCIATED_COIN',2,'LAUNCHPAD_ENTRY')","INSERT INTO launchpad_agent_scopes VALUES('LOCAL_FIXTURE','OWNER',1,'ASSOCIATED_COIN',2,'LAUNCHPAD_ENTRY') ON CONFLICT(agent_id) DO UPDATE SET created_at=2","UPDATE launchpad_agent_scopes SET created_at=2","DELETE FROM launchpad_agent_scopes"]){assert.throws(()=>db.exec(sql),/immutable/);assert.equal(JSON.stringify(db.prepare('SELECT * FROM launchpad_agent_scopes').get()),before);}assert.deepEqual(enter(db,l,agent,'LAUNCHPAD_IDENTITY'),bound);db.exec('DROP TRIGGER launchpad_scope_no_replace');assert.equal(l.readLaunchpadScope(agent).available,false);assert.throws(()=>installLaunchpadScopeLedger(db),/unavailable/);assert.equal(JSON.stringify(db.prepare('SELECT * FROM launchpad_agent_scopes').get()),before);}finally{db.close();}});
test('actual guard permits inactive entry and blocks malformed state without fabricating legacy',async()=>{const f=await apiFixture();try{const r=await f.call('/agent-identities',input);const entry=await f.call('/launchpad/agents/'+r.data.id+'/enter',{},'scope-fixture','entry-idle-001');assert.equal(entry.status,201);assert.deepEqual(entry.data.launchpadScope,bound);assert.equal((await f.call('/launchpad/agents/'+r.data.id+'/enter',{},'scope-fixture','entry-idle-001')).status,200);const second=await f.call('/agent-identities',input,'scope-fixture','second-identity-001');f.s.store.db.prepare('INSERT INTO paper_states VALUES(?,?)').run(second.data.id,'invalid JSON');assert.equal((await f.call('/launchpad/agents/'+second.data.id+'/enter',{},'scope-fixture','malformed-entry-001')).status,409);assert.deepEqual((await f.call('/agents/'+r.data.id+'/contract')).data.launchpadScope,bound);}finally{await f.close();}});
const coinMint='So11111111111111111111111111111111111111112',otherMint='11111111111111111111111111111111';
const marketQuote=mint=>({mint,network:'solana:101',priceUsd:1,solUsd:150,liquidityUsd:50000,change5m:2,buys5m:20,sells5m:5,volume5m:2000,observedAt:Date.now()});
test('API+durable ledger enforce configure/start/tick and survive omitted/deleted/replaced targetPolicy',async()=>{let reads=[];const f=await apiFixture({receipt:a=>({agentId:a.id,owner:a.creator,network:'solana:101',status:'Success',confirmed:true,signature:'LOCAL_FIXTURE_SIGNATURE',mint:coinMint}),market:async m=>{reads.push(m);return marketQuote(m);}},'local');try{const r=await f.call('/launchpad/agent-identities',input),id=r.data.id,base='/agents/'+id+'/trading';assert.equal((await f.call(base+'/configure',{mode:'paper',strategy:'balanced',tokenMint:otherMint},'scope-fixture','unused-key-001')).status,409);assert.equal(reads.length,0);assert.equal((await f.call(base+'/configure',{mode:'paper',strategy:'balanced',tokenMint:coinMint})).status,200);assert.equal((await f.call(base+'/enable',{mode:'paper',strategy:'balanced',tokenMint:otherMint})).status,409);assert.equal((await f.call(base+'/enable',{mode:'paper',strategy:'balanced',discovery:false})).status,200);await f.s.paperTick();let state=JSON.parse(f.s.store.db.prepare('SELECT data FROM paper_states WHERE agent_id=?').get(id).data);assert.equal(state.position.mint,coinMint);assert.ok(reads.every(m=>m===coinMint));await f.call(base+'/pause',{});for(const policy of [undefined,'GENERAL',null]){let s=JSON.parse(f.s.store.db.prepare('SELECT data FROM paper_states WHERE agent_id=?').get(id).data);if(policy===undefined)delete s.targetPolicy;else s.targetPolicy=policy;s.mint=otherMint;s.position=null;s.enabled=true;f.s.store.db.prepare('UPDATE paper_states SET data=? WHERE agent_id=?').run(JSON.stringify(s),id);const before=reads.length;await f.s.paperTick();assert.equal(reads.length,before);assert.equal(JSON.parse(f.s.store.db.prepare('SELECT data FROM paper_states WHERE agent_id=?').get(id).data).position,null);assert.deepEqual((await f.call('/agents/'+id+'/contract')).data.launchpadScope,bound);}for(const policy of ['GENERAL',null]){let s=JSON.parse(f.s.store.db.prepare('SELECT data FROM paper_states WHERE agent_id=?').get(id).data);s.enabled=false;s.targetPolicy=policy;f.s.store.db.prepare('UPDATE paper_states SET data=? WHERE agent_id=?').run(JSON.stringify(s),id);assert.equal((await f.call(base+'/configure',{mode:'paper',strategy:'balanced',tokenMint:otherMint})).status,409);assert.equal((await f.call(base+'/enable',{mode:'paper',strategy:'balanced'})).status,409);}}finally{await f.close();}});
test('authoritative ledger absence preserves legacy GENERAL configure/start/tick',async()=>{const reads=[];const f=await apiFixture({receipt:()=>null,market:async m=>{reads.push(m);return marketQuote(m);}},'local');try{const r=await f.call('/agent-identities',input),id=r.data.id,base='/agents/'+id+'/trading';assert.deepEqual((await f.call('/agents/'+id+'/contract')).data.launchpadScope,legacy);assert.equal((await f.call(base+'/configure',{mode:'paper',strategy:'balanced',tokenMint:otherMint})).status,200);assert.equal((await f.call(base+'/enable',{mode:'paper',strategy:'balanced',discovery:false})).status,200);await f.s.paperTick();const state=JSON.parse(f.s.store.db.prepare('SELECT data FROM paper_states WHERE agent_id=?').get(id).data);assert.equal(state.position.mint,otherMint);assert.ok(reads.length>=3);assert.ok(reads.every(m=>m===otherMint));assert.equal((await f.call(base)).data.paperTargetPolicy.kind,'GENERAL');}finally{await f.close();}});
test('entry guard blocks an in-flight legacy configure and legacy can finish normally',async()=>{let release,called;const calledPromise=new Promise(r=>called=r);const f=await apiFixture({receipt:()=>null,market:async m=>{called();await new Promise(r=>release=r);return marketQuote(m);}},'local');try{const r=await f.call('/agent-identities',input),id=r.data.id;const pending=f.call('/agents/'+id+'/trading/configure',{mode:'paper',strategy:'balanced',tokenMint:otherMint});await calledPromise;const entry=await f.call('/launchpad/agents/'+id+'/enter',{},'scope-fixture','inflight-entry-001');assert.equal(entry.status,409);release();assert.equal((await pending).status,200);assert.deepEqual((await f.call('/agents/'+id+'/contract')).data.launchpadScope,legacy);}finally{if(release)release();await f.close();}});

test('explicit persisted GENERAL cannot enter conflicting scope; legacy state remains unchanged',async()=>{const f=await apiFixture();try{const r=await f.call('/agent-identities',input),id=r.data.id,state=JSON.stringify({agentId:id,mode:'paper',enabled:false,position:null,targetPolicy:'GENERAL'});f.s.store.db.prepare('INSERT INTO paper_states VALUES(?,?)').run(id,state);assert.equal((await f.call('/launchpad/agents/'+id+'/enter',{},'scope-fixture','explicit-general-001')).status,409);assert.equal(f.s.store.db.prepare('SELECT data FROM paper_states WHERE agent_id=?').get(id).data,state);assert.deepEqual((await f.call('/agents/'+id+'/contract')).data.launchpadScope,legacy);}finally{await f.close();}});
