import {walletShortcuts} from '../public/app/wallet-catalog.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import bs58 from 'bs58';
const saved={window:globalThis.window,fetch:globalThis.fetch,CustomEvent:globalThis.CustomEvent,sessionStorage:globalThis.sessionStorage};
const owner=bs58.encode(new Uint8Array(32).fill(7));let serial=0;
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
test('product sign-in waits for explicit review even for the regular backend and cancel never signs',async()=>{
 for(const approved of [false,true])try{
  const f=await fixture(),review=deferred();
  const pending=f.backend.connect('phantom',{reviewChallenge:()=>review.promise});
  await new Promise(r=>setImmediate(r));assert.equal(f.calls.includes('sign'),false);
  review.resolve(approved);
  if(approved){await pending;assert.equal(f.calls.filter(x=>x==='sign').length,1);assert.equal(f.cookie,true);}
  else{await assert.rejects(pending);assert.equal(f.calls.includes('sign'),false);assert.equal(f.cookie,false);}
 }finally{Object.assign(globalThis,saved);}
});
async function fixture({connectWait,verifyWait,logoutFails=false}={}){
 const storage=new Map();globalThis.sessionStorage={getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
 const calls=[],listeners=new Map();let cookie=false;
 const provider={isPhantom:true,isConnected:true,publicKey:{toBase58:()=>owner},async connect(){calls.push('connect');if(connectWait)await connectWait.promise;return {publicKey:this.publicKey};},async signMessage(){calls.push('sign');return {signature:new Uint8Array(64)};},async disconnect(){calls.push('disconnect');this.isConnected=false;},on:(n,f)=>listeners.set(n,f),removeListener:n=>listeners.delete(n)};
 globalThis.CustomEvent=class{constructor(type){this.type=type;}};
 globalThis.window={phantom:{solana:provider},TekkworkSDK:{bs58},addEventListener(){},dispatchEvent:e=>calls.push(e.type)};
 globalThis.fetch=async url=>{calls.push(url);if(url.endsWith('/auth/challenge'))return {ok:true,json:async()=>({id:'mock-only',message:'mock challenge'})};if(url.endsWith('/auth/verify')){if(verifyWait)await verifyWait.promise;cookie=true;}if(url.endsWith('/auth/logout')){if(logoutFails)throw Error('offline');cookie=false;}return {ok:true,json:async()=>({address:owner})};};
 const source=process.env.RECOVERY_BASELINE==='1'?'../artifacts/launchpad-continuation/direct-delivery/baseline-master-recovery-20261002/public/app/backend.js':'../public/app/backend.js';
 const backend=await import(source+'?master='+ ++serial);const rows=backend.wallets({readOnly:true});
 return {backend,provider,rows,calls,listeners,get cookie(){return cookie;}};
}
test('no-provider chooser preserves Phantom Solflare MetaMask with disabled install guidance',async()=>{try{const f=await fixture();delete window.phantom;const rows=f.backend.wallets({readOnly:true});assert.deepEqual(rows.map(w=>w.name),walletShortcuts.map(([name])=>name));assert.ok(rows.every(w=>!w.selectable&&w.installUrl));}finally{Object.assign(globalThis,saved);}});
test('connected address works with failed API and never signs or authenticates',async()=>{try{const f=await fixture();globalThis.fetch=()=>{throw Error('offline');};await f.backend.connectPublicWallet('phantom');assert.equal(f.backend.publicWalletPresentation().address,owner);assert.equal(f.calls.includes('sign'),false);assert.equal(f.calls.some(c=>c.startsWith('/api')),false);await f.backend.disconnectPublicWallet();assert.equal(f.backend.publicWalletPresentation(),null);}finally{Object.assign(globalThis,saved);}});
test('logout failure clears launch binding and removes provider listeners immediately',async()=>{try{const f=await fixture({logoutFails:true});await f.backend.connect('phantom');const pending=f.backend.disconnect();assert.throws(()=>f.backend.launchWallet(owner));assert.equal(f.listeners.size,0);await assert.rejects(pending,/offline/);assert.ok(f.calls.includes('disconnect'));}finally{Object.assign(globalThis,saved);}});
test('connect returned after disconnect cannot sign verify or restore launch binding',async()=>{try{const gate=deferred(),f=await fixture({connectWait:gate});const attempt=f.backend.connect('phantom');const rejected=assert.rejects(attempt);await f.backend.disconnect();gate.resolve();await rejected;assert.equal(f.calls.includes('sign'),false);assert.equal(f.calls.includes('/api/auth/verify'),false);assert.throws(()=>f.backend.launchWallet(owner));}finally{Object.assign(globalThis,saved);}});
test('late verify is revoked before disconnect completes so reload cannot restore its cookie',async()=>{try{const gate=deferred(),f=await fixture({verifyWait:gate});const attempt=f.backend.connect('phantom');const rejected=assert.rejects(attempt);while(!f.calls.includes('/api/auth/verify'))await new Promise(r=>setImmediate(r));const ending=f.backend.disconnect();gate.resolve();await rejected;await ending;assert.equal(f.cookie,false);assert.equal(f.calls.at(-1),'/api/auth/logout');assert.throws(()=>f.backend.launchWallet(owner));}finally{Object.assign(globalThis,saved);}});
test('repeated restored-owner observation installs one pair of listeners and ignores other Phantom account',async()=>{try{const f=await fixture();let adds=0;f.provider.on=(n,cb)=>{adds++;f.listeners.set(n,cb);};for(let i=0;i<5;i++)f.backend.observeExistingWallet(owner);assert.equal(adds,2);const retired=f.listeners.get('accountChanged');await f.backend.disconnect();const count=f.calls.length;retired({toBase58:()=>bs58.encode(new Uint8Array(32).fill(8))});assert.equal(f.calls.length,count);f.backend.observeExistingWallet(bs58.encode(new Uint8Array(32).fill(9)));assert.equal(f.listeners.size,0);}finally{Object.assign(globalThis,saved);}});
test('restored Solflare owner observes only its matching provider and immediately invalidates on disconnect',async()=>{try{const f=await fixture();const handlers=new Map();window.solflare={...f.provider,isSolflare:true,on:(n,fn)=>handlers.set(n,fn),removeListener:n=>handlers.delete(n)};f.backend.observeExistingWallet(owner,{name:'Solflare'});assert.equal(f.listeners.size,0);assert.equal(handlers.size,2);handlers.get('disconnect')();assert.equal(handlers.size,0);assert.ok(f.calls.includes('tekkwork:wallet-account-changed'));await new Promise(r=>setImmediate(r));}finally{Object.assign(globalThis,saved);}});
test('cancelling owner auth while provider is pending prevents signature request',async()=>{try{const gate=deferred(),f=await fixture({connectWait:gate});const pending=f.backend.connect('phantom');const rejected=assert.rejects(pending);f.backend.cancelOwnerAuthentication();gate.resolve();await rejected;assert.equal(f.calls.includes('sign'),false);}finally{Object.assign(globalThis,saved);}});
test('failed logout followed by fresh module retains detached owner fence and denies private reads',async()=>{try{const f=await fixture({logoutFails:true});await f.backend.connect('phantom');await assert.rejects(f.backend.disconnect());const next=await import('../public/app/backend.js?reload='+ ++serial);assert.equal(next.ownerAccessDetached(),true);globalThis.fetch=async()=>({ok:true,json:async()=>({config:{},session:{address:owner},agents:[{id:'private'}],events:[{id:'private'}],stats:{private:1}})});const state=await next.request('/state');assert.equal(state.session,null);assert.deepEqual(state.agents,[]);await assert.rejects(next.request('/trading/overview'),e=>e.httpStatus===401);await next.connectPublicWallet(next.wallets({readOnly:true}).find(w=>w.name==='Phantom').id);assert.equal(next.ownerAccessDetached(),true);}finally{Object.assign(globalThis,saved);}});
test('restored provider disconnect reaches extension and reauthentication refreshes watcher revision',async()=>{try{const f=await fixture();f.backend.observeExistingWallet(owner,{name:'Phantom'});await f.backend.connect('phantom');f.provider.publicKey={toBase58:()=>bs58.encode(new Uint8Array(32).fill(8))};f.listeners.get('accountChanged')(f.provider.publicKey);assert.ok(f.calls.includes('tekkwork:wallet-account-changed'));assert.equal(f.backend.ownerAccessDetached(),true);await new Promise(r=>setImmediate(r));const g=await fixture();g.backend.observeExistingWallet(owner,{name:'Phantom'});await g.backend.disconnect();assert.ok(g.calls.includes('disconnect'));}finally{Object.assign(globalThis,saved);}});
