import test from 'node:test';
import assert from 'node:assert/strict';
import bs58 from 'bs58';
import {readFileSync} from 'node:fs';
import {createPreviewConnection} from '../public/app/preview-wallet.js';
const first=bs58.encode(new Uint8Array(32).fill(1)),second=bs58.encode(new Uint8Array(32).fill(2));
const key=address=>({toBase58:()=>address});
function fixture(){const events=new Map(),calls=[];let provider={isPhantom:true,publicKey:key(first),connect:async()=>{calls.push('connect');return {publicKey:provider.publicKey};},disconnect:async()=>calls.push('disconnect'),on:(name,fn)=>events.set(name,fn),removeListener:name=>events.delete(name),signMessage:()=>{throw Error('No signing');},signTransaction:()=>{throw Error('No transactions');}};const changes=[];const connection=createPreviewConnection({getProvider:()=>provider,validateAddress:value=>{try{return bs58.decode(value).length===32;}catch{return false;}},onChange:value=>changes.push(value)});return {connection,events,calls,changes,get provider(){return provider;},set provider(value){provider=value;}};}
test('read-only connect/disconnect only calls provider and keeps address in memory',async()=>{const f=fixture();assert.equal(await f.connection.connect(),first);assert.equal(f.connection.address,first);await f.connection.disconnect();assert.equal(f.connection.address,null);assert.deepEqual(f.calls,['connect','disconnect']);assert.equal(f.events.size,0);});
test('missing provider and rejected consent never fabricate connection',async()=>{const f=fixture();f.provider=null;await assert.rejects(f.connection.connect(),/no longer available/);assert.equal(f.connection.address,null);const rejected=fixture();rejected.provider.connect=async()=>{throw Object.assign(Error('rejected'),{code:4001});};await assert.rejects(rejected.connection.connect(),/cancelled/);assert.equal(rejected.connection.address,null);});
test('account changes reflect actual valid provider address; null/disconnect clears',async()=>{const f=fixture();await f.connection.connect();f.provider.publicKey=key(second);f.events.get('accountChanged')(key(second));assert.equal(f.connection.address,second);f.provider.publicKey=null;f.events.get('accountChanged')(null);assert.equal(f.connection.address,null);await assert.rejects(f.connection.connect(),/valid Solana/);const other=fixture();await other.connection.connect();other.events.get('disconnect')();assert.equal(other.connection.address,null);});
test('provider replacement and invalid or mismatched keys fail closed',async()=>{const f=fixture();f.provider.connect=async()=>({publicKey:key(second)});await assert.rejects(f.connection.connect(),/account changed/);assert.equal(f.connection.address,null);f.provider.publicKey=key('bad');await assert.rejects(f.connection.connect(),/valid Solana/);const swapped=fixture();swapped.provider.connect=async()=>{swapped.provider={};return {publicKey:key(first)};};await assert.rejects(swapped.connection.connect(),/provider changed/);assert.equal(swapped.connection.address,null);});
test('disconnect during pending approval prevents stale connected state',async()=>{const f=fixture();let resolve;f.provider.connect=()=>new Promise(r=>resolve=r);const pending=f.connection.connect();await f.connection.disconnect();resolve({publicKey:key(first)});assert.equal(await pending,null);assert.equal(f.connection.address,null);});
test('address adapter has no presentation, authentication, signature, balance, transport or persistence effects',()=>{const source=readFileSync('public/app/preview-wallet.js','utf8');assert.doesNotMatch(source,/fetch\(|post\(|request\(|signMessage\(|signTransaction\(|localStorage|sessionStorage|createElement\(/);const workspace=readFileSync('public/app/workspace.js','utf8');assert.match(workspace,/wallets\(\{readOnly:true\}\)/);});

test('committing the same public binding never emits a transient disconnect or changes its provider identity',async()=>{const f=fixture();await f.connection.connect('phantom');f.changes.length=0;await f.connection.connect('phantom');assert.deepEqual(f.changes,[first]);assert.equal(f.connection.isConnectedTo('phantom',first),true);assert.equal(f.connection.isConnectedTo('other',first),false);f.provider={};assert.equal(f.connection.isConnectedTo('phantom',first),false);});

test('already-connected replacement rejection clears old address/hooks before consent and ignores late retired events',async()=>{
 const f=fixture();await f.connection.connect();const lateChange=f.events.get('accountChanged'),lateDisconnect=f.events.get('disconnect');const previous=f.provider;let reject;
 f.provider={publicKey:key(second),connect:()=>new Promise((_,r)=>reject=r)};const pending=f.connection.connect();assert.equal(f.connection.address,null);assert.equal(f.events.size,0);reject(Object.assign(Error('rejected'),{code:4001}));await assert.rejects(pending,/cancelled/);previous.publicKey=key(second);lateChange(key(second));lateDisconnect();assert.equal(f.connection.address,null);assert.equal(f.events.size,0);
});
test('already-connected missing or mismatched replacement cannot retain retired binding',async()=>{
 for(const replacement of [null,{publicKey:key(second),connect:async()=>({publicKey:key(first)})}]){const f=fixture();await f.connection.connect();const late=f.events.get('accountChanged');f.provider=replacement;await assert.rejects(f.connection.connect(),/no longer available|account changed/);assert.equal(f.connection.address,null);assert.equal(f.events.size,0);late(key(first));assert.equal(f.connection.address,null);}
});
test('same-provider rejected retry preserves only a still-matching key and clears unannounced key changes',async()=>{
 const f=fixture();await f.connection.connect();f.provider.connect=async()=>{throw Object.assign(Error('rejected'),{code:4001});};await assert.rejects(f.connection.connect(),/cancelled/);assert.equal(f.connection.address,first);assert.equal(f.events.size,2);f.provider.publicKey=key(second);await assert.rejects(f.connection.connect(),/cancelled/);assert.equal(f.connection.address,null);assert.equal(f.events.size,0);
});
test('provider replacement during rejected retry also detaches old binding',async()=>{
 const f=fixture();await f.connection.connect();const old=f.provider;old.connect=async()=>{f.provider={};throw Object.assign(Error('rejected'),{code:4001});};await assert.rejects(f.connection.connect(),/cancelled/);assert.equal(f.connection.address,null);assert.equal(f.events.size,0);
});
test('successful replacement binds new provider and retired callbacks cannot clear its address',async()=>{
 const f=fixture();await f.connection.connect();const lateChange=f.events.get('accountChanged'),lateDisconnect=f.events.get('disconnect');const next=fixture();next.provider.publicKey=key(second);f.provider=next.provider;assert.equal(await f.connection.connect(),second);lateChange(key(first));lateDisconnect();assert.equal(f.connection.address,second);assert.equal(f.events.size,0);assert.equal(next.events.size,2);
});
