import test from 'node:test';import assert from 'node:assert/strict';
import {PublicKey,Keypair} from '@solana/web3.js';
import {LIGHTHOUSE_PROGRAM} from '../src/pump-wallet-final.js';
import {LIGHTHOUSE_LOADER,LIGHTHOUSE_PROGRAM_DATA,readLighthouseDeployment,validateLighthouseProgramSnapshots} from '../server/pump-lighthouse-program.js';
const fixture=()=>{const p=Buffer.alloc(36),d=Buffer.alloc(60);p.writeUInt32LE(2);new PublicKey(LIGHTHOUSE_PROGRAM_DATA).toBuffer().copy(p,4);d.writeUInt32LE(3);d.writeBigUInt64LE(50n,4);d[45]=7;return [p,d].map((b,i)=>({owner:LIGHTHOUSE_LOADER,executable:i===0,lamports:1000,rentEpoch:100,space:b.length,data:[b.toString('base64'),'base64']}));};
async function baseline(){const accounts=fixture(),calls=[];let slot=100;const transport={rpc:async(method,params)=>{calls.push({method,params});return {context:{slot:slot++},value:structuredClone(accounts)};}};const d=await readLighthouseDeployment(transport,90);return {accounts,calls,transport,d};}
const observation=(account,slot=100,phase='before')=>({pubkey:LIGHTHOUSE_PROGRAM,account,slot,phase});
test('same-state same-slot and later-slot deployment identity pass',async()=>{const f=await baseline();validateLighthouseProgramSnapshots([observation(f.accounts[0]),observation(structuredClone(f.accounts[0]))],f.d.identity);const later=structuredClone(f.accounts[0]);later.lamports++;later.rentEpoch++;delete later.space;validateLighthouseProgramSnapshots([observation(f.accounts[0]),observation(later,101,'simulation')],f.d.identity);f.accounts[0]=later;f.accounts[1].lamports+=3;f.accounts[1].rentEpoch++;delete f.accounts[1].space;await readLighthouseDeployment(f.transport,100,f.d.identity);assert.deepEqual(f.calls[0].params,[[LIGHTHOUSE_PROGRAM,LIGHTHOUSE_PROGRAM_DATA],{encoding:'base64',commitment:'finalized',minContextSlot:90}]);});
for(const [field,value] of [['executable',false],['owner',Keypair.generate().publicKey.toBase58()],['space',3],['lamports',-1],['rentEpoch',-1]])test('program rejects '+field,async()=>{const f=await baseline(),p={...f.accounts[0],[field]:value};assert.throws(()=>validateLighthouseProgramSnapshots([observation(p,101,'simulation')],f.d.identity),e=>{assert.equal(e.code,'M4_LIGHTHOUSE_PROGRAM_OR_STATE_CHANGED');assert.equal(e.validationFailure.field,field);assert.equal(e.validationFailure.slot,101);return true;});});
test('wrong program identity and ProgramData pointer reject',async()=>{const f=await baseline();assert.throws(()=>validateLighthouseProgramSnapshots([{...observation(f.accounts[0]),pubkey:Keypair.generate().publicKey.toBase58()}],f.d.identity),e=>e.validationFailure.field==='pubkey');const b=Buffer.from(f.accounts[0].data[0],'base64');Keypair.generate().publicKey.toBuffer().copy(b,4);f.accounts[0].data[0]=b.toString('base64');await assert.rejects(readLighthouseDeployment(f.transport,100),e=>e.validationFailure.field==='programData');});
test('same-bank lamport mutation rejects',async()=>{const f=await baseline(),p={...f.accounts[0],lamports:1001};assert.throws(()=>validateLighthouseProgramSnapshots([observation(f.accounts[0]),observation(p,100,'simulation')],f.d.identity),e=>e.validationFailure.field==='lamports');});
for(const field of ['owner','executable','code','authority','deployedSlot'])test('ProgramData '+field+' substitution rejects with retained observation',async()=>{const f=await baseline(),b=Buffer.from(f.accounts[1].data[0],'base64');if(field==='owner')f.accounts[1].owner=Keypair.generate().publicKey.toBase58();if(field==='executable')f.accounts[1].executable=true;if(field==='code')b[45]++;if(field==='authority'){b[12]=1;Keypair.generate().publicKey.toBuffer().copy(b,13);}if(field==='deployedSlot')b.writeBigUInt64LE(51n,4);f.accounts[1].data[0]=b.toString('base64');let observed;await assert.rejects(readLighthouseDeployment(f.transport,100,f.d.identity,o=>observed=o),e=>{assert.equal(e.code,'M4_LIGHTHOUSE_DEPLOYMENT_CHANGED');assert.ok(e.validationFailure.field);return true;});assert.equal(observed.response.context.slot,101);assert.equal(observed.addresses[1],LIGHTHOUSE_PROGRAM_DATA);});
test('missing ProgramData persists partial read before refusal',async()=>{let evidence;await assert.rejects(readLighthouseDeployment({rpc:async()=>({context:{slot:101},value:[fixture()[0],null]})},100,null,o=>evidence=o),e=>e.validationFailure.field==='exists');assert.equal(evidence.response.value[1],null);});
