import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Keypair} from '@solana/web3.js';import nacl from 'tweetnacl';import bs58 from 'bs58';import sharp from 'sharp';
import {createServer} from '../server/app.js';
const origin='https://staging.fixture.example';
test('real verifier in disposable fixture: immutable owner binding, foreign/session/receipt guards; no receipt write',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'tekkteam-m3-route-test-')),journal=join(dir,'pump-agent-launches.json'),journalBytes=JSON.stringify({version:2,receipts:{}});writeFileSync(journal,journalBytes);
 let release,reached,releaseEvidence,reachedEvidence;const pause=new Promise(r=>release=r),started=new Promise(r=>reached=r),evidencePause=new Promise(r=>releaseEvidence=r),evidenceStarted=new Promise(r=>reachedEvidence=r);let calls=0,lastSnapshot,evidenceCalls=0,foreignResult=false;
 const api=createServer({dbPath:':memory:',vaultKey:Buffer.alloc(32,31).toString('base64'),origins:[origin],network:'mainnet',mainnetSafetyMode:true,rpc:'https://rpc.fixture.invalid',tokenDraftConfiguration:{dataDir:dir,assetRoot:join(dir,'pump-metadata-site'),journalPath:journal,publicOrigin:origin,publisherOrigin:origin},launchPreparation:async (identity,initialBuy,requestId)=>{calls++;lastSnapshot=identity;if(calls===2){reached();await pause;}return {mode:'LOCAL_FIXTURE_ONLY',owner:identity.owner,id:requestId,feePayer:identity.owner,launch:{...identity,agentId:foreignResult?crypto.randomUUID():identity.agentId,initialBuyLamports:0}};},launchPreparationEvidence:async result=>{evidenceCalls++;assert.equal(result.mode,'LOCAL_FIXTURE_ONLY');if(evidenceCalls===2){reachedEvidence();await evidencePause;}},realMoneyNetwork:{connection:new Proxy({},{get:()=>()=>{throw Error('LOCAL_FIXTURE_EFFECT_DENIED');}}),verify:async()=>{throw Error('LOCAL_FIXTURE_EFFECT_DENIED');},status:()=>({})}});
 const server=api.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url='http://127.0.0.1:'+server.address().port;
 const call=async(path,body,cookie='',key=crypto.randomUUID())=>{const r=await fetch(url+'/api'+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,'Idempotency-Key':key},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0],data:await r.json()};};
 const authenticate=async(seed)=>{const key=Keypair.fromSeed(new Uint8Array(32).fill(seed)),owner=key.publicKey.toBase58(),challenge=await call('/auth/challenge',{address:owner}),verified=await call('/auth/verify',{id:challenge.data.id,signature:bs58.encode(nacl.sign.detached(Buffer.from(challenge.data.message),key.secretKey))});assert.equal(verified.status,200);return {owner,cookie:verified.cookie};};
 try{
  const a=await authenticate(37),b=await authenticate(38),identity=await call('/launchpad/agent-identities',{name:'Fixture Agent',description:'Fixture only',character:'frank',strategy:'balanced'},a.cookie);assert.equal(identity.status,201);const id=identity.data.id,path='/launchpad/agents/'+id+'/preparation',body={initialBuy:'0',requestId:crypto.randomUUID()};
  assert.equal((await call(path,body)).status,401);assert.equal((await call(path,body,b.cookie)).status,404);assert.equal((await call(path,body,a.cookie)).status,409);assert.equal(calls,0);
  const png=await sharp({create:{width:3,height:3,channels:4,background:'#102e55'}}).png().toBuffer();
  const saved=await call('/launchpad/agents/'+id+'/token-draft',{expectedRevision:0,draft:{name:'Fixture Coin',ticker:'FIX',telegram:'https://t.me/fixture'},tokenImage:'data:image/png;base64,'+png.toString('base64')},a.cookie);assert.equal(saved.status,201);
  assert.equal((await call(path,{...body,payer:b.owner},a.cookie)).status,400);assert.equal((await call(path,body,a.cookie)).status,200);assert.equal(lastSnapshot.owner,a.owner);assert.equal(lastSnapshot.telegram,'https://t.me/fixture');assert.equal(lastSnapshot.tokenDraftRevision,1);assert.equal(evidenceCalls,1);
  const pending=call(path,{...body,requestId:crypto.randomUUID()},a.cookie);await started;assert.equal((await call('/auth/logout',{},a.cookie)).status,200);release();assert.equal((await pending).status,401);assert.equal(evidenceCalls,1);
  const again=await authenticate(37);foreignResult=true;assert.equal((await call(path,{...body,requestId:crypto.randomUUID()},again.cookie)).status,503);assert.equal(evidenceCalls,1);foreignResult=false;
  const evidencePending=call(path,{...body,requestId:crypto.randomUUID()},again.cookie);await evidenceStarted;assert.equal((await call('/auth/logout',{},again.cookie)).status,200);releaseEvidence();assert.equal((await evidencePending).status,401);assert.equal(evidenceCalls,2);
  assert.equal(readFileSync(journal,'utf8'),journalBytes);assert.equal(api.store.db.prepare('SELECT secret FROM agents WHERE id=?').get(id).secret,null);
 }finally{release();releaseEvidence();await new Promise(r=>server.close(r));api.close();}
});
