import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {Keypair,VersionedTransaction} from '@solana/web3.js';
import {pumpAccountFixture,pumpWalletFixture,fixtureBlockhash} from './pump-account-fixture.mjs';
import {decodePumpVenueBundle} from '../server/dex/pump-account-decoder.js';
import {createPumpRuntimeAdapter} from '../server/dex/pump-runtime-adapter.js';
import {createPumpRuntimeLedger} from '../server/dex/pump-runtime-ledger.js';
import {createPumpRuntimeExecutor} from '../server/dex/pump-runtime-executor.js';
import {GENESIS} from '../src/pump-readiness.js';
import {SOL_MINT} from '../server/dex/intent.js';

// All dependencies below are SYNTHETIC contract tests. Relabelling the mock read
// provenance models DI only: no real RPC, ON_CHAIN receipt, position or qualification.
const now=1800000000000,wallet=Keypair.fromSeed(Buffer.alloc(32,191)).publicKey.toBase58();
async function fixture({backend=true,source='ON_CHAIN',qualified=true,migrated=false}={}){
 const bundle=await pumpAccountFixture({migrated});bundle.context.observedAt=now;if(backend)bundle.context.source='BACKEND_RPC_READ';
 const venue=decodePumpVenueBundle(bundle),snapshot={venue,accounts:pumpWalletFixture(venue,wallet),networkFeeLamports:'5000',blockhash:fixtureBlockhash,nativeValidity:{source:venue.source,genesis:GENESIS,commitment:'finalized',blockhash:fixtureBlockhash,blockhashContextSlot:101,minContextSlot:101,currentBlockHeight:80,lastValidBlockHeight:150,checkedAt:now}};
 const intent={owner:venue.owner,agentId:venue.agentId,agentWallet:wallet,network:'solana:101',genesis:GENESIS,side:'BUY',inputMint:SOL_MINT,outputMint:venue.mint,inputAmount:'1000000',slippageBps:100,expiresAt:now+10000};
 const calls={snapshot:0,simulation:0};let clock=now,ready=qualified,readHook=()=>{},simHook=()=>{},simulationSource=venue.source;
 const adapter=createPumpRuntimeAdapter({source,qualification:()=>ready,now:()=>clock,readNativeValidity:async()=>({source:venue.source,genesis:GENESIS,commitment:'finalized',minContextSlot:101,currentBlockHeight:81,checkedAt:clock,blockhash:fixtureBlockhash,blockhashValid:true,blockhashValidationSlot:102}),readSnapshot:async()=>{calls.snapshot++;await readHook();return snapshot;},simulateUnsigned:async p=>{calls.simulation++;await simHook();return {source:simulationSource,messageHash:p.messageHash,success:true,err:null};},readFinalized:async signature=>({signature,synthetic:true}),verifyFinalizedEffects:async()=>({synthetic:true})});
 return {adapter,intent,venue,snapshot,calls,set clock(v){clock=v;},set qualified(v){ready=v;},set simulationSource(v){simulationSource=v;},readHook(fn){readHook=fn;},simHook(fn){simHook=fn;}};
}
for(const migrated of [false,true])test(`explicit synthetic backend contract maps plan only (${migrated?'swap':'curve'}), never grants execution`,async()=>{const x=await fixture({migrated}),plan=await x.adapter.prepare(x.intent,{},async()=>{});assert.equal(plan.source,'ON_CHAIN');assert.equal(plan.quote.source,'BACKEND_RPC_READ');assert.equal(plan.simulation.source,'BACKEND_RPC_READ');assert.equal(plan.simulation.notReceipt,true);assert.equal(plan.quote.provenance,'DERIVED');assert.equal(plan.quote.actualDebitVerified,false);assert.equal(plan.quote.authorizationGranted,false);assert.equal(x.venue.onChainVerified,false);if(!migrated){assert.equal(plan.effectPolicy.source,'BACKEND_RPC_READ');assert.equal(plan.effectPolicy.venueExecutionQualified,false);assert.equal(plan.effectPolicy.authorizationGranted,false);}assert.equal(await x.adapter.verifyPrepared({plan}),true);assert.equal('sign'in x.adapter,false);assert.equal('broadcast'in x.adapter,false);});
test('default fixture contract stays fixture and never becomes qualified',async()=>{const x=await fixture({backend:false,source:'LOCAL_FIXTURE'}),p=await x.adapter.prepare(x.intent,{},async()=>{});assert.equal(p.source,'LOCAL_FIXTURE');assert.equal(x.adapter.qualification(),false);assert.equal(p.effectPolicy.source,'LOCAL_FIXTURE');assert.equal(await x.adapter.verifyPrepared({plan:p}),true);});
test('default source rejects backend snapshot before simulation',async()=>{const x=await fixture(),adapter=createPumpRuntimeAdapter({readSnapshot:()=>x.snapshot,simulateUnsigned:()=>{throw Error('MUST_NOT_SIMULATE');}});await assert.rejects(adapter.prepare(x.intent,{},async()=>{}),/READ_SOURCE/);});
test('explicit ON_CHAIN cannot promote LOCAL_FIXTURE despite qualification shim',async()=>{const x=await fixture({backend:false});await assert.rejects(x.adapter.prepare(x.intent,{},async()=>{}),/READ_SOURCE/);assert.equal(x.calls.simulation,0);});
for(const value of [false,undefined,null,1,'true',Promise.resolve(true)])test(`nonboolean qualification ${String(value)} stops before reads`,async()=>{const x=await fixture({qualified:value});if(value===undefined)x.qualified=undefined;await assert.rejects(x.adapter.prepare(x.intent,{},async()=>{}),/VENUE_NOT_QUALIFIED/);assert.deepEqual(x.calls,{snapshot:0,simulation:0});});
test('missing ON_CHAIN qualification remains default false without reading',async()=>{let reads=0;const a=createPumpRuntimeAdapter({source:'ON_CHAIN',readSnapshot:()=>{reads++;}});await assert.rejects(a.prepare({}, {},async()=>{}),/VENUE_NOT_QUALIFIED/);assert.equal(reads,0);});
for(const source of ['BACKEND_RPC_READ','REAL','UNKNOWN',null])test(`invalid execution source ${source} rejects at construction`,()=>assert.throws(()=>createPumpRuntimeAdapter({source}),/ADAPTER_SOURCE/));
test('cloned or relabelled venue descriptor lacks genuine decoder identity',async()=>{const x=await fixture();x.snapshot.venue=JSON.parse(JSON.stringify(x.venue));await assert.rejects(x.adapter.prepare(x.intent,{},async()=>{}),/DECODED_STATE_REQUIRED/);assert.equal(x.calls.simulation,0);});
for(const phase of ['snapshot','authority1','authority2','simulation','authority3'])test(`qualification revocation during ${phase} rejects new preparation`,async()=>{const x=await fixture();let guards=0;x.readHook(()=>{if(phase==='snapshot')x.qualified=false;});x.simHook(()=>{if(phase==='simulation')x.qualified=false;});await assert.rejects(x.adapter.prepare(x.intent,{},async()=>{if(phase===`authority${++guards}`)x.qualified=false;}),/VENUE_NOT_QUALIFIED/);x.qualified=true;await assert.rejects(x.adapter.verifyPrepared({plan:{source:'ON_CHAIN',messageHash:'absent'}}),/OPTIONS_MISSING/);});
test('wrong simulation provenance is rejected',async()=>{const x=await fixture();x.simulationSource='LOCAL_FIXTURE';await assert.rejects(x.adapter.prepare(x.intent,{},async()=>{}),/SIMULATION_FAILED/);});
test('extra await cannot resurrect failed simulation through a queued promise mutation',async()=>{const x=await fixture(),a=createPumpRuntimeAdapter({source:'ON_CHAIN',qualification:()=>true,now:()=>now,readSnapshot:()=>x.snapshot,simulateUnsigned:p=>{const simulation={source:'BACKEND_RPC_READ',messageHash:p.messageHash,success:false,err:{SyntheticFailure:true}},promise=Promise.resolve(simulation);promise.then(()=>queueMicrotask(()=>{simulation.success=true;simulation.err=null;}));return promise;}});await assert.rejects(a.prepare(x.intent,{},async()=>{}),/SIMULATION_FAILED/);});
test('snapshot wallet balance detaches before extra promise continuation',async()=>{const x=await fixture();x.snapshot.accounts.wallet.lamports=1;const a=createPumpRuntimeAdapter({source:'ON_CHAIN',qualification:()=>true,now:()=>now,readSnapshot:()=>{const p=Promise.resolve(x.snapshot);p.then(()=>queueMicrotask(()=>{x.snapshot.accounts.wallet.lamports=200000000;}));return p;},simulateUnsigned:()=>{throw Error('MUST_NOT_SIMULATE');}});await assert.rejects(a.prepare(x.intent,{},async()=>{}),/BALANCE|RESERVE|FEE/);});
test('queued qualification revocation stops the next simulator call before it starts',async()=>{const x=await fixture();let guards=0;await assert.rejects(x.adapter.prepare(x.intent,{},()=>{const p=Promise.resolve();if(++guards===2)p.then(()=>queueMicrotask(()=>{x.qualified=false;}));return p;}),/VENUE_NOT_QUALIFIED/);assert.equal(x.calls.simulation,0);});
test('verifyPrepared denies revocation before and during canonical byte validation',async()=>{const x=await fixture(),plan=await x.adapter.prepare(x.intent,{},async()=>{});x.qualified=false;await assert.rejects(x.adapter.verifyPrepared({plan}),/VENUE_NOT_QUALIFIED/);x.qualified=true;const pending=x.adapter.verifyPrepared({plan});x.qualified=false;await assert.rejects(pending,/VENUE_NOT_QUALIFIED/);});
test('passive dependencies remain usable after current qualification revocation',async()=>{const x=await fixture({qualified:false});assert.equal(x.adapter.qualification(),false);assert.deepEqual(await x.adapter.readFinalized('same-existing-signature',{status:'UNKNOWN'}),{signature:'same-existing-signature',synthetic:true});assert.deepEqual(await x.adapter.verifyFinalizedEffects({},{}),{synthetic:true});});
test('final executor authority await revocation cannot persist execution or reservation',async t=>{const x=await fixture(),db=new DatabaseSync(':memory:');t.after(()=>db.close());const ledger=createPumpRuntimeLedger(db,{source:'ON_CHAIN',now:()=>now});let reads=0;
 const context={authenticated:true,owner:x.intent.owner,agentId:x.intent.agentId,agentWallet:wallet,associatedMint:x.venue.mint,network:'solana:101',genesis:GENESIS,authorityVerified:true,revision:1,paused:false,enabled:true,killSwitch:false,emergencyStop:false,liveEnabled:false,broadcastEnabled:false};
 const e=createPumpRuntimeExecutor({source:'ON_CHAIN',ledger,adapter:x.adapter,readContext:async()=>{if(++reads===6)x.qualified=false;return structuredClone(context);},now:()=>now});
 await assert.rejects(e.prepare({}, {...x.intent,requestKey:'synthetic-source-guard-001'}),/VENUE_NOT_QUALIFIED/);assert.equal(reads,6);assert.equal(db.prepare('select count(*) n from pump_runtime_executions').get().n,0);assert.equal(db.prepare('select count(*) n from real_reserved_accounts').get().n,0);assert.equal(ledger.position(x.intent.agentId,x.venue.mint),null);assert.equal(db.prepare('select count(*) n from pump_runtime_receipts').get().n,0);
});
for(const phase of ['prepare','pending'])test(`native proof ageing during final ${phase} owner await rejects without new effect`,async t=>{
 const x=await fixture(),db=new DatabaseSync(':memory:');t.after(()=>db.close());let clock=now,reads=0,age=false;
 const ledger=createPumpRuntimeLedger(db,{source:'ON_CHAIN',now:()=>clock});
 const context={authenticated:true,owner:x.intent.owner,agentId:x.intent.agentId,agentWallet:wallet,associatedMint:x.venue.mint,network:'solana:101',genesis:GENESIS,authorityVerified:true,revision:1,paused:false,enabled:true,killSwitch:false,emergencyStop:false,liveEnabled:false,broadcastEnabled:false};
 const engine=createPumpRuntimeExecutor({source:'ON_CHAIN',ledger,adapter:x.adapter,readContext:async()=>{if(++reads===(phase==='prepare'?6:2)&&age){clock=now+6000;x.clock=clock;}return structuredClone(context);},now:()=>clock});
 if(phase==='prepare'){age=true;await assert.rejects(engine.prepare({}, {...x.intent,requestKey:'synthetic-native-age-prepare'}),/NATIVE_HEIGHT_UNVERIFIED/);assert.equal(ledger.list(x.intent.agentId).length,0);assert.equal(db.prepare('SELECT count(*) n FROM real_reserved_accounts').get().n,0);}
 else{const r=await engine.prepare({}, {...x.intent,requestKey:'synthetic-native-age-pending'});reads=0;age=true;const tx=VersionedTransaction.deserialize(Buffer.from(r.plan.unsignedTransaction,'base64'));tx.sign([Keypair.fromSeed(Buffer.alloc(32,191))]);await assert.rejects(engine.trackPending({},r.id,Buffer.from(tx.serialize()).toString('base64')),/NATIVE_HEIGHT_UNVERIFIED/);assert.equal(ledger.get(r.id).status,'PREPARED');assert.equal(ledger.get(r.id).signature,null);}
});
