import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {Keypair,Transaction,TransactionInstruction,SystemProgram} from '@solana/web3.js';
import {agentLaunchData,assertAgentLaunch} from '../src/agent-launch-data.js';
import {assertM4ReviewLifetime} from '../src/pump-review-lifetime.js';
// LOCAL_FIXTURE lifecycle only; preparation validator is stubbed, no chain proof.
async function fixture({short=0,finalShort=false,closeDuringPrepare=false}={}){
 const owner=Keypair.generate(),agent={id:'jit',name:'Agent',creator:owner.publicKey.toBase58(),coin:{name:'Coin',ticker:'FIX'}},requests=[];let prepares=0,providers=0,bridges=0,alive=true,now=100000,stopped;
 const node=()=>({textContent:'',disabled:false,hidden:false,style:{},append(){},replaceChildren(){}}),nodes=new Map(),host={isConnected:true,innerHTML:'',querySelector:s=>{if(!nodes.has(s))nodes.set(s,node());return nodes.get(s);}};
 const build=(id,lifetime=30000)=>{const mint=Keypair.generate(),tx=new Transaction({feePayer:owner.publicKey,recentBlockhash:Keypair.generate().publicKey.toBase58()}).add(new TransactionInstruction({programId:SystemProgram.programId,keys:[{pubkey:owner.publicKey,isSigner:true,isWritable:true},{pubkey:mint.publicKey,isSigner:true,isWritable:true}],data:Buffer.alloc(0)})),unsigned=tx.serialize({requireAllSignatures:false}).toString('base64');tx.partialSign(mint);const partial=tx.serialize({requireAllSignatures:false}).toString('base64');return {status:'READY_FOR_REVIEW',executionId:id,walletApprovalOpened:false,result:{transactionBase64:unsigned,mint:mint.publicKey.toBase58(),simulation:{status:'PASS'},executionReview:{startedAt:now-(30000-lifetime),expiresAt:now+lifetime,digest:id}},partial};};
 let current=build('old',1000);class FixtureDate extends Date{static now(){return now;}}
 const context={Buffer,Transaction,agentLaunchData,assertAgentLaunch,assertM4ReviewLifetime:(r)=>assertM4ReviewLifetime(r,now),AbortSignal,crypto,Date:FixtureDate,document:{createElement:node},clearTimeout(){},setTimeout(fn,ms){if(ms===5000){now+=5000;fn();}return 1;},validatePreparation:async()=>{},fetch:async(url,options={})=>{const action=url.split('/').at(-1),body=options.body?JSON.parse(options.body):null;requests.push({action,body,method:options.method??'GET'});if(url==='/api/agents/jit')return {ok:true,json:async()=>agent};if(action==='status')return {ok:true,json:async()=>current};if(action==='prepare'){prepares++;assert.equal(body.replaceExecutionId,current.executionId);current=build(body.requestId,prepares<=short?1000:30000);if(closeDuringPrepare)alive=false;return {ok:true,json:async()=>current};}if(action==='recover'){assert.equal(body.previousExecutionId,current.executionId);current=build(body.requestId);return {ok:true,json:async()=>current};}if(action==='review'){assert.equal(body.requestId,current.executionId);current={...current,status:'AWAITING_WALLET_APPROVAL',walletApprovalOpened:true,walletTransactionBase64:current.partial};return {ok:true,json:async()=>current};}if(action==='submit'){assert.equal(body.requestId,current.executionId);assert.equal(body.transactionBase64,current.result.transactionBase64);current={...current,status:'SIGNED_NOT_BROADCAST',signature:'fixture',broadcastAttempted:false,error:'EXECUTION_REVIEW_EXPIRED'};return {ok:true,json:async()=>current};}throw Error('Unexpected '+action);}};
 vm.runInNewContext(readFileSync('src/pump-m4-ui.js','utf8').replace(/^import .*$/gm,'').replace(/export /g,''),context);
 context.mountM4Launch(host,{agent,isCurrent:()=>alive,getM4Wallet:()=>({assertBound(){},async signTransaction(bytes,review,assertReady){bridges++;assertReady();if(finalShort&&bridges===1)throw Object.assign(Error('short'),{code:'M4_REVIEW_LIFETIME_TOO_SHORT',walletRequestOpened:false});providers++;const signed=Transaction.from(Buffer.from(bytes,'base64'));signed.partialSign(owner);return signed.serialize().toString('base64');}}),capability:{m4Target:{owner:agent.creator,agentId:agent.id},m4RecoveryExecutionId:'grant'}});
 await new Promise(r=>setImmediate(r));await host.querySelector('[data-approve]').onclick();host.isConnected=false;return {requests,prepares,providers,bridges,nodes};
}
test('near-expiry JIT refresh is bounded and only fresh request/bytes reach one provider and submit',async()=>{const f=await fixture({short:1});assert.equal(f.prepares,2);assert.equal(f.providers,1);assert.equal(f.requests.filter(r=>r.action==='review').length,1);assert.equal(f.requests.filter(r=>r.action==='submit').length,1);assert.ok(f.requests.filter(r=>r.action==='submit').every(r=>r.body.requestId!=='old'));assert.equal(f.requests.filter(r=>r.action==='jit').length,1);});
test('two slow preparations stop without wallet requests or submits',async()=>{const f=await fixture({short:2});assert.equal(f.prepares,2);assert.equal(f.providers,0);assert.equal(f.requests.filter(r=>r.action==='submit').length,0);});
test('final pre-provider lifetime failure recovers unsigned evidence and still opens exactly one actual request',async()=>{const f=await fixture({finalShort:true});assert.equal(f.bridges,2);assert.equal(f.providers,1);assert.equal(f.requests.filter(r=>r.action==='recover').length,1);assert.equal(f.requests.filter(r=>r.action==='submit').length,1);});
test('closed dialog during fresh preparation cannot reach review or provider',async()=>{const f=await fixture({closeDuringPrepare:true});assert.equal(f.providers,0);assert.equal(f.requests.filter(r=>r.action==='review').length,0);assert.equal(f.requests.filter(r=>r.action==='submit').length,0);});
