import test from 'node:test';
import assert from 'node:assert/strict';
import {createM4Execution} from '../server/pump-m4.js';
import {GENESIS} from '../src/pump-readiness.js';
import {assertM4ReviewLifetime} from '../src/pump-review-lifetime.js';
import {m4Fixture} from './pump-m4-fixture.mjs';
import {walletTestConfig} from '../server/wallet-test-policy.js';
import {M4_TARGET} from '../server/pump-m4-guard.js';
import {M4_EXPIRED_RECOVERY_ID,M4_REJECTED_RECOVERY_ID,M4_DETERMINISTIC_RECOVERY_ID} from '../server/pump-m4-recovery.js';

// LOCAL_FIXTURE: synthetic keys, isolated SQLite and read-only RPC stubs.
const state=f=>JSON.parse(f.db.prepare('SELECT payload FROM m4_execution').get().payload);
async function expired(f){const ready=await f.controller.run('prepare',f.identity,{initialBuy:'0',requestId:crypto.randomUUID()}),request=f.request(ready);await f.controller.run('review',f.identity,request);const signed=f.signed();f.advance(30000);await f.controller.run('submit',f.identity,{...request,signedTransactionBase64:signed});return state(f);}
function recovery(f,overrides={}){const calls=[];const rpc=async(method,params)=>{calls.push({method,params});if(Object.hasOwn(overrides,method))return overrides[method];const old=state(f);switch(method){case'getGenesisHash':return GENESIS;case'isBlockhashValid':return {context:{slot:104},value:false};case'getBlockHeight':return old.result.lastValidBlockHeight+1;case'getSignatureStatuses':return {context:{slot:120},value:[null]};case'getTransaction':return null;case'getMultipleAccounts':assert.equal(params[1].minContextSlot,104);return {context:{slot:105},value:[null]};default:throw Error('Unexpected method '+method);}};return {calls,controller:createM4Execution({...f.deps,transport:{...f.deps.transport,rpc},recoverExecutionId:state(f).executionId})};}
test('fixed lifetime minimum rejects short review without renewing its TTL',()=>{const r={executionReview:{startedAt:100000,expiresAt:130000}};assert.equal(assertM4ReviewLifetime(r,115000),15000);assert.throws(()=>assertM4ReviewLifetime(r,115001));assert.throws(()=>assertM4ReviewLifetime(r,113000,18000));assert.throws(()=>assertM4ReviewLifetime({executionReview:{...r.executionReview,expiresAt:160000}},115000));});
test('authorized recovery archives exact old signed payload atomically and cannot replay it',async()=>{const f=m4Fixture();try{const old=await expired(f),r=recovery(f),request={initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:old.executionId};await assert.rejects(f.controller.run('recover',f.identity,request),e=>e.code==='M4_RECOVERY_NOT_AUTHORIZED');const fresh=await r.controller.run('recover',f.identity,request);assert.equal(fresh.status,'READY_FOR_REVIEW');assert.notEqual(fresh.result.mint,old.result.mint);assert.notEqual(fresh.result.transactionBase64,old.result.transactionBase64);assert.equal(fresh.signature,null);assert.deepEqual(JSON.parse(f.db.prepare('SELECT payload FROM m4_execution_history WHERE execution_id=?').get(old.executionId).payload),old);assert.equal((await r.controller.run('recover',f.identity,request)).executionId,fresh.executionId);assert.equal(f.db.prepare('SELECT count(*) n FROM m4_execution_history').get().n,1);await assert.rejects(r.controller.run('submit',f.identity,{...f.request({executionId:old.executionId,result:old.result}),signedTransactionBase64:old.signedTransactionBase64}));await assert.rejects(r.controller.run('prepare',f.identity,{initialBuy:'0',requestId:old.executionId}));assert.throws(()=>f.db.prepare('DELETE FROM m4_execution_history').run());assert.equal(f.sends(),0);}finally{f.db.close();}});
test('recovery fails closed on Mainnet/hash/signature/transaction/mint conflicts and leaves old state intact',async()=>{for(const conflict of [{getGenesisHash:'wrong'},{isBlockhashValid:{context:{slot:104},value:true}},{getBlockHeight:0},{getSignatureStatuses:{context:{slot:120},value:[{confirmationStatus:'processed'}]}},{getTransaction:{slot:105}},{getMultipleAccounts:{context:{slot:105},value:[{}]}}]){const f=m4Fixture();try{const old=await expired(f),r=recovery(f,conflict);await assert.rejects(r.controller.run('recover',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:old.executionId}));assert.deepEqual(state(f),old);assert.equal(f.db.prepare('SELECT count(*) n FROM m4_execution_history').get().n,0);assert.equal(f.sends(),0);}finally{f.db.close();}}});
test('recovery archive rolls back with failed active update and refuses send uncertainty',async()=>{const f=m4Fixture();try{const old=await expired(f),r=recovery(f);f.db.exec("CREATE TRIGGER fail_recovery BEFORE UPDATE ON m4_execution BEGIN SELECT RAISE(ABORT,'write failed'); END");await assert.rejects(r.controller.run('recover',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:old.executionId}));assert.deepEqual(state(f),old);assert.equal(f.db.prepare('SELECT count(*) n FROM m4_execution_history').get().n,0);}finally{f.db.close();}const b=m4Fixture({sendFails:true});try{const ready=await b.controller.run('prepare',b.identity,{initialBuy:'0',requestId:crypto.randomUUID()});await b.controller.run('review',b.identity,b.request(ready));await b.controller.run('submit',b.identity,{...b.request(ready),signedTransactionBase64:b.signed()});const r=recovery(b);await assert.rejects(r.controller.run('recover',b.identity,{initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:ready.executionId}),e=>e.code==='M4_RECOVERY_STATE_DENIED');assert.equal(b.sends(),1);}finally{b.db.close();}});
test('JIT unsigned supersession preserves prior evidence; near-expiry review never consumes wallet latch',async()=>{let f;f=m4Fixture({dependencies:{revalidate:async()=>{f.advance(13000);return {contextSlot:104};}}});try{const old=await f.controller.run('prepare',f.identity,{initialBuy:'0',requestId:crypto.randomUUID()});await assert.rejects(f.controller.run('review',f.identity,f.request(old)),e=>e.code==='M4_REVIEW_LIFETIME_TOO_SHORT');assert.equal(state(f).walletApprovalOpened,false);const fresh=await f.controller.run('prepare',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),replaceExecutionId:old.executionId});assert.notEqual(old.result.mint,fresh.result.mint);assert.equal(f.db.prepare('SELECT count(*) n FROM m4_execution_history').get().n,1);assert.equal(f.sends(),0);}finally{f.db.close();}});
test('unopened unsigned approval recovery waits for blockhash death and stays inside exact grant lineage',async()=>{const f=m4Fixture();try{const old=await expired(f),r=recovery(f),first=await r.controller.run('recover',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:old.executionId});await r.controller.run('review',f.identity,f.request(first));const request={initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:first.executionId};await assert.rejects(r.controller.run('recover',f.identity,request),e=>e.code==='M4_RECOVERY_REVIEW_STILL_VALID');f.advance(30000);const second=await r.controller.run('recover',f.identity,request);assert.equal(second.status,'READY_FOR_REVIEW');assert.notEqual(first.result.mint,second.result.mint);assert.equal(f.db.prepare('SELECT count(*) n FROM m4_execution_history').get().n,2);assert.equal(f.sends(),0);assert.equal(r.calls.filter(c=>c.method==='getSignatureStatuses').length,1);}finally{f.db.close();}});
test('next signed expiry cannot rearm original grant; retry of archived recovery only returns current state',async()=>{const f=m4Fixture();try{const old=await expired(f),r=recovery(f),request={initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:old.executionId},first=await r.controller.run('recover',f.identity,request),fresh=await r.controller.run('prepare',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),replaceExecutionId:first.executionId});assert.equal((await r.controller.run('recover',f.identity,request)).executionId,fresh.executionId);await r.controller.run('review',f.identity,f.request(fresh));const signed=f.signed();f.advance(30000);await r.controller.run('submit',f.identity,{...f.request(fresh),signedTransactionBase64:signed});const quarantined=state(f);await assert.rejects(r.controller.run('recover',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:fresh.executionId}),e=>e.code==='M4_RECOVERY_NOT_AUTHORIZED');assert.deepEqual(state(f),quarantined);assert.equal(f.db.prepare('SELECT count(*) n FROM m4_execution_history').get().n,2);assert.equal(f.sends(),0);}finally{f.db.close();}});
test('staging recovery config grants only the separately authorized expired execution',()=>{const config={origin:'https://staging.tekkteam.tech',port:4395,dataDir:'/var/lib/tekkteam-staging',rpcUrl:'https://fixture.example',launchPreparation:true,m4Launch:M4_TARGET};assert.equal(walletTestConfig(config).m4RecoveryExecutionId,undefined);assert.equal(walletTestConfig({...config,m4RecoveryExecutionId:M4_EXPIRED_RECOVERY_ID}).m4RecoveryExecutionId,M4_EXPIRED_RECOVERY_ID);assert.throws(()=>walletTestConfig({...config,m4RecoveryExecutionId:crypto.randomUUID()}));});
async function rejected(f,id=M4_REJECTED_RECOVERY_ID){const ready=await f.controller.run('prepare',f.identity,{initialBuy:'0',requestId:id});await f.controller.run('review',f.identity,f.request(ready));await f.controller.run('reject',f.identity,{requestId:ready.executionId});f.advance(30000);return state(f);}
test('exact rejected grant recovers once with fresh blockhash and cannot renew after the next review or rejection',async()=>{const f=m4Fixture({freshBlockhash:true});try{const old=await rejected(f),r=recovery(f),request={initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:old.executionId};const fresh=await r.controller.run('recover',f.identity,request);assert.notEqual(fresh.result.recentBlockhash,old.result.recentBlockhash);assert.notEqual(fresh.result.mint,old.result.mint);assert.deepEqual(JSON.parse(f.db.prepare('SELECT payload FROM m4_execution_history WHERE execution_id=?').get(old.executionId).payload),old);assert.equal((await r.controller.run('recover',f.identity,request)).executionId,fresh.executionId);await r.controller.run('review',f.identity,f.request(fresh));f.advance(30000);const retry={initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:fresh.executionId};await assert.rejects(r.controller.run('recover',f.identity,retry),e=>e.code==='M4_RECOVERY_NOT_AUTHORIZED');await r.controller.run('reject',f.identity,{requestId:fresh.executionId});await assert.rejects(r.controller.run('recover',f.identity,retry),e=>e.code==='M4_RECOVERY_NOT_AUTHORIZED');assert.equal(f.sends(),0);assert.equal(r.calls.filter(c=>c.method==='getSignatureStatuses').length,0);}finally{f.db.close();}});
test('rejected recovery refuses reused blockhash or any evidence of signature/broadcast/observed mint',async()=>{for(const change of ['hash','signature','broadcast','mint']){const f=m4Fixture({freshBlockhash:change!=='hash'});try{await rejected(f);if(change==='signature'||change==='broadcast'){const s=state(f);if(change==='signature')s.signature='unexpected';else s.broadcastAttempted=true;f.db.prepare('UPDATE m4_execution SET payload=?').run(JSON.stringify(s));}const old=state(f),r=recovery(f,change==='mint'?{getMultipleAccounts:{context:{slot:105},value:[{}]}}:{});await assert.rejects(r.controller.run('recover',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:old.executionId}));assert.deepEqual(state(f),old);assert.equal(f.db.prepare('SELECT count(*) n FROM m4_execution_history').get().n,0);assert.equal(f.sends(),0);}finally{f.db.close();}}});
test('rejected exact config requires M4 launch and never grants a random execution',()=>{const config={origin:'https://staging.tekkteam.tech',port:4395,dataDir:'/var/lib/tekkteam-staging',rpcUrl:'https://fixture.example',launchPreparation:true,m4Launch:M4_TARGET};assert.equal(walletTestConfig({...config,m4RecoveryExecutionId:M4_REJECTED_RECOVERY_ID}).m4RecoveryExecutionId,M4_REJECTED_RECOVERY_ID);assert.throws(()=>walletTestConfig({...config,m4Launch:undefined,m4RecoveryExecutionId:M4_REJECTED_RECOVERY_ID}));});

// LOCAL_FIXTURE: the new user permission extends only this exact rejected record.
test('deterministic fee grant recovers only exact d16 once; a child rejection never renews it',async()=>{const cfg={origin:'https://staging.tekkteam.tech',port:4395,dataDir:'/isolated',rpcUrl:'https://fixture.example',launchPreparation:true,m4Launch:M4_TARGET};assert.equal(walletTestConfig({...cfg,m4RecoveryExecutionId:M4_DETERMINISTIC_RECOVERY_ID}).m4RecoveryExecutionId,M4_DETERMINISTIC_RECOVERY_ID);assert.throws(()=>walletTestConfig({...cfg,m4RecoveryExecutionId:crypto.randomUUID()}));const f=m4Fixture({freshBlockhash:true});try{const old=await rejected(f,M4_DETERMINISTIC_RECOVERY_ID),r=recovery(f),fresh=await r.controller.run('recover',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:old.executionId});assert.notEqual(fresh.result.recentBlockhash,old.result.recentBlockhash);assert.notEqual(fresh.result.mint,old.result.mint);assert.deepEqual(JSON.parse(f.db.prepare('SELECT payload FROM m4_execution_history WHERE execution_id=?').get(old.executionId).payload),old);await r.controller.run('review',f.identity,f.request(fresh));await r.controller.run('reject',f.identity,{requestId:fresh.executionId});f.advance(30000);await assert.rejects(r.controller.run('recover',f.identity,{initialBuy:'0',requestId:crypto.randomUUID(),previousExecutionId:fresh.executionId}),e=>e.code==='M4_RECOVERY_NOT_AUTHORIZED');assert.equal(f.sends(),0);}finally{f.db.close();}});
