import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {DatabaseSync} from 'node:sqlite';
import {installPumpRuntimeRoutes} from '../server/dex/pump-runtime-routes.js';import {createServer} from '../server/app.js';
import {Keypair,SystemProgram,TransactionMessage,VersionedTransaction} from '@solana/web3.js';import {createHash} from 'node:crypto';import {GENESIS} from '../src/pump-readiness.js';import {SOL_MINT} from '../server/dex/intent.js';
const owner='fixture-owner',agent={id:'fixture-agent',creator:owner,tradingWallet:'fixture-wallet'};
async function fixture(t,dependencies){const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE agent_wallets(agent_id TEXT,address TEXT)');db.prepare('INSERT INTO agent_wallets VALUES(?,?)').run(agent.id,agent.tradingWallet);const app=express();app.use(express.json());const auth=(req,res,next)=>{if(req.headers['x-fixture-owner']!==owner)return res.sendStatus(401);req.session={address:owner};next();};const installed=installPumpRuntimeRoutes(app,{db,auth,owned:()=>({agent}),sessionValid:req=>req.session?.address===owner,assertTarget:()=>({kind:'ASSOCIATED_COIN',mint:'fixture-mint'}),dependencies});app.use((e,req,res,next)=>res.status(e.status??409).json({error:e.code??e.message}));const s=app.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));t.after(async()=>{s.closeAllConnections();await new Promise(r=>s.close(r));db.close();});const call=async(route,body,authenticated=true)=>{const r=await fetch('http://127.0.0.1:'+s.address().port+'/api/agents/'+agent.id+'/pump-runtime'+route,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json',...(authenticated?{'x-fixture-owner':owner}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,data:r.status===401?null:await r.json()};};return {db,call,installed};}
test('default registered route is disabled; flags cannot inject adapter or create Pump schema',async t=>{const f=await fixture(t);assert.equal((await f.call('')).data.registration,'REGISTERED_DISARMED');assert.equal((await f.call('')).data.enabled,false);assert.equal((await f.call('',undefined,false)).status,401);assert.equal((await f.call('/prepare',{})).data.error,'PUMP_RUNTIME_DISABLED');assert.equal(f.db.prepare("SELECT count(*) n FROM sqlite_master WHERE name LIKE 'pump_runtime_%'").get().n,0);assert.equal(f.installed.engine,null);});
test('owner Pause is independent of mint/custody/RPC readiness and never clears pending holds',async t=>{let reads=0;const f=await fixture(t,{source:'LOCAL_FIXTURE',localDisarmed:true,adapter:{},associatedMint:()=>{throw Error('UNAVAILABLE');},readAuthority:()=>{reads++;throw Error('UNAVAILABLE');}});const r=await f.call('/pause',{});assert.equal(r.status,200);assert.equal(r.data.paused,true);assert.equal(reads,0);assert.equal(f.installed.ledger.control(agent.id).paused,1);assert.equal((await f.call('/pause',{enable:true})).status,409);});
test('runtime constructor DI cannot enter production or Mainnet server',()=>{for(const p of [{network:'mainnet',mainnetSafetyMode:true,rpc:'https://fixture.invalid'},{network:'local',production:true}])assert.throws(()=>createServer({...p,pumpRuntimeDependencies:{}}),/isolated local backend/);});

test('HTTP DI prepare/read/cancel/Pause uses runtime authority and exact associated mint',async t=>{
 const wallet=Keypair.fromSeed(Buffer.alloc(32,32));agent.tradingWallet=wallet.publicKey.toBase58();let authorized=true;
 t.after(()=>{agent.tradingWallet='fixture-wallet';});
 const adapter={prepare:async intent=>{const message=new TransactionMessage({payerKey:wallet.publicKey,recentBlockhash:SOL_MINT,instructions:[SystemProgram.transfer({fromPubkey:wallet.publicKey,toPubkey:wallet.publicKey,lamports:0})]}).compileToV0Message();return {source:'LOCAL_FIXTURE',observedAt:Date.now(),snapshotSlot:100,venueKind:'PUMP_BONDING_CURVE',messageHash:createHash('sha256').update(message.serialize()).digest('hex'),unsignedTransaction:Buffer.from(new VersionedTransaction(message).serialize()).toString('base64'),quote:{...intent,estimatedOutput:'50',minimumOutput:'50'},feeCapLamports:'10000',rentCapLamports:'0',refundCapLamports:'0',balances:{native:'200000000',wsol:'0',token:'0'}};},verifyPrepared:async()=>true};
 const f=await fixture(t,{source:'LOCAL_FIXTURE',localDisarmed:true,adapter,associatedMint:()=> 'fixture-mint',readAuthority:async()=>({authorityVerified:authorized,revision:1,network:'solana:101',genesis:GENESIS,paused:false,killSwitch:false,emergencyStop:false,enabled:true,liveEnabled:false,broadcastEnabled:false})});
 const body={agentId:agent.id,owner,agentWallet:agent.tradingWallet,network:'solana:101',genesis:GENESIS,side:'BUY',inputMint:SOL_MINT,outputMint:'fixture-mint',inputAmount:'100000',slippageBps:100,expiresAt:Date.now()+20000,requestKey:'http-runtime-fixture-001'};
 const prepared=await f.call('/prepare',body);assert.equal(prepared.status,200);assert.equal(prepared.data.status,'PREPARED');assert.equal(prepared.data.notBroadcast,true);
 const read=await f.call('/'+prepared.data.id);assert.equal(read.data.receipt,null);assert.equal(read.data.source,'LOCAL_FIXTURE');assert.equal('unsignedTransaction'in read.data,false);
 assert.equal((await f.call('/prepare',body)).data.id,prepared.data.id);assert.equal((await f.call('/'+prepared.data.id+'/cancel',{})).data.status,'CANCELLED');
 authorized=false;assert.equal((await f.call('/prepare',{...body,requestKey:'http-runtime-fixture-002'})).data.error,'PUMP_RUNTIME_AUTHORITY');authorized=true;
 assert.equal((await f.call('/prepare',{...body,outputMint:'unrelated-mint',requestKey:'http-runtime-fixture-003'})).data.error,'PUMP_RUNTIME_AUTHORITY');
 assert.equal((await f.call('/pause',{})).data.paused,true);assert.equal((await f.call('/prepare',{...body,requestKey:'http-runtime-fixture-004'})).data.error,'PUMP_RUNTIME_PAUSED_OR_DISARMED');assert.equal(f.db.prepare('SELECT count(*) n FROM real_reserved_accounts').get().n,0);
});
