import test from 'node:test';
import assert from 'node:assert/strict';
import {Keypair,PublicKey,VersionedTransaction,SystemProgram} from '@solana/web3.js';
import bs58 from 'bs58';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {pumpAccountFixture,pumpWalletFixture,fixtureBlockhash} from './pump-account-fixture.mjs';
import {decodePumpVenueBundle} from '../server/dex/pump-account-decoder.js';
import {createPumpCurveEffectPolicy,verifyFinalizedPumpCurveEffects} from '../server/dex/pump-finalized-effects.js';
import {curveProgram,pumpSdk,BN} from '../server/dex/pump-sdk-boundary.js';
import {buildOfflinePumpEnvelope} from '../server/dex/pump-offline-envelope.js';
import {createPumpRuntimeAdapter} from '../server/dex/pump-runtime-adapter.js';
import {createPumpRuntimeLedger} from '../server/dex/pump-runtime-ledger.js';
import {createPumpRuntimeExecutor} from '../server/dex/pump-runtime-executor.js';
import {createPumpFinalizedReader} from '../server/dex/pump-finalized-reader.js';
import {GENESIS} from '../src/pump-readiness.js';
import {digest,SOL_MINT} from '../server/dex/intent.js';

const now=1800000000000,signer=Keypair.fromSeed(Buffer.alloc(32,77)),wallet=signer.publicKey.toBase58();
const pump=pumpSdk.PUMP_PROGRAM_ID.toBase58(),system=SystemProgram.programId.toBase58();
const eventPrefix=Buffer.from('e445a52e51cb9a1dbddb7fd34ee661ee','hex');
function defaultField(type){if(type==='pubkey')return SystemProgram.programId;if(type==='bool')return false;if(type==='string')return '';if(type?.vec)return [];return new BN(0);}
function eventFields(){return Object.fromEntries(curveProgram.idl.types.find(t=>t.name==='tradeEvent').type.fields.map(f=>[f.name,defaultField(f.type)]));}
async function fixture(side='BUY'){
 const bundle=await pumpAccountFixture();bundle.context.observedAt=now;
 const venue=decodePumpVenueBundle(bundle),buy=side==='BUY',intent={agentId:venue.agentId,owner:venue.owner,agentWallet:wallet,network:'solana:101',genesis:GENESIS,side,inputMint:buy?SOL_MINT:venue.mint,outputMint:buy?venue.mint:SOL_MINT,inputAmount:buy?'100000000':'1000000000',slippageBps:100,expiresAt:now+10000};
 const options={venue,intent,executionWallet:wallet,blockhash:fixtureBlockhash,networkFeeLamports:'5000',now};
 const envelope=await buildOfflinePumpEnvelope(options),effectPolicy=await createPumpCurveEffectPolicy(options),quote=envelope.quote;
 const r={id:'local-finalized-fixture',source:'LOCAL_FIXTURE',intent,signature:null,plan:{source:'LOCAL_FIXTURE',venueKind:'PUMP_BONDING_CURVE',snapshotSlot:100,proofHash:venue.proofHash,quote:structuredClone(quote),messageHash:envelope.messageHash,unsignedTransaction:envelope.unsignedTransaction,effectPolicy,feeCapLamports:'10000',rentCapLamports:'0',refundCapLamports:'0',risk:{protectedLamports:'2020000'}}};
 const tx=VersionedTransaction.deserialize(Buffer.from(envelope.unsignedTransaction,'base64'));tx.sign([signer]);r.signature=bs58.encode(tx.signatures[0]);
 r.planDigest=digest(r.plan);r.fingerprint=digest(r.intent);
 const keys=tx.message.staticAccountKeys.map(k=>k.toBase58()),roles=effectPolicy.roles,at=address=>keys.indexOf(address);
 const sol=buy?99000000n:100000n,tokens=buy?BigInt(quote.estimatedOutput):BigInt(intent.inputAmount),protocol=(sol*30n+9999n)/10000n,creator=(sol*50n+9999n)/10000n;
 const pre=keys.map(()=>1000000),post=[...pre];pre[0]=200000000;pre[at(roles.bondingCurve)]=1000000000;pre[at(roles.associatedUser)]=2039280;pre[at(roles.associatedBondingCurve)]=2039280;post.splice(0,post.length,...pre);
 const add=(address,n)=>post[at(address)]+=Number(n);
 add(wallet,(buy?-sol-protocol-creator:sol-protocol-creator)-5000n);add(roles.bondingCurve,buy?sol:-sol);add(roles.feeRecipient,protocol);add(roles.creatorVault,creator);
 const token=(address,owner,amount)=>({accountIndex:at(address),mint:venue.mint,owner,programId:venue.tokenProgram,uiTokenAmount:{decimals:6,amount:amount.toString()}});
 const baseBefore=2000000000n,curveBefore=793100000000000n,change=buy?tokens:-tokens;
 const meta={err:null,fee:5000,preBalances:pre,postBalances:post,preTokenBalances:[token(roles.associatedUser,wallet,baseBefore),token(roles.associatedBondingCurve,roles.bondingCurve,curveBefore)],postTokenBalances:[token(roles.associatedUser,wallet,baseBefore+change),token(roles.associatedBondingCurve,roles.bondingCurve,curveBefore-change)],innerInstructions:[{index:0,instructions:[]}],logMessages:[]};
 const event={...eventFields(),mint:tx.message.staticAccountKeys[at(roles.mint)],user:signer.publicKey,creator:new PublicKey(venue.owner),feeRecipient:tx.message.staticAccountKeys[at(roles.feeRecipient)],solAmount:new BN(sol.toString()),tokenAmount:new BN(tokens.toString()),isBuy:buy,ixName:buy?'buy_exact_sol_in':'sell',feeBasisPoints:new BN(30),fee:new BN(protocol.toString()),creatorFeeBasisPoints:new BN(50),creatorFee:new BN(creator.toString())};
 const cpis=meta.innerInstructions[0].instructions;
 const cpi=(program,accounts,data)=>cpis.push({programIdIndex:at(program),accounts:accounts.map(at),stackHeight:2,data:bs58.encode(data)});
 const transfer=Buffer.alloc(10);transfer[0]=12;transfer.writeBigUInt64LE(tokens,1);transfer[9]=6;
 cpi(venue.tokenProgram,buy?[roles.associatedBondingCurve,venue.mint,roles.associatedUser,roles.bondingCurve]:[roles.associatedUser,venue.mint,roles.associatedBondingCurve,wallet],transfer);
 if(buy)for(const [to,n]of [[roles.bondingCurve,sol],[roles.feeRecipient,protocol],[roles.creatorVault,creator]]){const data=Buffer.alloc(12);data.writeUInt32LE(2);data.writeBigUInt64LE(n,4);cpi(system,[wallet,to],data);}
 const setEvent=()=>{const data=Buffer.concat([eventPrefix,curveProgram.coder.types.encode('tradeEvent',event)]),row={programIdIndex:at(pump),accounts:[at(roles.eventAuthority)],stackHeight:2,data:bs58.encode(data)};if(cpis.at(-1)?.programIdIndex===at(pump))cpis[cpis.length-1]=row;else cpis.push(row);};setEvent();
 const setLogs=()=>{meta.logMessages=[`Program ${pump} invoke [1]`,...cpis.flatMap(i=>[`Program ${keys[i.programIdIndex]} invoke [2]`,`Program ${keys[i.programIdIndex]} success`]),`Program ${pump} success`];};setLogs();
 const o={source:'LOCAL_FIXTURE',finalized:true,network:'solana:101',genesis:GENESIS,signature:r.signature,slot:101,error:null,transaction:Buffer.from(tx.serialize()).toString('base64'),meta};
 return {r,o,venue,options,envelope,event,setEvent,setLogs,keys,roles,at,tx,sol,tokens,protocol,creator};
}
for(const side of ['BUY','SELL'])test(`exact ${side} atomic effects remain LOCAL_FIXTURE and grant no execution`,async()=>{
 const x=await fixture(side),e=verifyFinalizedPumpCurveEffects(x.r,x.o);assert.equal(e.source,'LOCAL_FIXTURE');assert.equal(e.venueExecutionQualified,false);assert.equal(e.authorizationGranted,false);assert.equal(e.rentLamports,'0');assert.equal(e.wsolDelta,'0');assert.equal(e.venueFees.protocol,x.protocol.toString());assert.equal(e.venueFees.creator,x.creator.toString());assert.equal(e.actualInput,(side==='BUY'?x.sol+x.protocol+x.creator:x.tokens).toString());assert.equal(e.actualOutput,(side==='BUY'?x.tokens:x.sol-x.protocol-x.creator).toString());assert(Object.isFrozen(e.venueFees));
});
for(const [name,change]of [
 ['missing policy',x=>delete x.r.plan.effectPolicy],['mutated policy',x=>x.r.plan.effectPolicy={...x.r.plan.effectPolicy,creator:wallet}],['mutable quote',x=>x.r.plan.quote.minimumOutput='1'],['wrong owner',x=>x.r.intent.owner=wallet],['fixture relabel',x=>{x.r.source='ON_CHAIN';x.o.source='ON_CHAIN';x.r.plan.source='ON_CHAIN';}],['not finalized',x=>x.o.finalized=false],['Devnet',x=>x.o.genesis='devnet'],['old slot',x=>x.o.slot=99],['foreign signature',x=>x.o.signature='different'],['signature bytes',x=>{const tx=VersionedTransaction.deserialize(Buffer.from(x.o.transaction,'base64'));tx.signatures[0][0]^=1;x.o.transaction=Buffer.from(tx.serialize()).toString('base64');x.r.signature=x.o.signature=bs58.encode(tx.signatures[0]);}],
 ['missing meta',x=>delete x.o.meta],['unknown error',x=>x.o.error=undefined],['mismatched error',x=>x.o.meta.err={InstructionError:[0,'error']}],['partial native balances',x=>x.o.meta.postBalances.pop()],['unsafe balance',x=>x.o.meta.preBalances[0]=Number.MAX_SAFE_INTEGER+1],['fee cap',x=>x.r.plan.feeCapLamports='1'],['rent cap',x=>x.r.plan.rentCapLamports='1'],['readonly mutation',x=>{const i=x.keys.findIndex((_,i)=>!x.tx.message.isAccountWritable(i));x.o.meta.postBalances[i]++;x.o.meta.postBalances[0]--;}],['native imbalance',x=>x.o.meta.postBalances[0]++],['hidden balanced debit',x=>{x.o.meta.postBalances[x.at(x.roles.userVolumeAccumulator)]--;x.o.meta.postBalances[0]++;}],['new auxiliary',x=>{const i=x.at(x.roles.userVolumeAccumulator),n=x.o.meta.preBalances[i];x.o.meta.preBalances[i]=0;x.o.meta.postBalances[i]-=n;}],['reserve',x=>x.r.plan.risk.protectedLamports='200000000'],
 ['missing token',x=>x.o.meta.postTokenBalances.pop()],['unrelated token',x=>x.o.meta.preTokenBalances[0].mint=SOL_MINT],['foreign authority',x=>x.o.meta.postTokenBalances[0].owner=x.r.intent.owner],['wrong program',x=>x.o.meta.preTokenBalances[0].programId=system],['decimals',x=>x.o.meta.postTokenBalances[0].uiTokenAmount.decimals=9],['duplicate token index',x=>x.o.meta.preTokenBalances[1].accountIndex=x.o.meta.preTokenBalances[0].accountIndex],['token imbalance',x=>x.o.meta.postTokenBalances[0].uiTokenAmount.amount=(BigInt(x.o.meta.postTokenBalances[0].uiTokenAmount.amount)+1n).toString()],['token rent',x=>{x.o.meta.postBalances[x.at(x.roles.associatedUser)]++;x.o.meta.postBalances[0]--;}],
 ['missing inner',x=>delete x.o.meta.innerInstructions],['wrong top ix',x=>x.o.meta.innerInstructions[0].index=1],['missing stack',x=>delete x.o.meta.innerInstructions[0].instructions.at(-1).stackHeight],['foreign event authority',x=>x.o.meta.innerInstructions[0].instructions.at(-1).accounts=[0]],['unknown event tag',x=>{const row=x.o.meta.innerInstructions[0].instructions.at(-1),d=Buffer.from(bs58.decode(row.data));d[0]^=1;row.data=bs58.encode(d);}],['truncated event',x=>{const row=x.o.meta.innerInstructions[0].instructions.at(-1);row.data=bs58.encode(bs58.decode(row.data).subarray(0,-1));}],['trailing event byte',x=>{const row=x.o.meta.innerInstructions[0].instructions.at(-1);row.data=bs58.encode(Buffer.concat([bs58.decode(row.data),Buffer.from([0])]));}],['duplicate event',x=>{x.o.meta.innerInstructions[0].instructions.push({...x.o.meta.innerInstructions[0].instructions.at(-1)});x.setLogs();}],
 ['event foreign owner',x=>{x.event.user=x.tx.message.staticAccountKeys[x.at(x.roles.creatorVault)];x.setEvent();}],['event side',x=>{x.event.isBuy=false;x.setEvent();}],['event method',x=>{x.event.ixName='buy';x.setEvent();}],['fee arithmetic',x=>{x.event.feeBasisPoints=new BN(31);x.setEvent();}],['buyback split',x=>{x.event.buybackFee=new BN(1);x.setEvent();}],['mayhem',x=>{x.event.mayhemMode=true;x.setEvent();}],['holder rewards',x=>{x.event.holderRewards=new BN(1);x.setEvent();}],['volume mode',x=>{x.event.trackVolume=true;x.setEvent();}],['event token mismatch',x=>{x.event.tokenAmount=x.event.tokenAmount.addn(1);x.setEvent();}],
 ['CPI token amount',x=>{const row=x.o.meta.innerInstructions[0].instructions[0],d=Buffer.from(bs58.decode(row.data));d.writeBigUInt64LE(x.tokens+1n,1);row.data=bs58.encode(d);}],['CPI account creation',x=>{const row=x.o.meta.innerInstructions[0].instructions[1],d=Buffer.from(bs58.decode(row.data));d.writeUInt32LE(0);row.data=bs58.encode(d);}],['CPI native mismatch',x=>{const row=x.o.meta.innerInstructions[0].instructions[1],d=Buffer.from(bs58.decode(row.data));d.writeBigUInt64LE(x.sol+1n,4);row.data=bs58.encode(d);}],['missing BUY transfer',x=>{x.o.meta.innerInstructions[0].instructions.splice(1,1);x.setLogs();}],['missing logs',x=>delete x.o.meta.logMessages],['unbalanced log',x=>x.o.meta.logMessages.pop()],['fake root',x=>x.o.meta.logMessages[0]=`Program ${system} invoke [1]`],['CPI log mismatch',x=>x.o.meta.logMessages[1]=`Program ${system} invoke [2]`],['truncated log marker',x=>x.o.meta.logMessages.push('Log truncated')]
])test(`finalized verifier rejects ${name}`,async()=>{const x=await fixture();change(x);assert.throws(()=>verifyFinalizedPumpCurveEffects(x.r,x.o));});
test('finalized fee-only failure never accepts token/native movement',async()=>{const x=await fixture();x.o.error=x.o.meta.err={InstructionError:[0,'SyntheticFailure']};x.o.meta.postBalances=[...x.o.meta.preBalances];x.o.meta.postBalances[0]-=5000;x.o.meta.postTokenBalances=structuredClone(x.o.meta.preTokenBalances);const e=verifyFinalizedPumpCurveEffects(x.r,x.o);assert.equal(e.actualInput,'0');assert.equal(e.actualOutput,'0');assert.equal(e.nativeDelta,'-5000');x.o.meta.postTokenBalances[0].uiTokenAmount.amount='2000000001';assert.throws(()=>verifyFinalizedPumpCurveEffects(x.r,x.o));});
test('expired historical review/policy still verifies exact finalized bytes after JSON restart',async t=>{t.mock.method(Date,'now',()=>now+60000);const x=await fixture('SELL'),restored=JSON.parse(JSON.stringify(x.r));assert(restored.intent.expiresAt<Date.now());assert.deepEqual(verifyFinalizedPumpCurveEffects(restored,JSON.parse(JSON.stringify(x.o))),verifyFinalizedPumpCurveEffects(x.r,x.o));});
test('SDK backward-default legacy/truncated event is explicitly outside initial qualified subset',async()=>{const x=await fixture(),row=x.o.meta.innerInstructions[0].instructions.at(-1);row.data=bs58.encode(bs58.decode(row.data).subarray(0,-16));assert.throws(()=>verifyFinalizedPumpCurveEffects(x.r,x.o),/EVENT_LAYOUT/);});
test('transaction deserializer cannot silently discard trailing landed bytes',async()=>{const x=await fixture();x.o.transaction=Buffer.concat([Buffer.from(x.o.transaction,'base64'),Buffer.from([0])]).toString('base64');assert.throws(()=>verifyFinalizedPumpCurveEffects(x.r,x.o),/TRANSACTION_NONCANONICAL/);});
test('nonzero prepared buyback parameter stays unqualified even with zero event',async()=>{const x=await fixture();const p={...x.r.plan.effectPolicy,buybackBasisPoints:'1'};delete p.digest;x.r.plan.effectPolicy={...p,digest:digest(p)};x.r.planDigest=digest(x.r.plan);assert.throws(()=>verifyFinalizedPumpCurveEffects(x.r,x.o),/BUYBACK_SPLIT_UNQUALIFIED/);});
for(const [name,mutate]of [['raised fee cap',x=>x.r.plan.feeCapLamports='100000'],['lowered reserve',x=>x.r.plan.risk.protectedLamports='0'],['refund bound',x=>x.r.plan.refundCapLamports='100000'],['native balance',x=>x.r.plan.balances={native:'999999999'}]])test(`persisted plan rejects ${name} mutation`,async()=>{const x=await fixture();mutate(x);assert.throws(()=>verifyFinalizedPumpCurveEffects(x.r,x.o),/PERSISTED_PLAN_INTEGRITY/);});
function economicAmounts(x,sol,tokens){
 const buy=x.r.intent.side==='BUY',meta=x.o.meta,protocol=(sol*30n+9999n)/10000n,creator=(sol*50n+9999n)/10000n;
 x.event.solAmount=new BN(sol.toString());x.event.tokenAmount=new BN(tokens.toString());x.event.fee=new BN(protocol.toString());x.event.creatorFee=new BN(creator.toString());x.setEvent();
 meta.postBalances=[...meta.preBalances];for(const [address,change]of [[wallet,(buy?-sol-protocol-creator:sol-protocol-creator)-5000n],[x.roles.bondingCurve,buy?sol:-sol],[x.roles.feeRecipient,protocol],[x.roles.creatorVault,creator]])meta.postBalances[x.at(address)]+=Number(change);
 for(let i=0;i<2;i++)meta.postTokenBalances[i].uiTokenAmount.amount=(BigInt(meta.preTokenBalances[i].uiTokenAmount.amount)+(i===0?1n:-1n)*(buy?tokens:-tokens)).toString();
 const cpis=meta.innerInstructions[0].instructions,d=Buffer.from(bs58.decode(cpis[0].data));d.writeBigUInt64LE(tokens,1);cpis[0].data=bs58.encode(d);
 if(buy)for(const [i,n]of [[1,sol],[2,protocol],[3,creator]]){const data=Buffer.from(bs58.decode(cpis[i].data));data.writeBigUInt64LE(n,4);cpis[i].data=bs58.encode(data);}
}
for(const [name,side,change]of [['BUY above reviewed budget','BUY',x=>economicAmounts(x,101000000n,x.tokens)],['BUY below minimum tokens','BUY',x=>economicAmounts(x,x.sol,BigInt(x.r.plan.quote.minimumOutput)-1n)],['SELL excess input','SELL',x=>economicAmounts(x,x.sol,x.tokens+1n)],['SELL below minimum SOL','SELL',x=>economicAmounts(x,BigInt(x.r.plan.quote.minimumOutput)/2n,x.tokens)]])test(`atomic self-consistent ${name} still rejects`,async()=>{const x=await fixture(side);change(x);assert.throws(()=>verifyFinalizedPumpCurveEffects(x.r,x.o),/TRADE_LIMIT/);});
test('pinned read-only fee CPI is accepted; trailing fee instruction bytes are rejected',async()=>{const x=await fixture(),program=pumpSdk.getPumpFeeProgram(null),data=program.coder.instruction.encode('getFees',{isPumpPool:true,marketCapLamports:new BN('30000000000'),tradeSizeLamports:new BN(x.sol.toString()),isNewQuoteMint:{0:false}}),row={programIdIndex:x.at(x.roles.feeProgram),accounts:[x.at(x.roles.feeConfig),x.at(pump)],stackHeight:2,data:bs58.encode(data)};x.o.meta.innerInstructions[0].instructions.unshift(row);x.setLogs();assert.equal(verifyFinalizedPumpCurveEffects(x.r,x.o).source,'LOCAL_FIXTURE');row.data=bs58.encode(Buffer.concat([data,Buffer.from([0])]));assert.throws(()=>verifyFinalizedPumpCurveEffects(x.r,x.o),/FEE_CPI_UNQUALIFIED/);});
test('derived policy persists in existing adapter plan without adding finality/send ports',async()=>{const x=await fixture(),adapter=createPumpRuntimeAdapter({now:()=>now,readSnapshot:async()=>({...x.options,accounts:pumpWalletFixture(x.venue,wallet)}),simulateUnsigned:async p=>({source:'LOCAL_FIXTURE',messageHash:p.messageHash,success:true,err:null})});const plan=await adapter.prepare(x.r.intent,{},async()=>{});assert.equal(plan.effectPolicy.messageHash,plan.messageHash);assert.equal(plan.effectPolicy.authorizationGranted,false);assert.equal('sign'in adapter,false);assert.equal('broadcast'in adapter,false);assert.throws(()=>adapter.verifyFinalizedEffects(x.r,x.o),/VERIFIER_UNAVAILABLE/);});
test('default-off runtime uses genuine pure verifier; restart and rejected effects retain UNKNOWN',async t=>{
 const x=await fixture(),file=path.join(mkdtempSync(path.join(tmpdir(),'tekkteam-finalized-fixture-')),'fixture.sqlite');let db=new DatabaseSync(file),ledger=createPumpRuntimeLedger(db,{now:()=>now}),clock=now; t.after(()=>db.close());
 const context={authenticated:true,owner:x.r.intent.owner,agentId:x.r.intent.agentId,agentWallet:wallet,associatedMint:x.venue.mint,network:'solana:101',genesis:GENESIS,authorityVerified:true,revision:1,paused:false,enabled:true,killSwitch:false,emergencyStop:false,liveEnabled:false,broadcastEnabled:false};
 let missing=false,rpcFailure=false;const calls=[];
 const readFinalized=createPumpFinalizedReader({rpc:async(method,params)=>{calls.push({method,params});if(rpcFailure)throw Error('synthetic unavailable');if(method==='getGenesisHash')return GENESIS;if(method==='getSignatureStatuses')return {context:{slot:102},value:[{slot:x.o.slot,confirmations:null,confirmationStatus:'finalized',err:x.o.error}]};if(method==='getTransaction')return missing?null:{slot:x.o.slot,version:0,blockTime:null,transaction:[x.o.transaction,'base64'],meta:x.o.meta};throw Error('FORBIDDEN_RPC');}});
 const adapter=createPumpRuntimeAdapter({now:()=>clock,readSnapshot:async()=>({...x.options,accounts:pumpWalletFixture(x.venue,wallet),feeCapLamports:'10000'}),simulateUnsigned:async p=>({source:'LOCAL_FIXTURE',messageHash:p.messageHash,success:true,err:null}),readFinalized,verifyFinalizedEffects:verifyFinalizedPumpCurveEffects});
 const engine=()=>createPumpRuntimeExecutor({ledger,adapter,readContext:()=>structuredClone(context),riskPolicy:{version:'fixture-policy',maxSnapshotAgeMs:10000,maxSlippageBps:100,maxBuyLamports:'100000000',maxNetworkFeeLamports:'10000',minReserveLamports:'2000000',futureSellFeeLamports:'10000',reconciliationMarginLamports:'10000'},now:()=>clock});
 const r=await engine().prepare({}, {...x.r.intent,requestKey:'finalized-effects-fixture-001'});assert.equal(r.plan.effectPolicy.messageHash,x.r.plan.effectPolicy.messageHash);await engine().trackPending({},r.id,x.o.transaction);
 db.close();db=new DatabaseSync(file);ledger=createPumpRuntimeLedger(db,{now:()=>now});clock=now+60000;context.paused=true;context.killSwitch=true;
 missing=true;assert.equal((await engine().reconcile({},r.id)).status,'UNKNOWN');assert.equal(ledger.reservation(r.id).status,'UNKNOWN');assert.equal(ledger.receipt(r.id),null);missing=false;
 rpcFailure=true;await assert.rejects(engine().reconcile({},r.id),/RPC_UNAVAILABLE/);assert.equal(ledger.reservation(r.id).status,'UNKNOWN');assert.equal(ledger.position(r.intent.agentId,x.venue.mint),null);rpcFailure=false;
 const old=x.o.meta.postBalances[0];x.o.meta.postBalances[0]++;await assert.rejects(engine().reconcile({},r.id));assert.equal(ledger.get(r.id).status,'UNKNOWN');assert.equal(ledger.receipt(r.id),null);assert.equal(ledger.reservation(r.id).status,'UNKNOWN');x.o.meta.postBalances[0]=old;
 assert.equal((await engine().reconcile({},r.id)).status,'CONFIRMED');assert.equal(ledger.receipt(r.id).actualChainVerified,false);assert.equal(ledger.position(r.intent.agentId,x.venue.mint).source,'LOCAL_FIXTURE');assert.equal((await engine().reconcile({},r.id)).status,'CONFIRMED');
 assert(calls.every(c=>!['getSignatureStatuses','getTransaction'].includes(c.method)||JSON.stringify(c.params).includes(x.r.signature)));assert(calls.every(c=>['getGenesisHash','getSignatureStatuses','getTransaction'].includes(c.method)));
});
