import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {Keypair,PublicKey,SystemProgram,TransactionMessage,VersionedTransaction} from '@solana/web3.js';
import {createHash} from 'node:crypto';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createPumpRuntimeLedger} from '../server/dex/pump-runtime-ledger.js';
import {createPumpRuntimeExecutor} from '../server/dex/pump-runtime-executor.js';
import {createPumpRuntimeAdapter} from '../server/dex/pump-runtime-adapter.js';
import {createRealBalanceReservations} from '../server/real-balance-reservations.js';
import {GENESIS} from '../src/pump-readiness.js';
import {SOL_MINT} from '../server/dex/intent.js';
import {pumpAccountFixture,pumpWalletFixture,fixtureBlockhash} from './pump-account-fixture.mjs';
import {decodePumpVenueBundle} from '../server/dex/pump-account-decoder.js';

const now=1800000000000,signer=Keypair.fromSeed(Buffer.alloc(32,88)),wallet=signer.publicKey.toBase58(),mint=Keypair.fromSeed(Buffer.alloc(32,89)).publicKey.toBase58(),owner=Keypair.fromSeed(Buffer.alloc(32,90)).publicKey.toBase58();
function fixture(t,{swap=false,durable=false}={}){
 const file=durable?path.join(mkdtempSync(path.join(tmpdir(),'tekkteam-pump-runtime-')),'fixture.sqlite'):':memory:';
 let db=new DatabaseSync(file),ledger=createPumpRuntimeLedger(db,{now:()=>now}),clock=now;
 const context={authenticated:true,owner,agentId:'runtime-agent',agentWallet:wallet,associatedMint:mint,network:'solana:101',genesis:GENESIS,authorityVerified:true,revision:1,paused:false,enabled:true,killSwitch:false,emergencyStop:false,liveEnabled:false,broadcastEnabled:false};
 const body={owner,agentId:context.agentId,agentWallet:wallet,network:'solana:101',genesis:GENESIS,side:'BUY',inputMint:SOL_MINT,outputMint:mint,inputAmount:'100000',slippageBps:100,expiresAt:now+20000,requestKey:'runtime-local-request-001'};
 let observation=null,effects=null,prepareHook=()=>{},verifyHook=()=>{},readHook=()=>{},effectHook=()=>{},readCalls=0;
 const adapter={
  async prepare(intent){
   await prepareHook();
   const m=new TransactionMessage({payerKey:signer.publicKey,recentBlockhash:fixtureBlockhash,instructions:[SystemProgram.transfer({fromPubkey:signer.publicKey,toPubkey:new PublicKey(intent.inputMint),lamports:0})]}).compileToV0Message(),tx=new VersionedTransaction(m);
   return {source:'LOCAL_FIXTURE',observedAt:now,snapshotSlot:100,venueKind:swap?'PUMPSWAP':'PUMP_BONDING_CURVE',unsignedTransaction:Buffer.from(tx.serialize()).toString('base64'),messageHash:createHash('sha256').update(m.serialize()).digest('hex'),quote:{side:intent.side,agentId:intent.agentId,inputMint:intent.inputMint,outputMint:intent.outputMint,inputAmount:intent.inputAmount,slippageBps:intent.slippageBps,expiresAt:intent.expiresAt,estimatedOutput:intent.side==='BUY'?'50':'80000',minimumOutput:intent.side==='BUY'?'50':'80000'},feeCapLamports:'10000',rentCapLamports:'2000',refundCapLamports:'2000',balances:{native:'200000000',wsol:'1000000',token:'1000000'}};
  },
  async verifyPrepared(){await verifyHook();return true;},
  async readFinalized(){readCalls++;await readHook();return observation;},
  async verifyFinalizedEffects(){await effectHook();return effects;}
 };
 const engine=()=>createPumpRuntimeExecutor({ledger,adapter,readContext:()=>structuredClone(context),now:()=>clock});
 t.after(()=>db.close());
 return {context,body,adapter,engine,get ledger(){return ledger;},get db(){return db;},set clock(v){clock=v;},get readCalls(){return readCalls;},hooks(x){({prepareHook=prepareHook,verifyHook=verifyHook,readHook=readHook,effectHook=effectHook}=x);},async pending(input=body){const r=await engine().prepare({},input),tx=VersionedTransaction.deserialize(Buffer.from(r.plan.unsignedTransaction,'base64'));tx.sign([signer]);await engine().trackPending({},r.id,Buffer.from(tx.serialize()).toString('base64'));return ledger.get(r.id);},finality(r,e,{error=null,finalized=true}={}){const tx=VersionedTransaction.deserialize(Buffer.from(r.plan.unsignedTransaction,'base64'));tx.sign([signer]);observation={source:'LOCAL_FIXTURE',finalized,network:'solana:101',genesis:GENESIS,signature:ledger.get(r.id).signature,slot:100,error,transaction:Buffer.from(tx.serialize()).toString('base64')};effects=e;return observation;},restart(){db.close();db=new DatabaseSync(file);ledger=createPumpRuntimeLedger(db,{now:()=>now});}};
}
const buyEffects=swap=>({actualInput:'90000',actualOutput:'100',networkFeeLamports:'5000',rentLamports:'1000',nativeDelta:swap?'-6000':'-96000',tokenDelta:'100',wsolDelta:swap?'-90000':'0',venueFees:{protocol:'100',creator:'100',buyback:'100',lp:'0',includedInTrade:true}});

test('dependency observation and effects cannot mutate proof across authority awaits',async t=>{
 for(const phase of ['observation','effects']){const f=fixture(t),r=await f.pending(),effects=buyEffects(false),observation=f.finality(r,effects);let reads=0;
 const e=createPumpRuntimeExecutor({ledger:f.ledger,adapter:f.adapter,now:()=>now,readContext:async()=>{reads++;if(reads===(phase==='observation'?2:3)){if(phase==='observation'){observation.slot=999;observation.error={tampered:true};}else{effects.actualInput='1';effects.venueFees.protocol='99999';}}return structuredClone(f.context);}});
 assert.equal((await e.reconcile({},r.id)).status,'CONFIRMED');const proof=f.ledger.receipt(r.id).evidence;assert.equal(proof.slot,100);assert.equal(proof.error,null);assert.equal(proof.effects.actualInput,'90000');assert.equal(proof.effects.venueFees.protocol,'100');
 }
});
test('pending import rechecks expiry after final asynchronous authority guard',async t=>{const f=fixture(t),r=await f.engine().prepare({},f.body),tx=VersionedTransaction.deserialize(Buffer.from(r.plan.unsignedTransaction,'base64'));tx.sign([signer]);let reads=0,clock=now;const e=createPumpRuntimeExecutor({ledger:f.ledger,adapter:f.adapter,now:()=>clock,readContext:async()=>{if(++reads===2)clock=f.body.expiresAt;return structuredClone(f.context);}});await assert.rejects(e.trackPending({},r.id,Buffer.from(tx.serialize()).toString('base64')),/EXPIRED/);assert.equal(f.ledger.get(r.id).status,'PREPARED');assert.equal(f.ledger.get(r.id).signature,null);});
test('same-key replay does not rebuild or refresh the immutable plan',async t=>{const f=fixture(t),r=await f.engine().prepare({},f.body);f.adapter.prepare=()=>{throw Error('MUST_NOT_REBUILD');};assert.deepEqual(await f.engine().prepare({},f.body),r);await assert.rejects(f.engine().prepare({}, {...f.body,inputAmount:'1'}),/IDEMPOTENCY_CONFLICT/);});
test('same-key replay and passive read reject persisted plan mutation without rebuilding',async t=>{const f=fixture(t),r=await f.engine().prepare({},f.body);r.plan.feeCapLamports='999999';f.db.prepare('UPDATE pump_runtime_executions SET data=? WHERE id=?').run(JSON.stringify(r),r.id);f.adapter.prepare=()=>{throw Error('MUST_NOT_REBUILD');};await assert.rejects(f.engine().prepare({},f.body),/PERSISTED_INTEGRITY/);await assert.rejects(f.engine().read({},r.id),/PERSISTED_INTEGRITY/);});
test('concurrent identical intent converges despite changing prepared snapshot',async t=>{const f=fixture(t),base=f.adapter.prepare;let n=0;f.adapter.prepare=async i=>({...await base(i),snapshotSlot:100+(++n)});const [a,b]=await Promise.all([f.engine().prepare({},f.body),f.engine().prepare({},f.body)]);assert.equal(a.id,b.id);assert.equal(f.db.prepare('SELECT count(*) n FROM pump_runtime_executions').get().n,1);assert.equal(f.db.prepare('SELECT count(*) n FROM real_reserved_accounts').get().n,1);});
for(const bad of [undefined,false,0,'',{}])test(`ambiguous finality error ${JSON.stringify(bad)} cannot settle`,async t=>{const f=fixture(t),r=await f.pending(),o=f.finality(r,buyEffects(false));if(bad===undefined)delete o.error;else o.error=bad;await assert.rejects(f.engine().reconcile({},r.id),/FINALITY_CLASSIFICATION/);assert.equal(f.ledger.receipt(r.id),null);assert.equal(f.ledger.reservation(r.id).status,'UNKNOWN');});
test('finalized slot older than preparation cannot settle',async t=>{const f=fixture(t),r=await f.pending(),o=f.finality(r,buyEffects(false));o.slot=99;await assert.rejects(f.engine().reconcile({},r.id),/FINALITY_CLASSIFICATION/);assert.equal(f.ledger.receipt(r.id),null);});
for(const swap of [false,true])test(`runtime ${swap?'WSOL':'SOL'} receipt settlement releases only original asset dust`,async t=>{const f=fixture(t,{swap}),r=await f.pending();assert.equal(f.ledger.reservation(r.id).status,'UNKNOWN');assert.equal(f.ledger.reservation(r.id).resources[0].lamports,swap?'12000':'112000');f.finality(r,buyEffects(swap));const result=await f.engine().reconcile({},r.id);assert.equal(result.status,'CONFIRMED');assert.equal(result.unspentInput,'10000');assert.equal(result.releasedAsset,swap?'WSOL':'NATIVE_SOL');const p=f.ledger.position(f.body.agentId,mint);assert.equal(p.quantity,'100');assert.equal(p.costBasisLamports,'95000');assert.equal(p.rentPaidLamports,'1000');assert.equal(p.venueFeesLamports,'300');assert.equal(p.unrealizedPnl,null);assert.equal(p.provenance,'LOCAL_FIXTURE');assert.equal(f.ledger.receipt(r.id).actualChainVerified,false);assert.equal(f.ledger.reservation(r.id).status,'CONFIRMED');assert.equal((await f.engine().reconcile({},r.id)).status,'CONFIRMED');assert.equal(f.readCalls,1);});
test('curve BUY -> PumpSwap partial SELL carries basis without SOL/WSOL spendability conversion',async t=>{const f=fixture(t),r=await f.pending();f.finality(r,buyEffects(false));await f.engine().reconcile({},r.id);const base=f.adapter.prepare;f.adapter.prepare=async i=>({...await base(i),venueKind:'PUMPSWAP'});const s=await f.pending({...f.body,side:'SELL',inputMint:mint,outputMint:SOL_MINT,inputAmount:'50',requestKey:'runtime-sell-request-002'});f.finality(s,{actualInput:'50',actualOutput:'80000',grossOutput:'80300',networkFeeLamports:'5000',rentLamports:'-1000',nativeDelta:'-4000',tokenDelta:'-50',wsolDelta:'80000',venueFees:{protocol:'100',creator:'100',buyback:'100',lp:'0',includedInTrade:true}});await f.engine().reconcile({},s.id);const p=f.ledger.position(f.body.agentId,mint);assert.equal(p.quantity,'50');assert.equal(p.costBasisLamports,'47500');assert.equal(p.realizedPnlLamports,'27500');assert.equal(p.rentRecoveredLamports,'1000');assert.equal(p.networkFeesLamports,'10000');assert.equal(p.venueFeesLamports,'600');});
for(const [name,change] of [['mint',c=>c.associatedMint=wallet],['owner',c=>c.owner=wallet],['authority',c=>c.authorityVerified=false],['Pause',c=>c.paused=true],['kill',c=>c.killSwitch=true],['Live',c=>c.liveEnabled=true],['broadcast',c=>c.broadcastEnabled=true],['revision',c=>c.revision=-1]])test(`runtime denies ${name} before adapter and reservation`,async t=>{const f=fixture(t);change(f.context);await assert.rejects(f.engine().prepare({},f.body));assert.equal(f.db.prepare('SELECT count(*) n FROM pump_runtime_executions').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM real_reserved_accounts').get().n,0);});
for(const phase of ['prepareHook','verifyHook'])test(`late Pause after ${phase} prevents persistence`,async t=>{const f=fixture(t);f.hooks({[phase]:()=>{f.context.paused=true;f.context.revision++;}});await assert.rejects(f.engine().prepare({},f.body),/PAUSED_OR_DISARMED/);assert.equal(f.db.prepare('SELECT count(*) n FROM pump_runtime_executions').get().n,0);});
test('expiry during adapter await and changed request cannot bypass review',async t=>{const f=fixture(t);f.hooks({prepareHook:()=>{f.clock=f.body.expiresAt;}});await assert.rejects(f.engine().prepare({},f.body));assert.equal(f.db.prepare('SELECT count(*) n FROM real_reserved_accounts').get().n,0);});
test('pending restart and Pause reconciliation retain exact signature, null/pruned never terminal',async t=>{const f=fixture(t,{durable:true}),r=await f.pending();f.restart();f.context.paused=true;f.context.killSwitch=true;assert.equal((await f.engine().reconcile({},r.id)).status,'UNKNOWN');assert.equal(f.ledger.get(r.id).signature,r.signature);assert.equal(f.ledger.receipt(r.id),null);assert.equal(f.ledger.reservation(r.id).status,'UNKNOWN');await assert.rejects(f.engine().cancel({},r.id));await assert.rejects(f.engine().prepare({},f.body));f.finality(r,buyEffects(false));assert.equal((await f.engine().reconcile({},r.id)).status,'CONFIRMED');assert.equal('sign'in f.engine(),false);assert.equal('broadcast'in f.engine(),false);});
test('not-finalized observation is not success, but finalized on-chain error records fee without position',async t=>{const f=fixture(t),r=await f.pending();f.finality(r,buyEffects(false),{finalized:false});assert.equal((await f.engine().reconcile({},r.id)).status,'UNKNOWN');f.finality(r,{actualInput:'0',actualOutput:'0',networkFeeLamports:'5000',rentLamports:'0',nativeDelta:'-5000',tokenDelta:'0',wsolDelta:'0'},{error:{InstructionError:[0,'FixtureError']}});assert.equal((await f.engine().reconcile({},r.id)).status,'FAILED');assert.equal(f.ledger.position(f.body.agentId,mint),null);assert.equal(f.ledger.receipt(r.id).evidence.effects.networkFeeLamports,'5000');assert.equal(f.ledger.reservation(r.id).status,'FAILED');});
for(const [name,change] of [['over budget',e=>e.actualInput='100001'],['output',e=>e.actualOutput='1'],['fee',e=>e.networkFeeLamports='10001'],['rent',e=>e.rentLamports='2001'],['refund',e=>e.rentLamports='-2001'],['native',e=>e.nativeDelta='0'],['WSOL',e=>e.wsolDelta='1'],['token',e=>e.tokenDelta='1'],['venue fees',e=>e.venueFees.includedInTrade=false]])test(`invalid ${name} rolls back receipt, position and hold release`,async t=>{const f=fixture(t),r=await f.pending(),e=buyEffects(false);change(e);f.finality(r,e);await assert.rejects(f.engine().reconcile({},r.id));assert.equal(f.ledger.receipt(r.id),null);assert.equal(f.ledger.position(f.body.agentId,mint),null);assert.equal(f.ledger.reservation(r.id).status,'UNKNOWN');});
test('lost authority during finality/effects read cannot commit but Pause itself permits passive finality',async t=>{for(const hook of ['readHook','effectHook']){const f=fixture(t),r=await f.pending();f.finality(r,buyEffects(false));f.hooks({[hook]:()=>{f.context.owner=wallet;}});await assert.rejects(f.engine().reconcile({},r.id),/AUTHORITY/);assert.equal(f.ledger.receipt(r.id),null);}});
test('idempotency, cross-executor wallet hold and unsigned cancel remain exact',async t=>{const f=fixture(t),r=await f.engine().prepare({},f.body);assert.equal((await f.engine().prepare({},f.body)).id,r.id);await assert.rejects(f.engine().prepare({}, {...f.body,inputAmount:'90000'}),/IDEMPOTENCY_CONFLICT/);await assert.rejects(f.engine().prepare({}, {...f.body,requestKey:'runtime-competing-operation'}),/REAL_BALANCE_RESERVED/);assert.throws(()=>createRealBalanceReservations(f.db).reserve({operationId:'fixture-cpmm',intentHash:'cpmm',kind:'CONTROLLED_DEX',status:'PREPARED',resources:[{wallet,lamports:'1'}]}),/REAL_BALANCE_RESERVED/);assert.equal((await f.engine().cancel({},r.id)).status,'CANCELLED');assert.equal(f.db.prepare('SELECT count(*) n FROM real_reserved_accounts').get().n,0);});
test('receipt unique signature/atomic failure and immutable conflicting replay',async t=>{const f=fixture(t),r=await f.pending();f.finality(r,buyEffects(false));await f.engine().reconcile({},r.id);const proof=f.ledger.receipt(r.id).evidence;assert.equal(f.ledger.settle(r.id,proof).status,'CONFIRMED');assert.throws(()=>f.ledger.settle(r.id,{...proof,slot:101}),/RECEIPT_CONFLICT/);assert.throws(()=>f.db.prepare('DELETE FROM pump_runtime_receipts').run(),/Immutable Pump receipt/);});
test('untracked SELL and signed preparation are rejected',async t=>{const f=fixture(t);await assert.rejects(f.engine().prepare({}, {...f.body,side:'SELL',inputMint:mint,outputMint:SOL_MINT}),/UNTRACKED_POSITION/);const orig=f.adapter.prepare;f.adapter.prepare=async i=>{const p=await orig(i),tx=VersionedTransaction.deserialize(Buffer.from(p.unsignedTransaction,'base64'));tx.sign([signer]);return {...p,unsignedTransaction:Buffer.from(tx.serialize()).toString('base64')};};await assert.rejects(f.engine().prepare({},f.body),/SIGNED_PREPARATION/);});
test('official adapter rejects originally failed simulation despite deferred dependency mutation',async()=>{const b=await pumpAccountFixture();b.context.observedAt=now;const venue=decodePumpVenueBundle(b);let simulation,guards=0;const adapter=createPumpRuntimeAdapter({now:()=>now,readSnapshot:async()=>({venue,accounts:pumpWalletFixture(venue,wallet),networkFeeLamports:'5000',blockhash:fixtureBlockhash}),simulateUnsigned:async p=>{simulation={source:'LOCAL_FIXTURE',messageHash:p.messageHash,success:false,err:{fixtureFailure:true}};return simulation;}});await assert.rejects(adapter.prepare({agentId:venue.agentId,owner:venue.owner,network:'solana:101',agentWallet:wallet,side:'BUY',inputMint:SOL_MINT,outputMint:venue.mint,inputAmount:'1000000',slippageBps:100,expiresAt:now+10000},{},async()=>{if(++guards===3){simulation.success=true;simulation.err=null;}}),/SIMULATION_FAILED/);});
for(const migrated of [false,true])test(`official pinned SDK adapter is consumed by runtime prepare ${migrated}`,async t=>{
 const b=await pumpAccountFixture({migrated});b.context.observedAt=now;const venue=decodePumpVenueBundle(b),db=new DatabaseSync(':memory:');t.after(()=>db.close());const ledger=createPumpRuntimeLedger(db,{now:()=>now});
 const adapter=createPumpRuntimeAdapter({now:()=>now,readSnapshot:async()=>({venue,accounts:pumpWalletFixture(venue,wallet),networkFeeLamports:'5000',blockhash:fixtureBlockhash}),simulateUnsigned:async p=>({source:'LOCAL_FIXTURE',messageHash:p.messageHash,success:true,err:null})});
 const c={authenticated:true,owner:venue.owner,agentId:venue.agentId,agentWallet:wallet,associatedMint:venue.mint,network:'solana:101',genesis:GENESIS,authorityVerified:true,revision:1,paused:false,enabled:true,killSwitch:false,emergencyStop:false,liveEnabled:false,broadcastEnabled:false};
 const e=createPumpRuntimeExecutor({ledger,adapter,readContext:()=>c,now:()=>now}),r=await e.prepare({}, {owner:c.owner,agentId:c.agentId,agentWallet:wallet,network:'solana:101',genesis:GENESIS,side:'BUY',inputMint:SOL_MINT,outputMint:venue.mint,inputAmount:'1000000',slippageBps:100,expiresAt:now+10000,requestKey:'official-sdk-runtime-001'});
 assert.equal(r.status,'PREPARED');assert.equal(r.plan.venueKind,migrated?'PUMPSWAP':'PUMP_BONDING_CURVE');assert.equal(r.plan.quote.executable,false);assert.equal(r.signature,null);assert.equal(ledger.receipt(r.id),null);
});
