import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Keypair,SystemProgram,TransactionMessage,VersionedTransaction} from '@solana/web3.js';
import bs58 from 'bs58';
import {createPumpFinalizedReader} from '../server/dex/pump-finalized-reader.js';
import {GENESIS} from '../src/pump-readiness.js';
import {digest} from '../server/dex/intent.js';

// Synthetic bytes test transport binding only. Not a qualified Pump trade/event.
const signer=Keypair.fromSeed(Buffer.alloc(32,171)),other=Keypair.fromSeed(Buffer.alloc(32,172));
function fixture(){
 const message=new TransactionMessage({payerKey:signer.publicKey,recentBlockhash:other.publicKey.toBase58(),instructions:[SystemProgram.transfer({fromPubkey:signer.publicKey,toPubkey:other.publicKey,lamports:1})]}).compileToV0Message(),tx=new VersionedTransaction(message);
 const plan={source:'LOCAL_FIXTURE',venueKind:'PUMP_BONDING_CURVE',snapshotSlot:100,unsignedTransaction:Buffer.from(tx.serialize()).toString('base64'),messageHash:createHash('sha256').update(message.serialize()).digest('hex')};
 tx.sign([signer]);const signature=bs58.encode(tx.signatures[0]),intent={network:'solana:101',genesis:GENESIS,agentWallet:signer.publicKey.toBase58()};
 const record={id:'local-reader-test',source:'LOCAL_FIXTURE',status:'UNKNOWN',signature,intent,plan,planDigest:digest(plan),fingerprint:digest(intent)};
 const responses={getGenesisHash:GENESIS,getSignatureStatuses:{context:{slot:102},value:[{slot:101,confirmationStatus:'finalized',confirmations:null,err:null}]},getTransaction:{slot:101,blockTime:null,version:0,transaction:[Buffer.from(tx.serialize()).toString('base64'),'base64'],meta:{err:null,fee:5000}}};
 const calls=[];let hook=()=>{};
 const reader=createPumpFinalizedReader({rpc:async(method,params)=>{calls.push({method,params:structuredClone(params)});return hook(method)??responses[method];}});
 return {record,signature,tx,responses,calls,reader,hook:fn=>hook=fn};
}
test('exact recorded signature uses only three explicit read-only RPC calls',async()=>{
 const x=fixture(),o=await x.reader(x.signature,x.record);
 assert.deepEqual(x.calls,[{method:'getGenesisHash',params:[]},{method:'getSignatureStatuses',params:[[x.signature],{searchTransactionHistory:true}]},{method:'getTransaction',params:[x.signature,{encoding:'base64',commitment:'finalized',maxSupportedTransactionVersion:0}]}]);
 assert.equal(o.source,'LOCAL_FIXTURE');assert.equal(o.authorizationGranted,false);assert.equal(o.venueExecutionQualified,false);assert.equal(o.blockTime,null);assert.equal(o.meta.fee,5000);assert.equal(typeof x.reader,'function');assert.equal('sign'in x.reader,false);assert.equal('broadcast'in x.reader,false);
 // Reader transports the atomic RPC metadata; a separate effect verifier qualifies it.
 assert.equal(o.transaction,x.responses.getTransaction.transaction[0]);
});
for(const state of [null,'processed','confirmed'])test(`${state} observation stays unresolved without a transaction query`,async()=>{const x=fixture();x.responses.getSignatureStatuses.value[0]=state===null?null:{slot:101,confirmationStatus:state,confirmations:1,err:null};assert.equal(await x.reader(x.signature,x.record),null);assert.equal(x.calls.length,2);});
test('finalized status with pruned/missing transaction remains unresolved',async()=>{const x=fixture();x.responses.getTransaction=null;assert.equal(await x.reader(x.signature,x.record),null);assert.equal(x.calls.length,3);});
for(const [name,mutate]of [
 ['no record',x=>x.record=null],['not tracked',x=>x.record.status='PREPARED'],['foreign signature',x=>x.record.signature=bs58.encode(Buffer.alloc(64,1))],['source promotion',x=>x.record.source='ON_CHAIN'],['plan source promotion',x=>x.record.plan.source='ON_CHAIN'],['unknown venue',x=>x.record.plan.venueKind='OTHER'],['Devnet',x=>x.record.intent.genesis='devnet'],['EVM network',x=>x.record.intent.network='eip155:1'],['zero context',x=>x.record.plan.snapshotSlot=0],['mutable plan',x=>x.record.plan.messageHash='0'.repeat(64)],['mutable intent',x=>x.record.intent.agentWallet=other.publicKey.toBase58()],['zero signature',x=>x.signature=x.record.signature=bs58.encode(Buffer.alloc(64))],['short signature',x=>x.signature=x.record.signature=bs58.encode(Buffer.alloc(63,1))],['invalid signature',x=>x.signature=x.record.signature='0xabc']
])test(`reject ${name} before any RPC`,async()=>{const x=fixture();mutate(x);await assert.rejects(x.reader(x.signature,x.record));assert.equal(x.calls.length,0);});
for(const [name,mutate]of [
 ['wrong genesis',x=>x.responses.getGenesisHash='devnet'],['missing status context',x=>delete x.responses.getSignatureStatuses.context],['multiple status',x=>x.responses.getSignatureStatuses.value.push(null)],['undefined status',x=>x.responses.getSignatureStatuses.value[0]=undefined],['unknown commitment',x=>x.responses.getSignatureStatuses.value[0].confirmationStatus='unknown'],['status slot beyond bank',x=>x.responses.getSignatureStatuses.value[0].slot=103],['old finalized slot',x=>x.responses.getSignatureStatuses.value[0].slot=99],['finalized confirmations',x=>x.responses.getSignatureStatuses.value[0].confirmations=1],['missing status error',x=>delete x.responses.getSignatureStatuses.value[0].err],['invalid status error',x=>x.responses.getSignatureStatuses.value[0].err={}],
 ['missing transaction',x=>x.responses.getTransaction=undefined],['wrong transaction slot',x=>x.responses.getTransaction.slot=102],['legacy version',x=>x.responses.getTransaction.version='legacy'],['missing meta',x=>delete x.responses.getTransaction.meta],['missing landed error',x=>delete x.responses.getTransaction.meta.err],['mismatched error',x=>x.responses.getTransaction.meta.err={InstructionError:[0,'SyntheticFailure']}],['missing blocktime',x=>delete x.responses.getTransaction.blockTime],['negative blocktime',x=>x.responses.getTransaction.blockTime=-1],['parsed encoding',x=>x.responses.getTransaction.transaction[1]='jsonParsed'],['unsigned landed bytes',x=>x.responses.getTransaction.transaction[0]=x.record.plan.unsignedTransaction],['trailing transaction bytes',x=>x.responses.getTransaction.transaction[0]=Buffer.concat([Buffer.from(x.responses.getTransaction.transaction[0],'base64'),Buffer.from([0])]).toString('base64')],['broken crypto',x=>{x.tx.signatures[0][0]^=1;x.signature=x.record.signature=bs58.encode(x.tx.signatures[0]);x.responses.getTransaction.transaction[0]=Buffer.from(x.tx.serialize()).toString('base64');}],['changed signed bytes',x=>{x.tx.message.recentBlockhash=signer.publicKey.toBase58();x.tx.sign([signer]);x.signature=x.record.signature=bs58.encode(x.tx.signatures[0]);x.responses.getTransaction.transaction[0]=Buffer.from(x.tx.serialize()).toString('base64');}]
])test(`reject ${name} without retry or additional queries`,async()=>{const x=fixture();mutate(x);await assert.rejects(x.reader(x.signature,x.record));assert(x.calls.length<=3);assert(x.calls.every(c=>['getGenesisHash','getSignatureStatuses','getTransaction'].includes(c.method)));});
test('matching finalized failure is transported for fee-only effect qualification',async()=>{const x=fixture(),err={InstructionError:[0,'SyntheticFailure']};x.responses.getSignatureStatuses.value[0].err=err;x.responses.getTransaction.meta.err=err;const o=await x.reader(x.signature,x.record);assert.deepEqual(o.error,err);assert.equal(o.finalized,true);assert.equal(o.authorizationGranted,false);});
test('RPC failures are sanitized, do not retry and expose no provider secrets',async()=>{for(const method of ['getGenesisHash','getSignatureStatuses','getTransaction']){const x=fixture();x.hook(m=>{if(m===method)throw Object.assign(Error('https://rpc.example/?api-key=private-value'),{code:'PRIVATE_CREDENTIAL',httpStatus:429,rpcCode:-32005});});await assert.rejects(x.reader(x.signature,x.record),e=>e.code==='PUMP_FINALITY_RPC_UNAVAILABLE'&&e.httpStatus===429&&e.rpcCode===-32005&&!JSON.stringify(e).includes('private')&&!e.stack.includes('private'));assert.equal(x.calls.at(-1).method,method);assert.equal(x.calls.filter(c=>c.method===method).length,1);}});
test('throwing error accessors/proxy never bypass fixed sanitized RPC error',async()=>{for(const thrown of [Object.defineProperty(Error('private-marker'),'httpStatus',{get(){throw Error('private-marker');}}),Object.defineProperty(Error('private-marker'),'rpcCode',{get(){throw Error('private-marker');}}),new Proxy({},{ownKeys(){throw Error('private-marker');}})]){const x=fixture();x.hook(()=>{throw thrown;});await assert.rejects(x.reader(x.signature,x.record),e=>e.code==='PUMP_FINALITY_RPC_UNAVAILABLE'&&!e.stack.includes('private-marker')&&e.httpStatus===undefined&&e.rpcCode===undefined);assert.equal(x.calls.length,1);}});
test('capture record and status before dependency awaits; results do not alias RPC objects',async()=>{const x=fixture();x.hook(method=>{if(method==='getGenesisHash'){x.record.plan.messageHash='changed-after-await';x.record.signature='foreign';}if(method==='getTransaction')x.responses.getSignatureStatuses.value[0].slot=999;});const o=await x.reader(x.signature,x.record);assert.equal(o.slot,101);x.responses.getTransaction.meta.fee=999;assert.equal(o.meta.fee,5000);});
test('constructor rejects missing dependency and unsupported source; default is fixture',()=>{assert.throws(()=>createPumpFinalizedReader());assert.throws(()=>createPumpFinalizedReader({rpc:()=>{},source:'BACKEND_RPC_READ'}));});
test('ON_CHAIN cannot read a fixture record even when explicitly selected',async()=>{const x=fixture();let calls=0;const read=createPumpFinalizedReader({source:'ON_CHAIN',rpc:()=>{calls++;return null;}});await assert.rejects(read(x.signature,x.record),/TRACKED_RECORD_REQUIRED/);assert.equal(calls,0);});
