import test from 'node:test';import assert from 'node:assert/strict';import bs58 from 'bs58';import {readFileSync} from 'node:fs';
import {createReownWallet,reownNamespaces,restrictReownRequests,reownProjectConfigured,SOLANA_CAIP} from '../public/app/reown-wallet.js';
import {createReownTransport} from '../public/app/reown-transport.js';
import {readReownProjectId,reownBrowserPolicy} from '../tools/local-owner-preview/reown-config.mjs';
const owner=bs58.encode(new Uint8Array(32).fill(9));
const session=()=>({topic:'fixture-session',expiry:Math.floor(Date.now()/1000)+300,namespaces:{solana:{...reownNamespaces().solana,accounts:[SOLANA_CAIP+':'+owner]}}});
function fixture(){let loads=0,signs=0,disconnects=0;const events=new Map(),provider={session:null,on:(key,fn)=>events.set(key,fn),async request(args,chain){assert.equal(chain,SOLANA_CAIP);assert.equal(args.method,'solana_signMessage');assert.equal(args.params.pubkey,owner);assert.equal(new TextDecoder().decode(bs58.decode(args.params.message)),'AUTH ONLY');signs++;return {signature:bs58.encode(new Uint8Array(64))};}};const bridge=createReownWallet({codec:bs58,load:async()=>{loads++;return {provider,connect:async()=>provider.session=provider.session||session(),disconnect:async()=>{disconnects++;provider.session=null;}};}});return {bridge,provider,events,get loads(){return loads;},get signs(){return signs;},get disconnects(){return disconnects;}};}
test('single configured client key parsing does not load or expose unrelated environment',()=>{const id='a'.repeat(32);assert.equal(readReownProjectId('PRIVATE_KEY=fixture-unrelated\nVITE_REOWN_PROJECT_ID='+id+'\nANOTHER=ignored'),id);assert.equal(readReownProjectId('PRIVATE_KEY=fixture-unrelated'),'');assert.throws(()=>readReownProjectId('VITE_REOWN_PROJECT_ID=bad'),/Invalid VITE_REOWN/);assert.equal(reownProjectConfigured(id),true);assert.equal(reownProjectConfigured(''),false);assert.equal(reownBrowserPolicy(false).connect,'');assert.doesNotMatch(reownBrowserPolicy(true).connect,/\*/);assert.doesNotMatch(readFileSync('src/reown-bootstrap.js','utf8'),/[a-f0-9]{32}/i);});
test('registration and connect never authenticate; only explicit message goes through same Solana account',async()=>{const f=fixture(),w=f.bridge.wallet;assert.equal(f.loads,0);assert.deepEqual(w.accounts,[]);assert.deepEqual(Object.keys(w.features),['standard:connect','standard:disconnect','standard:events','solana:signMessage']);const result=await f.bridge.prepareConnection();assert.equal(result.accounts[0].address,owner);assert.equal(f.signs,0);assert.equal(f.loads,1);assert.equal((await w.features['standard:connect'].connect()).accounts[0],result.accounts[0]);await w.features['solana:signMessage'].signMessage({account:result.accounts[0],message:new TextEncoder().encode('AUTH ONLY')});assert.equal(f.signs,1);assert.equal(w.features['solana:signTransaction'],undefined);await w.features['standard:disconnect'].disconnect();assert.equal(w.accounts.length,0);assert.equal(f.disconnects,1);});
test('EVM, Devnet, excess transaction permission and expired sessions never become application owners',async()=>{for(const change of [s=>s.namespaces.solana.accounts=['eip155:1:0x123'],s=>s.namespaces.solana.accounts=[SOLANA_CAIP+':0x'+'a'.repeat(40)],s=>s.namespaces.solana.chains=['solana:devnet'],s=>s.namespaces.eip155={},s=>s.namespaces.solana.methods.push('solana_signTransaction'),s=>s.expiry=1,s=>delete s.expiry]){const f=fixture();f.provider.session=session();change(f.provider.session);await assert.rejects(f.bridge.prepareConnection());assert.deepEqual(f.bridge.wallet.accounts,[]);assert.equal(f.signs,0);assert.equal(f.disconnects,1);}});
test('account/chain/session changes and expiry revoke message signing',async()=>{for(const action of [f=>f.events.get('accountsChanged')(['0x123']),f=>f.events.get('chainChanged')('eip155:1'),f=>f.events.get('disconnect')(),f=>{f.provider.session.expiry=1;}]){const f=fixture(),w=f.bridge.wallet;const {accounts}=await f.bridge.prepareConnection();action(f);assert.equal(w.accounts.length,0);await assert.rejects(w.features['solana:signMessage'].signMessage({account:accounts[0],message:new Uint8Array([1])}));assert.equal(f.signs,0);}});
test('transaction/send/RPC methods and wrong chains are rejected before provider transport',async()=>{let calls=0;const p=restrictReownRequests({request:async()=>++calls});for(const method of ['solana_signTransaction','solana_signAndSendTransaction','solana_sendTransaction','eth_sendTransaction','getBalance'])assert.throws(()=>p.request({method},SOLANA_CAIP),/Only Solana authentication/);assert.throws(()=>p.request({method:'solana_signMessage'},'eip155:1'));assert.equal(calls,0);await p.request({method:'solana_signMessage'},SOLANA_CAIP);assert.equal(calls,1);});
test('closing discovery rejects promptly; late wallet approval is disconnected, SDK retry cannot broaden namespaces',async()=>{
 let state,resolvePairing,disconnected=0,proposal;
 const p={session:null,on(){},request:async()=>{},abortPairingAttempt(){},connect:async args=>{proposal=args;return new Promise(r=>resolvePairing=r);},disconnect:async()=>{disconnected++;p.session=null;},client:{disconnect:async()=>disconnected++}};
 const modal={subscribeState:fn=>{state=fn;return ()=>{};},open:async()=>state({open:true}),close:async()=>state({open:false})};
 const t=createReownTransport({provider:p,modal}),pending=t.connect();await new Promise(setImmediate);assert.deepEqual(proposal,{namespaces:reownNamespaces(),optionalNamespaces:{}});
 const retry=p.connect({optionalNamespaces:{eip155:{methods:['eth_sendTransaction']}}});assert.equal(retry,p.connect());const retryRejected=assert.rejects(retry,error=>error.code===4001);
 state({open:false});await assert.rejects(pending,error=>error.code===4001);await assert.rejects(p.connect(),error=>error.code===4001);p.session=session();resolvePairing(p.session);await retryRejected;assert.equal(disconnected,1);assert.equal(p.session,null);
});
test('curated Load More changes only modal state and has no catalog launcher',()=>{const source=readFileSync('public/app/workspace.js','utf8');const more=source.slice(source.indexOf("if(e.target.closest('[data-load-wallets],[data-less-wallets]'))"),source.indexOf("const mobileAction=e.target.closest('[data-mobile-wallets]')"));assert.match(more,/showMoreWallets=/);assert.match(more,/repaintWalletRows\(\)/);assert.doesNotMatch(source,/Browse All Wallets|data-more-wallets|data-wallet-discovery/);assert.doesNotMatch(more,/prepareConnection|connectPublicWallet|dialog.close|connect\(|disconnect\(|clearOwnerView\(|signMessage|post\(/);});
test('same-phone discovery starts with wallet choices instead of QR-only view',async()=>{
 let state,view;const p={session:null,request:async()=>{},abortPairingAttempt(){},connect:()=>new Promise(()=>{}),disconnect:async()=>{}};
 const modal={subscribeState:fn=>{state=fn;return ()=>{};},open:async options=>{view=options.view;state({open:true});},close:async()=>state({open:false})};
 const t=createReownTransport({provider:p,modal,mobile:true}),pending=t.connect();await new Promise(setImmediate);assert.equal(view,'AllWallets');state({open:false});await assert.rejects(pending,e=>e.code===4001);
});
