import test from'node:test';import assert from'node:assert/strict';
let serial=0;const key='TOKEN_TRANSPORT_KEY_001',id='fixture_AGENT',image='https://fixture.invalid/metadata/agents/fixture_AGENT/'+'a'.repeat(64)+'.png',envelope=()=>({draft:{name:'Coin',ticker:'COIN',image,website:'https://EXAMPLE.invalid:443/'},expectedRevision:0});
async function fixture(handler){const saved={window:globalThis.window,CustomEvent:globalThis.CustomEvent,fetch:globalThis.fetch,sessionStorage:globalThis.sessionStorage};const calls=[];globalThis.window={addEventListener(){},dispatchEvent(){}};for(const p of ['phantom','solflare','TekkworkSDK'])Object.defineProperty(window,p,{get(){throw Error('Provider/auth/signing access forbidden');}});globalThis.CustomEvent=class{constructor(type,options){this.type=type;this.detail=options?.detail;}};globalThis.sessionStorage=new Proxy({}, {get(){throw Error('Persistent storage access forbidden');}});globalThis.fetch=async(url,options)=>{calls.push({url,options});return handler(url,options,calls.length);};const backend=await import('../public/app/backend.js?token-transport-'+(++serial));return{backend,calls,close:()=>Object.assign(globalThis,saved)};}
const response=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});
test('first-token transport preserves explicit intent, omission, owner credentials and normalized adopted URLs',async()=>{const result={agentId:id,revision:1,replayed:false},f=await fixture(()=>response(result,201));try{const e=envelope();assert.deepEqual(await f.backend.saveTokenDraft(id,e,key),result);assert.equal(f.calls.length,1);const{url,options}=f.calls[0];assert.equal(url,'/api/launchpad/agents/'+id+'/token-draft');assert.equal(options.credentials,'same-origin');assert.equal(options.method,'POST');assert.equal(options.headers['idempotency-key'],key);const sent=JSON.parse(options.body);assert.equal(sent.draft.website,'https://example.invalid/');assert.ok(!Object.hasOwn(sent.draft,'description'));assert.ok(!Object.hasOwn(sent,'owner'));assert.equal(e.draft.website,'https://EXAMPLE.invalid:443/');assert.equal(options.headers['Content-Type'],'application/json');}finally{f.close();}});
test('uploaded image transport is isolated from token fields and preserves explicit empty description',async()=>{const f=await fixture(()=>response({revision:1}));try{const e={draft:{name:'Coin',ticker:'COIN',description:''},expectedRevision:0,tokenImage:'data:image/png;base64,AA=='};await f.backend.saveTokenDraft(id,e,key);assert.deepEqual(JSON.parse(f.calls[0].options.body),e);}finally{f.close();}});
test('lost response never auto retries or rotates key; explicit retry sends identical bytes',async()=>{const f=await fixture((u,o,n)=>{if(n===1)throw TypeError('Network response lost');return response({replayed:true});});try{const e=envelope();await assert.rejects(f.backend.saveTokenDraft(id,e,key),/response lost/);assert.equal(f.calls.length,1);await f.backend.saveTokenDraft(id,e,key);assert.equal(f.calls.length,2);assert.equal(f.calls[0].options.body,f.calls[1].options.body);assert.equal(f.calls[0].options.headers['idempotency-key'],f.calls[1].options.headers['idempotency-key']);}finally{f.close();}});
test('401/409/503 propagate authoritative HTTP status without auth prompt or background retry',async()=>{for(const status of [401,409,503]){const f=await fixture(()=>response({error:'Owner request unavailable'},status));try{await assert.rejects(f.backend.saveTokenDraft(id,envelope(),key),e=>e.httpStatus===status);assert.equal(f.calls.length,1);}finally{f.close();}}});
test('invalid route/key/revision/private fields/accessors fail before any request',async()=>{const f=await fixture(()=>{throw Error('No request permitted');});try{const accessor={...envelope()};Object.defineProperty(accessor,'draft',{enumerable:true,get(){throw Error('CANARY_ACCESSOR');}});const proxy=new Proxy({}, {ownKeys(){throw Error('CANARY_PROXY');}});const invalid=[['../OTHER',envelope(),key],[id,envelope(),'short'],[id,envelope(),'abcdefgh\r\n'],[id,{...envelope(),expectedRevision:1},key],[id,{...envelope(),owner:'OTHER'},key],[id,{...envelope(),draft:{...envelope().draft,privateKey:'CANARY'}},key],[id,{draft:{name:'Coin',ticker:'COIN'},expectedRevision:0},key],[id,{...envelope(),tokenImage:'AA'},key],[id,accessor,key],[id,proxy,key]];for(const args of invalid)await assert.rejects(f.backend.saveTokenDraft(...args),e=>e.code==='TOKEN_DRAFT_TRANSPORT_INPUT'&&!e.message.includes('CANARY'));assert.equal(f.calls.length,0);}finally{f.close();}});
test('client demo rejects save before fetch; input mutation cannot change a pending serialized intent',async()=>{let resolve;const pending=new Promise(r=>resolve=r);const f=await fixture(()=>pending);try{window.TekkworkDemo={session:null};await assert.rejects(f.backend.saveTokenDraft(id,envelope(),key),/Client demo only/);assert.equal(f.calls.length,0);delete window.TekkworkDemo;const e=envelope(),p=f.backend.saveTokenDraft(id,e,key);e.draft.name='Changed';resolve(response({revision:1}));await p;assert.equal(JSON.parse(f.calls[0].options.body).draft.name,'Coin');}finally{f.close();}});
test('configured local API base reuses existing cookie transport without additional calls',async()=>{const f=await fixture(()=>response({replayed:true}));try{window.TekkworkApiBase='http://127.0.0.1:4190/api';await f.backend.saveTokenDraft(id,envelope(),key);assert.equal(f.calls[0].url,'http://127.0.0.1:4190/api/launchpad/agents/'+id+'/token-draft');assert.equal(f.calls[0].options.credentials,'same-origin');assert.equal(f.calls.length,1);}finally{f.close();}});
