// Isolated browser fixtures. No application data, wallet request or transaction.
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
try{
 const page=await browser.newPage();let connected=false,fail=false;const calls=[];
 const agent={agentId:'fixture',name:'Fixture trader',character:'frank',tokenName:'Fixture token',tokenSymbol:'FIX',tokenMint:'fixture-mint',status:'READY',strategy:'momentum',mode:'paper',paperCashSol:0.1,portfolioValueSol:0.1,totalPnlSol:null,realizedPnlSol:null,unrealizedPnlSol:null,roiPercent:null,tradeCount:0,winRate:null,openPositions:[],activity:[],profiles:['momentum','selective'],wallet:null};
 await page.route('**/api/**',route=>{const p=new URL(route.request().url()).pathname;calls.push({p,method:route.request().method(),body:route.request().postData()});if(fail)return route.fulfill({status:503,json:{error:'Fixture outage'}});if(p==='/api/state')return route.fulfill({json:{session:connected?{address:'fixture-owner'}:null}});if(p.includes('/agents/'))return route.fulfill({json:agent});return route.fulfill({json:{mode:'paper',liveLocked:true,agents:[{...agent,rank:1}],overview:{activeTraders:0,openPositions:0,tradesToday:0,totalPaperPnlSol:null},activity:[]}});});
 await page.route('**/fixture-trading',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/workspace.css"><link rel="stylesheet" href="/polish.css"><link rel="stylesheet" href="/trading.css"><main id="fixture" style="padding:24px"></main>'}));
 await page.goto('http://127.0.0.1:5188/fixture-trading');
 const mount=kind=>page.evaluate(async kind=>{window.ctrl?.destroy();const m=await import('/app/trading-pages.js');window.ctrl=m.mountTradingPage(document.querySelector('main'),kind);},kind);
 await mount('payroll');await page.getByRole('heading',{name:'Connect your wallet'}).waitFor();assert.equal(calls.some(c=>c.p==='/api/trading/payroll'),false);
 connected=true;await mount('traders');await page.getByRole('heading',{name:'Fixture trader'}).waitFor();assert.match(await page.locator('main').innerText(),/—/);assert.equal(await page.locator('.tw-trader-card').getAttribute('href'),'#/trader/fixture');
 for(const width of [1440,390]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:`trading-network-${width}.png`,fullPage:true});}
 await mount('leaderboard');await page.getByRole('link',{name:'Fixture trader'}).waitFor();await page.locator('[data-sort]').selectOption('winRate');
 await page.evaluate(async()=>{window.ctrl.destroy();const m=await import('/app/trading-ui.js');window.ctrl=m.mountTrading(document.querySelector('main'),{id:'fixture'});});await page.getByRole('button',{name:'Start paper trading'}).waitFor();assert.equal(await page.getByRole('button',{name:'Start paper trading'}).isEnabled(),true);assert.equal(await page.getByRole('button',{name:'Fund agent — locked'}).isDisabled(),true);await page.locator('[data-mint]').fill('configured-market');await page.getByRole('button',{name:'Save market configuration'}).click();await page.waitForFunction(()=>document.querySelector('[data-mint]')?.value==='fixture-mint');assert.ok(calls.some(c=>c.p.endsWith('/configure')&&JSON.parse(c.body).tokenMint==='configured-market'));
 agent.status='PAUSED';agent.tokenMint=null;agent.defaultTokenMint='default-confirmed-mint';
 await page.evaluate(async()=>{window.ctrl.destroy();const m=await import('/app/trading-ui.js');window.ctrl=m.mountTrading(document.querySelector('main'),{id:'fixture'});});
 await page.getByRole('button',{name:'Resume paper trading'}).waitFor();assert.equal(await page.locator('[data-mint]').inputValue(),'default-confirmed-mint');assert.equal(await page.getByRole('button',{name:'Create agent wallet'}).isEnabled(),true);assert.equal(await page.getByRole('button',{name:'Live — locked'}).isDisabled(),true);assert.ok(await page.getByText('Starting capital',{exact:true}).count());
 agent.status='DRAFT';await mount('traders');await page.getByRole('heading',{name:'No traders yet'}).waitFor();assert.equal(await page.locator('.tw-trader-card').count(),0);
 const rendered=await page.evaluate(async()=>{const m=await import('/app/trading-pages.js');return {activity:m.renderActivity([{agentId:'one',type:'BUY',strategy:'momentum',entryPrice:1,executedSizeSol:0.01,pnlSol:null,timestamp:Date.now()}],[{agentId:'one',name:'Known trader'}]),positions:m.renderPositions([{tokenSymbol:'FIX',sizeSol:0.01,pnlPercent:2,openedAt:Date.now()-60000}])};});assert.match(rendered.activity,/Known trader/);assert.match(rendered.activity,/Entry 1 USD/);assert.doesNotMatch(rendered.activity,/PnL —/);assert.match(rendered.positions,/Size SOL/);assert.match(rendered.positions,/1m/);
 fail=true;await mount('traders');await page.getByRole('alert').filter({hasText:'Fixture outage'}).waitFor();assert.equal(await page.getByRole('heading',{name:'No traders yet'}).count(),0);
 console.log('PASS trading pages: canonical metrics, null values, private session, controls, errors and responsive layout');
}finally{await browser.close();}
