import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalEvent,projectTrading,aggregateTrading,rankTraders} from '../server/trading-projection.js';
import {executeLive,liveExecutionStatus,DexQuoteProvider,TradeExecutor,TransactionValidator,PositionReconciler} from '../server/live-execution.js';
const agent={id:'a',name:'Trader',creator:'PRIVATE_OWNER',secret:'SECRET',characterId:'frank',coin:{name:'Token',symbol:'TOK'}};
const now=Date.UTC(2026,8,27,12);
const state={mode:'paper',mint:'mint',strategy:'momentum',initialSol:.1,cashSol:.09,realizedSol:.002,market:{priceUsd:2,solUsd:100,observedAt:now},position:{positionId:'p',quantity:1,costSol:.01,entryPriceUsd:1,openedAt:now-1000}};
test('projection computes native SOL values once and redacts custody',()=>{
 const p=projectTrading(agent,state,[],now);assert.equal(p.status,'PAUSED');assert.equal(p.portfolioValueSol,.11);assert.ok(Math.abs(p.totalPnlSol-.01)<1e-12);assert.equal(p.unrealizedPnlSol,.01);assert.equal(p.winRate,null);assert.equal(p.character,'frank');assert.ok(!JSON.stringify(p).includes('SECRET'));assert.ok(!JSON.stringify(p).includes('PRIVATE_OWNER'));
});
test('legacy metrics remain unknown rather than invented',()=>{const p=projectTrading(agent,{mint:'mint',strategy:'momentum',initialUsd:10,cashUsd:9},[]);assert.equal(p.totalPnlSol,null);assert.equal(p.paperStartingCapitalSol,null);assert.equal(p.realizedPnlSol,null);assert.equal(p.paperCashSol,null);});
test('lifecycle distinguishes never-started and paused without launch state',()=>{assert.equal(projectTrading(agent,null).status,'DRAFT');assert.equal(projectTrading(agent,{mint:'mint',strategy:'momentum'}).status,'READY');assert.equal(projectTrading(agent,{...state,enabled:true}).status,'WORKING');assert.equal(projectTrading(agent,state).status,'PAUSED');});
test('closed positions not partial sells determine wins, breakevens count',()=>{
 const events=[{type:'SELL',realizedSol:1,createdAt:now},{type:'POSITION_CLOSED',positionId:'p1',pnlSol:1,createdAt:now},{type:'POSITION_CLOSED',positionId:'p1',pnlSol:1,createdAt:now},{type:'POSITION_CLOSED',positionId:'p2',pnlSol:0,createdAt:now},{type:'POSITION_CLOSED',positionId:'p3',pnlSol:-1,createdAt:now}];
 const p=projectTrading(agent,state,events);assert.equal(p.tradeCount,1);assert.equal(p.closedPositionCount,3);assert.equal(p.wins,1);assert.equal(p.losses,1);assert.ok(Math.abs(p.winRate-100/3)<1e-12);
});
test('network activity sorted globally, UTC tradesToday ignores HOLD and old trades',()=>{const a=projectTrading(agent,state,[{side:'BUY',createdAt:now},{side:'SELL',createdAt:now-86400000}]);const b=projectTrading({...agent,id:'b'},state,[{type:'HOLD',timestamp:now+1000},{side:'SELL',createdAt:now+2000}]);const n=aggregateTrading([a,b],now);assert.equal(n.overview.tradesToday,2);assert.equal(n.activity[0].agentId,'b');assert.equal(n.overview.openPositions,2);});
test('canonical events preserve missing fields as null and exclude raw records',()=>{const e=canonicalEvent(agent,state,{side:'BUY',createdAt:now,solNotional:.001,priceUsd:2,secret:'secret'});assert.equal(e.type,'BUY');assert.equal(e.entryPrice,2);assert.equal(e.executedSizeSol,.001);assert.equal(e.confidence,null);assert.equal(e.requestedSizeSol,null);assert.equal(e.secret,undefined);});
test('ranking sorts nulls last including negative returns',()=>{assert.deepEqual(rankTraders([{agentId:'a',totalPnlSol:null},{agentId:'b',totalPnlSol:-1}]).map(p=>p.agentId),['b','a']);});
test('canonical type mapping preserves legacy reasons',()=>{for(const [type,expected] of Object.entries({HOLD:'SIGNAL_SKIPPED',REJECTED:'RISK_REJECTED',STARTED:'TRADING_STARTED',CONFIGURED:'SIGNAL_SKIPPED',ERROR:'SIGNAL_SKIPPED'})){const e=canonicalEvent(agent,state,{type,reason:'Original reason'});assert.equal(e.type,expected);assert.equal(e.reason,'Original reason');}assert.equal(canonicalEvent(agent,state,{type:'SIGNAL_DETECTED'}).type,'SIGNAL_DETECTED');});
test('configured market token identity overrides agent launch token',()=>{const s={...state,tokenSymbol:'MARKET',market:{...state.market,tokenSymbol:'QUOTE'}};const p=projectTrading(agent,s,[{type:'BUY'}]);assert.equal(p.tokenSymbol,'MARKET');assert.equal(p.openPositions[0].tokenSymbol,'MARKET');assert.equal(p.activity[0].tokenSymbol,'MARKET');assert.equal(projectTrading(agent,{...state,strategy:'invalid'}).status,'DRAFT');});
test('unknown configured asset symbol never falls back to a different agent token',()=>{const p=projectTrading({...agent,coin:{...agent.coin,mint:'different'}},state,[{type:'BUY'}]);assert.equal(p.tokenSymbol,null);assert.equal(p.openPositions[0].tokenSymbol,null);assert.equal(p.activity[0].tokenSymbol,null);});
test('same timestamp keeps SQL newest-first order rather than sorting random identifiers',()=>{const history=[{eventId:'z',type:'SELL',timestamp:now},{eventId:'a',type:'SIGNAL_DETECTED',timestamp:now}];const p=projectTrading(agent,state,history);assert.equal(p.lastAction.type,'SELL');assert.deepEqual(aggregateTrading([p],now).activity.map(e=>e.eventId),['z','a']);});
test('unstarted drafts do not poison totals; participating unknowns remain unknown',()=>{const draft=projectTrading({...agent,id:'draft'},null),ready=projectTrading({...agent,id:'ready'},{mint:'mint',strategy:'balanced'}),p=projectTrading(agent,state);assert.equal(aggregateTrading([draft,ready,p],now).overview.totalPaperPnlSol,p.totalPnlSol);const legacy=projectTrading({...agent,id:'legacy'},{mint:'mint',strategy:'balanced',initialUsd:10});assert.equal(aggregateTrading([draft,legacy,p],now).overview.totalPaperPnlSol,null);});
test('Live remains locked even when environment requests live; adapters explicit',async()=>{const old=process.env.LIVE_TRADING_ENABLED;process.env.LIVE_TRADING_ENABLED='true';try{assert.equal(liveExecutionStatus().enabled,false);await assert.rejects(executeLive(),/LOCKED/);await assert.rejects(new TradeExecutor().execute({}),/LOCKED/);await assert.rejects(new DexQuoteProvider().quote({}),/NOT_IMPLEMENTED/);await assert.rejects(new TransactionValidator().validate({}),/NOT_IMPLEMENTED/);await assert.rejects(new PositionReconciler().reconcile({}),/NOT_IMPLEMENTED/);}finally{if(old===undefined)delete process.env.LIVE_TRADING_ENABLED;else process.env.LIVE_TRADING_ENABLED=old;}});
