import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {Keypair} from '@solana/web3.js';
import {createServer} from '../server/app.js';

test('one real paper event source feeds detail, network, leaderboard and owner payroll; no launch/wallet needed',async t=>{
 let time=1800000000000,price=1,change=2,stale=false,hold=null;
 const owner=Keypair.generate().publicKey.toBase58(),mint=Keypair.generate().publicKey.toBase58();
 const instance=createServer({dbPath:join(mkdtempSync(join(tmpdir(),'tekk-network-')),'db.sqlite'),now:()=>time,tradingOptions:{receipt:()=>null,market:async()=>{if(hold)await hold;return {mint,tokenMint:mint,tokenSymbol:'MARKET',snapshotId:'snapshot-'+time,network:'solana:101',priceUsd:price,solUsd:150,liquidityUsd:50000,change5m:change,buys5m:20,sells5m:5,volume5m:2000,observedAt:stale?time-31000:time};}}});
 const db=instance.store.db,server=instance.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>{server.close();instance.close();});
 const other=Keypair.generate().publicKey.toBase58();
 for(const [cookie,key] of [['owner',owner],['other',other]])db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(createHash('sha256').update(cookie).digest('hex'),key,time+3600000);
 for(const [id,key] of [['one',owner],['two',other]])db.prepare('INSERT INTO agents(id,owner,data,secret) VALUES(?,?,?,?)').run(id,key,JSON.stringify({id,creator:key,name:id,character:'frank',status:'DRAFT',strategy:'balanced',coin:{name:'Own draft',ticker:'DRAFT'}}),'test-only');
 const call=async(path,body,session='owner')=>{const r=await fetch(`http://127.0.0.1:${server.address().port}/api${path}`,{method:body?'POST':'GET',headers:{origin:'http://127.0.0.1:5188',cookie:session?'tw_session='+session:'','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};};
 const base='/agents/one/trading';
 assert.equal((await call(base)).data.status,'DRAFT');
 assert.equal((await call(base+'/enable',{mode:'paper',strategy:'balanced'})).status,409);
 // A missing config must not leak the per-agent lock.
 assert.equal((await call(base+'/configure',{strategy:'balanced',tokenMint:mint})).data.status,'READY');
 assert.equal((await call(base+'/enable',{mode:'paper',strategy:'balanced'})).data.status,'WORKING');
 assert.equal(db.prepare('SELECT COUNT(*) n FROM agent_wallets').get().n,0);
 await instance.paperTick();const first=(await call(base)).data;
 assert.equal(first.tradeCount,1);assert.equal(first.openPositions.length,1);assert.equal(first.winRate,null);assert.equal(first.losses,0);assert.equal(first.openPositions[0].tokenSymbol,'MARKET');
 const publicData=(await call('/trading/network',undefined,null)).data;
 assert.equal(publicData.overview.activeTraders,1);assert.equal(publicData.overview.tradesToday,1);
 assert.equal(publicData.overview.totalPaperPnlSol,first.totalPnlSol);
 assert.deepEqual(publicData.agents.find(a=>a.agentId==='one').activity,first.activity);
 assert.doesNotMatch(JSON.stringify(publicData),/test-only|"(?:tradingWallet|secret|privateKey|creator|owner)":/);
 const eventIds=first.activity.map(e=>e.eventId);assert.equal(new Set(eventIds).size,eventIds.length);
 assert.equal((await call('/trading/payroll')).data.agents.length,1);assert.equal((await call('/trading/payroll',undefined,'other')).data.agents.length,0);assert.equal((await call('/trading/payroll',undefined,null)).status,401);
 assert.equal((await call('/agents/one/trading',undefined,'other')).status,404);
 assert.equal((await call('/trading/leaderboard?mode=live')).status,409);
 assert.equal((await call(base+'/enable',{mode:'live',strategy:'balanced'})).status,409);
 assert.equal((await call(base+'/funding/prepare',{lamports:1})).status,409);
 time+=61000;price=.9;await instance.paperTick();const closed=(await call(base)).data;
 assert.equal(closed.tradeCount,2);assert.equal(closed.closedPositionCount,1);assert.equal(closed.losses,1);assert.equal(closed.winRate,0);assert.equal(closed.openPositions.length,0);
 assert.ok(Math.abs(closed.totalPnlSol-closed.realizedPnlSol)<1e-12);
 assert.equal((await call('/trading/leaderboard')).data.agents[0].totalPnlSol,closed.totalPnlSol);
 time+=61000;change=0;await instance.paperTick();assert.equal((await call(base)).data.lastAction.type,'SIGNAL_SKIPPED');
 time+=61000;stale=true;await instance.paperTick();assert.equal((await call(base)).data.tradeCount,2);assert.equal((await call(base)).data.health,'Unavailable');stale=false;change=2;
 time+=61000;let release;hold=new Promise(r=>release=r);const pending=instance.paperTick();await new Promise(r=>setTimeout(r,10));assert.equal((await call(base+'/pause',{})).data.status,'PAUSED');release();await pending;hold=null;
 assert.equal((await call(base)).data.tradeCount,2);assert.equal((await call('/trading/payroll')).data.agents[0].status,'PAUSED');
 assert.equal((await call('/agents/one/positions')).data.positions.length,0);
 assert.deepEqual((await call('/agents/one/activity')).data.events,(await call(base)).data.activity);
 assert.equal((await call(base+'/enable',{mode:'paper',strategy:'balanced'})).data.lastAction.type,'RESUMED');
 assert.equal((await call('/state')).data.agents[0].tradingStatus,'WORKING');
});
