import {selectorWalletRows,selectorWalletRow,selectorWallets} from '../public/app/wallet-selector.js';
import {createOwnerConnectFlow} from '../public/app/owner-connect-flow.js';
import {walletGroup,walletShortcuts} from '../public/app/wallet-catalog.js';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import bs58 from 'bs58';
import {mobileWalletPresentation} from '../public/app/wallet-mobile.js';
const first=bs58.encode(new Uint8Array(32).fill(4)),second=bs58.encode(new Uint8Array(32).fill(5)),key=value=>({toBase58:()=>value});
const saved={window:globalThis.window,CustomEvent:globalThis.CustomEvent,fetch:globalThis.fetch,sessionStorage:globalThis.sessionStorage};let serial=0;
function environment(wallets=[]){const listeners=new Map(),events=[];let unregister;globalThis.CustomEvent=class{constructor(type,options){this.type=type;this.detail=options?.detail;}};globalThis.window={TekkworkSDK:{bs58},addEventListener:(type,fn)=>listeners.set(type,fn),dispatchEvent:event=>{events.push(event.type);listeners.get(event.type)?.(event);}};if(wallets.length)window.addEventListener('wallet-standard:app-ready',e=>{unregister=e.detail.register(...wallets);});globalThis.fetch=()=>{throw Error('No transport allowed');};globalThis.sessionStorage={getItem(){throw Error('No storage allowed');},setItem(){throw Error('No storage allowed');},removeItem(){throw Error('No storage allowed');}};return {listeners,events,unregister:()=>unregister?.()};}
function standard(name){const handlers=new Map(),calls=[];const w={name,chains:['solana:mainnet'],accounts:[],features:{'standard:connect':{async connect(){calls.push('connect');w.accounts=[{address:first,chains:['solana:mainnet']}];return {accounts:w.accounts};}},'standard:disconnect':{async disconnect(){calls.push('disconnect');w.accounts=[];}},'standard:events':{on(name,fn){handlers.set(name,fn);return ()=>handlers.delete(name);}}}};Object.defineProperty(w.features,'solana:signMessage',{enumerable:true,get(){throw Error('Signature feature must not be inspected');}});return {w,handlers,calls};}
test('dynamic discovery retains connected provider identity when an unrelated wallet unregisters',async()=>{
 const env=environment(),a=standard('Backpack'),b=standard('Trust');let removeFirst;
 try{const backend=await import('../public/app/backend.js?restoration-'+(++serial));env.listeners.get('wallet-standard:register-wallet')({detail:({register})=>{removeFirst=register(a.w);register(b.w);}});const row=backend.wallets({readOnly:true}).find(w=>w.name==='Trust Wallet');await backend.connectPublicWallet(row.id);removeFirst();const current=backend.wallets({readOnly:true}).find(w=>w.name==='Trust Wallet');assert.equal(current.id,row.id);assert.equal(backend.publicWalletPresentation().address,first);assert.equal(backend.publicWalletPresentation().name,'Trust Wallet');}finally{Object.assign(globalThis,saved);}
});
test('existing chooser catalog supports all seven first-class Solana providers for address-only connection without sign/transport/storage',async()=>{
 const rows=walletShortcuts.map(([name])=>standard(name));environment(rows.map(x=>x.w));try{const backend=await import('../public/app/backend.js?restoration-'+(++serial));const catalog=backend.wallets({readOnly:true});assert.deepEqual(catalog.map(x=>x.name),walletShortcuts.map(([name])=>name));for(const row of catalog){assert.equal(row.selectable,true);assert.equal(await backend.connectPublicWallet(row.id),first);assert.deepEqual(backend.publicWalletPresentation().name,row.name);await backend.disconnectPublicWallet();assert.equal(backend.publicWalletPresentation(),null);}for(const row of rows)assert.deepEqual(row.calls,['connect','disconnect']);}finally{Object.assign(globalThis,saved);}
});
test('standard selected account updates, replacement/unregister and retired callbacks stay bound to actual provider',async()=>{
 const phantom=standard('Phantom'),solflare=standard('Solflare');const env=environment([phantom.w,solflare.w]);try{const backend=await import('../public/app/backend.js?restoration-'+(++serial));let rows=backend.wallets({readOnly:true});await backend.connectPublicWallet(rows[0].id);const late=phantom.handlers.get('change');phantom.w.accounts=[{address:second,chains:['solana:mainnet']}];late({accounts:phantom.w.accounts});assert.equal(backend.publicWalletPresentation().address,second);await backend.connectPublicWallet(rows[1].id);late({accounts:[{address:second,chains:['solana:mainnet']}]});assert.equal(backend.publicWalletPresentation().name,'Solflare');solflare.w.accounts=[];solflare.handlers.get('change')({accounts:[]});assert.equal(backend.publicWalletPresentation(),null);assert.equal(solflare.handlers.size,0);assert.ok(env.events.includes('tekkwork:public-wallet-changed'));}finally{Object.assign(globalThis,saved);}
});
test('injected Phantom/Solflare retain original discovery, and EVM-only MetaMask remains unavailable',async()=>{
 environment();const calls=[];const injected=name=>{const p={publicKey:key(first),connect:async()=>{calls.push(name+' connect');return {publicKey:p.publicKey};},disconnect:async()=>calls.push(name+' disconnect')};Object.defineProperty(p,'signMessage',{get(){throw Error('No signature feature reads');}});return p;};const p=injected('Phantom');p.isPhantom=true;window.phantom={solana:p};const s=injected('Solflare');s.isSolflare=true;window.solflare=s;window.ethereum={isMetaMask:true};try{const backend=await import('../public/app/backend.js?restoration-'+(++serial));const rows=backend.wallets({readOnly:true});assert.deepEqual(rows.map(x=>x.name),walletShortcuts.map(([name])=>name));assert.equal(rows.find(x=>x.name==='MetaMask').selectable,false);for(const row of rows.slice(0,2)){assert.equal(await backend.connectPublicWallet(row.id),first);assert.equal(backend.publicWalletPresentation().name,row.name);await backend.disconnectPublicWallet();}assert.deepEqual(calls,['Phantom connect','Phantom disconnect','Solflare connect','Solflare disconnect']);await assert.rejects(backend.connectPublicWallet(rows.find(x=>x.name==='MetaMask').id),/no longer available/);}finally{Object.assign(globalThis,saved);}
});
const workspace=fs.readFileSync('public/app/workspace.js','utf8');const walletCode=workspace.slice(workspace.indexOf('function paintWallet()'),workspace.indexOf('async function refresh()'));
function node(){const children=new Map();return {textContent:'',innerHTML:'',hidden:false,disabled:false,dataset:{},style:{},isConnected:true,classList:{add(){},remove(){}},setAttribute(){},removeAttribute(){},focus(){},append(){},prepend(){},remove(){this.isConnected=false;},contains:()=>false,querySelector(selector){if(!children.has(selector))children.set(selector,node());return children.get(selector);},querySelectorAll:()=>[],addEventListener(){}};}
test('actual preview button opens the recovered chooser with original rows/classes and address-only selected flow',async()=>{for(const preview of [true,false]){
 const effects=[],nodes=new Map(),rows=['Phantom','Solflare','Backpack'].map((name,i)=>{const n=node();n.dataset.wallet='standard-'+i;n.querySelector('strong').textContent=name;return n;});let dialog;const button=node();
 const ctx={state:{config:{preview,capabilities:{walletAuth:false}},session:null},workspaceUnavailable:false,window:{addEventListener(){}},document:{activeElement:button,querySelector:()=>null,createElement:()=>{dialog=node();dialog.querySelectorAll=s=>s==='[data-wallet]'?rows:[];const h=node();h.nextElementSibling=node();const q=dialog.querySelector.bind(dialog);dialog.querySelector=s=>s==='h2'?h:q(s);dialog.showModal=()=>effects.push('chooser-open');dialog.close=()=>{dialog.onclose?.();effects.push('chooser-close');};dialog.addEventListener=(name,fn)=>{dialog[name]=fn;};return dialog;},body:{append(){}}},$:s=>s==='#tw-wallet'?button:s==='#tw-create'?null:(nodes.get(s)||nodes.set(s,node()).get(s)),publicWalletPresentation:()=>ctx.connectedWallet||null,mountWalletBalance:(_,options)=>{effects.push('original-wallet-button');assert.equal(options.readOnly,true);},wallets:options=>{assert.equal(options.readOnly,true);return rows.map((row,i)=>({id:row.dataset.wallet,name:['Phantom','Solflare','Backpack'][i],selectable:true}));},walletSelectionStatus:()=>'',icon:()=>'<svg></svg>',esc:String,phantomSignProbeAvailable:()=>false,connectPublicWallet:async id=>{effects.push('public '+id);ctx.connectedWallet={address:first,name:'Phantom'};return first;},connect:()=>{throw Error('No owner auth');},refresh:()=>{throw Error('No owner state refresh');}};
 Object.assign(ctx,{createOwnerConnectFlow,selectorWalletRows,mobileWalletPresentation,walletGroup,location:{href:'http://127.0.0.1:5199/#/launch'},navigator:{userAgent:'Desktop test',maxTouchPoints:0}});vm.runInNewContext(walletCode,ctx);ctx.paintWallet();ctx.openWallet();assert.equal(dialog.className,'tw-dialog tw-connect-dialog');assert.match(dialog.innerHTML,/tw-wallet-choice-wrap/);assert.match(dialog.innerHTML,/CONNECT WALLET/);assert.ok(dialog.innerHTML.includes('Phantom')&&dialog.innerHTML.includes('Solflare')&&dialog.innerHTML.includes('Backpack'));assert.doesNotMatch(dialog.innerHTML,/data-wallet-probe=/);await dialog.click({target:{closest:s=>s==='[data-wallet]'?rows[2]:null}});assert.ok(effects.includes('public standard-2'));assert.ok(effects.includes('chooser-close'));assert.equal(ctx.state.session,null);
 ctx.connectPublicWallet=async()=>{throw Object.assign(Error('Rejected'),{walletAuthStage:'PROVIDER_CONNECT',walletAuthCode:'WALLET_CONNECTION_REJECTED'});};ctx.walletAuthPresentation=()=>({title:'CONNECTION CANCELLED',message:'Connection cancelled',details:''});ctx.walletFailureStatus=()=> 'Connection cancelled';ctx.openWallet();await dialog.click({target:{closest:s=>s==='[data-wallet]'?rows[0]:null}});assert.equal(rows[0].querySelector('small').textContent,'Connection cancelled');assert.ok(rows.every(row=>row.disabled===false));assert.equal(ctx.$('.tw-connect-details').hidden,true);assert.equal(ctx.state.session,null);
 ctx.workspaceUnavailable=true;ctx.state=null;ctx.paintWallet();ctx.openWallet();assert.equal(dialog.className,'tw-dialog tw-connect-dialog');await dialog.click({target:{closest:s=>s==='[data-wallet]'?rows[0]:null}});assert.equal(rows[0].querySelector('small').textContent,'Connection cancelled');assert.equal(ctx.state,null);assert.equal(ctx.$('.tw-connect-details').hidden,true);ctx.connectPublicWallet=async id=>{effects.push('offline-public '+id);ctx.connectedWallet={address:first,name:'Phantom'};return first;};await dialog.click({target:{closest:s=>s==='[data-wallet]'?rows[1]:null}});assert.ok(effects.includes('offline-public standard-1'));assert.equal(ctx.state,null);
}});
test('normal owner wallet branch remains separate from public-address fixture state',()=>{const effects=[];const ctx={state:{config:{preview:false},session:{address:first}},workspaceUnavailable:false,$:()=>node(),window:{addEventListener(){}},observeExistingWallet:()=>effects.push('owner-observe'),mountWalletBalance:(_,options)=>{effects.push('owner-menu');assert.equal(options.owner,first);assert.equal(options.readOnly,undefined);},walletProviderDisplay:()=>null,connectedWalletPresentation:()=>null,publicWalletPresentation:()=>{throw Error('Owner path must not use browser public address');}};vm.runInNewContext(walletCode,ctx);ctx.paintWallet();assert.deepEqual(effects,['owner-observe','owner-menu']);});

test('wallet app return reuses owner balance only and coalesces visibility/pageshow reads',async()=>{
 const raw=fs.readFileSync('public/app/wallet-balance.js','utf8').replace(/^import .*$/gm,'').replace(/export /g,'');
 const events=new Map(),winEvents=new Map(),calls=[];let time=100000,release;
 const ctx={window:{addEventListener:(k,v)=>winEvents.set(k,v),removeEventListener:k=>winEvents.delete(k)},document:{hidden:false,addEventListener:(k,v)=>events.set(k,v),removeEventListener:k=>events.delete(k),body:{classList:{add(){},remove(){}}}},Date:{now:()=>time},icon:()=>'<svg></svg>',request:path=>{calls.push(path);return new Promise(resolve=>{release=()=>resolve({owner:first,network:'solana:101',lamports:16738236});});},clearTimeout(){}};
 vm.runInNewContext(raw,ctx);const button=node();const opts={owner:first,onConnect:()=>{throw Error('No reconnect');},onAuthenticate:()=>{throw Error('No auth');}};
 ctx.mountWalletBalance(button,opts);assert.equal(calls.length,1);release();await new Promise(setImmediate);
 events.get('visibilitychange')();assert.equal(calls.length,1);time+=20000;ctx.document.hidden=true;events.get('visibilitychange')();assert.equal(calls.length,1);
 ctx.document.hidden=false;events.get('visibilitychange')();winEvents.get('pageshow')();assert.equal(calls.length,2);release();await new Promise(setImmediate);
 assert.deepEqual(calls,['/wallet/mainnet-balance','/wallet/mainnet-balance']);
 ctx.mountWalletBalance(button,{...opts,readOnly:true});time+=20000;events.get('visibilitychange')();winEvents.get('pageshow')();assert.equal(calls.length,2);
});
test('recovered connected-address popover uses existing markup without balance/auth/storage requests at desktop/mobile contexts',async()=>{
 const raw=fs.readFileSync('public/app/wallet-balance.js','utf8').replace(/^import .*$/gm,'').replace(/export /g,'');
 for(const width of [1440,390]){let panel,snapshot={address:first,name:'MetaMask'};const button=node();button.getBoundingClientRect=()=>({right:240,top:400});let disconnects=0;const ctx={window:{addEventListener(){},removeEventListener(){}},document:{addEventListener(){},removeEventListener(){},body:{classList:{add(){},remove(){}},append(p){panel=p;}},createElement:()=>{const p=node();p.offsetWidth=320;p.offsetHeight=360;return p;}},matchMedia:()=>({matches:width<=900}),innerWidth:width,innerHeight:844,icon:()=>'<svg></svg>',request:()=>{throw Error('No balance/API requests');},sessionStorage:{getItem(){throw Error('No storage');},setItem(){throw Error('No storage');},removeItem(){throw Error('No storage');}},setTimeout:()=>0,clearTimeout(){},navigator:{clipboard:{writeText:async()=>{}}}};
 vm.runInNewContext(raw,ctx);const paint=()=>ctx.mountWalletBalance(button,{owner:snapshot?.address,provider:snapshot,readOnly:true,getConnection:()=>snapshot,onConnect:()=>{},onDisconnect:async()=>{disconnects++;snapshot=null;paint();}});paint();assert.match(button.innerHTML,/tw-connected-label/);button.onclick();assert.equal(panel.className,'tw-wallet-popover tw-owner-popover');assert.match(panel.innerHTML,/tw-owner-disconnect/);assert.equal(panel.querySelector('[data-provider]').textContent,'MetaMask');assert.equal(panel.querySelector('[data-address]').title,first);assert.equal(panel.querySelector('[data-balance]').textContent,'Balance access unavailable');assert.equal(panel.querySelector('[data-refresh]').disabled,true);assert.match(panel.querySelector('[data-network]').textContent,/OWNER ACCESS UNAVAILABLE/);await panel.querySelector('[data-refresh]').onclick({currentTarget:node()});await panel.querySelector('[data-disconnect]').onclick({currentTarget:node()});assert.equal(disconnects,1);assert.match(button.innerHTML,/CONNECT WALLET/);
 }
});
test('curated selector retains native provider buttons and sidebar placement',()=>{const rows=walletShortcuts.map(([name,installUrl],i)=>({id:'provider-'+i,name,installUrl,selectable:i===0}));assert.deepEqual(selectorWallets(rows,false).map(w=>w.name),['Phantom','Solflare','Backpack']);assert.equal(selectorWallets(rows,true).length,7);const markup=selectorWalletRow(rows[0],{esc:String,href:'https://staging.tekkteam.tech',userAgent:'Android'});assert.match(markup,/<button class="tw-wallet-choice" type="button" data-wallet="provider-0"/);assert.doesNotMatch(markup,/disabled|href=/);const unavailable=selectorWalletRow(rows[2],{esc:String,href:'https://staging.tekkteam.tech',userAgent:'Android'});assert.match(unavailable,/backpack.webp/);assert.match(unavailable,/Open Backpack/);assert.doesNotMatch(unavailable,/disabled/);const current=fs.readFileSync('public/app/glass-navigation.js','utf8');assert.match(current,/dock.append\(wallet\)/);assert.equal(fs.readFileSync('public/hero-sidebar.css','utf8').includes('.tw-wallet-popover'),true);assert.doesNotMatch(fs.readFileSync('public/app/preview-wallet.js','utf8'),/createElement|innerHTML|Connect Phantom/);});
