import test from'node:test';import assert from'node:assert/strict';import vm from'node:vm';import{readFileSync,mkdtempSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{createHash}from'node:crypto';import sharp from'sharp';import{tokenDraftRead,createTokenDraftActions}from'../public/app/launchpad-page.js';import{createServer}from'../server/app.js';
const source=readFileSync('public/app/workspace.js','utf8'),code=source.slice(source.indexOf('async function launch(page)'),source.indexOf('function createAgentDialog()',source.indexOf('async function launch(page)'))),owner='ECMaFXkpb2bDFKXQciAKa1HNtqWgJs9PU3DcEmzgNMNS',agent={id:'AGENT',creator:owner,name:'Agent',coin:null};
const dto=()=>({id:agent.id,owner,lifecycle:{agent:{id:agent.id}},tokenDraft:{version:1,agentId:agent.id,owner,state:'EMPTY',revision:0,savedDraft:null,save:{allowed:true,reason:null,expectedRevision:0,immutable:true},ownerAuthority:{available:true,provenance:'BACKEND VERIFIED'},image:{required:true,localAsset:'MISSING',complete:false,publicDelivery:'UNVERIFIED'},authorizationGranted:false}});
async function fixture(options={}){let hooks;const calls=[],ctx={state:{session:{address:owner},agents:[{...agent}],config:{preview:false}},routeVersion:1,scenes:[],createIdentityIntentJournal:()=>null,publicWalletPresentation:()=>null,tokenDraftRead,request:async path=>{calls.push(['read',path]);return options.dto??dto();},saveTokenDraft:(...args)=>{calls.push(['save',...args]);return options.result??{agentId:agent.id};},refresh:async()=>calls.push(['refresh']),paintWallet:()=>calls.push(['wallet']),render:()=>calls.push(['render']),launchpadUnit:()=>{},openWallet:()=>{},post:()=>{throw Error('No other write allowed');},mountLaunchpadPage:(host,o)=>{hooks=o;return{destroy(){}};},location:{hash:'#/launch'},empty:()=>'',$:()=>({})};Object.assign(ctx,options.context);vm.runInNewContext(code,ctx);await ctx.launch({innerHTML:''});return{ctx,calls,get hooks(){return hooks;}};}
test('workspace eligibility requires actual bound v1 owner read; missing/unavailable/mismatched fails closed',async()=>{for(const value of [dto(),{...dto(),owner:'OTHER'},{...dto(),tokenDraft:null},{...dto(),tokenDraft:{...dto().tokenDraft,save:{allowed:false}}}]){const f=await fixture({dto:value});assert.equal(f.hooks.canSaveTokenDraft(agent.id),false);await f.hooks.loadContract(agent.id);assert.equal(f.hooks.canSaveTokenDraft(agent.id),value.owner===owner&&value.tokenDraft?.save.allowed===true);}const f=await fixture();await f.hooks.loadContract('OTHER');assert.equal(f.hooks.canSaveTokenDraft('OTHER'),false);});
test('workspace transport passes the exact caller body/key and never gates an attempted immutable retry on fresh eligibility',async()=>{const f=await fixture(),body={draft:{name:'Coin',ticker:'COIN'},expectedRevision:0,tokenImage:'data:image/png;base64,AAAA'};assert.equal(f.hooks.canSaveTokenDraft(agent.id),false);await f.hooks.saveTokenDraft(agent.id,body,'EXACT_KEY');assert.deepEqual(f.calls.at(-1),['save',agent.id,body,'EXACT_KEY']);assert.equal(f.calls.filter(x=>x[0]==='save').length,1);});
test('owner changes, stale route and preview prevent writes and capability use',async()=>{for(const change of [f=>f.ctx.state.session={address:'OTHER'},f=>f.ctx.routeVersion++,f=>f.ctx.state.config.preview=true]){const f=await fixture();await f.hooks.loadContract(agent.id);change(f);assert.equal(f.hooks.canSaveTokenDraft(agent.id),false);assert.throws(()=>f.hooks.saveTokenDraft(agent.id,{},'EXACT_KEY'),/context unavailable/);await f.hooks.onTokenSaved({agentId:agent.id});assert.equal(f.calls.filter(x=>x[0]==='save').length,0);assert.equal(f.calls.filter(x=>x[0]==='render').length,0);}});
test('late owner contract does not restore a stale route capability',async()=>{let release;const pending=new Promise(r=>release=r),f=await fixture({context:{request:()=>pending}});const read=f.hooks.loadContract(agent.id);f.ctx.routeVersion++;release(dto());assert.equal(await read,null);assert.equal(f.hooks.canSaveTokenDraft(agent.id),false);});
test('verified save refreshes actual owner roster before rendering; refresh failure/stale owner does not render success',async()=>{const f=await fixture();await f.hooks.loadContract(agent.id);await f.hooks.onTokenSaved({agentId:agent.id});assert.deepEqual(f.calls.slice(-2),[['refresh'],['render']]);assert.equal(f.hooks.canSaveTokenDraft(agent.id),false);const stale=await fixture({context:{refresh:async()=>{}}});stale.ctx.refresh=async()=>{stale.ctx.state.session={address:'OTHER'};};await stale.hooks.onTokenSaved({agentId:agent.id});assert.equal(stale.calls.some(x=>x[0]==='render'),false);const failed=await fixture();failed.ctx.refresh=async()=>{throw Error('offline');};await assert.rejects(failed.hooks.onTokenSaved({agentId:agent.id}),/offline/);assert.equal(failed.calls.some(x=>x[0]==='render'),false);});
test('preview and unowned Agent never acquire a contract/save through workspace hooks',async()=>{const f=await fixture({context:{state:{session:null,agents:[],config:{preview:true}}}});assert.equal(await f.hooks.loadContract(agent.id),null);assert.equal(f.hooks.canSaveTokenDraft(agent.id),false);assert.throws(()=>f.hooks.saveTokenDraft(agent.id,{},'EXACT_KEY'));assert.equal(f.calls.filter(x=>x[0]==='read').length,0);});
test('actual disposable owner API + browser transport + form intent + workspace hooks replay lost response once and refresh immutable roster',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'tekkteam-workspace-token-')),journal=join(dir,'pump-agent-launches.json'),previousDir=process.env.DATA_DIR,savedGlobals={window:globalThis.window,CustomEvent:globalThis.CustomEvent,fetch:globalThis.fetch},nativeFetch=globalThis.fetch,session='WORKSPACE_FIXTURE_SESSION',origin='http://127.0.0.1:5188';process.env.DATA_DIR=dir;writeFileSync(journal,JSON.stringify({version:2,receipts:{}}));
 const s=createServer({dbPath:':memory:',vaultKey:Buffer.alloc(32,9).toString('base64'),network:'mainnet',mainnetSafetyMode:true,rpc:'https://fixture.invalid',tokenDraftOptions:{journalPath:journal,assetRoot:dir,publicOrigin:'https://fixture.invalid'},realMoneyNetwork:{connection:new Proxy({}, {get:()=>()=>{throw Error('NO_RPC')}}),verify:async()=>{throw Error('NO_RPC')},status:()=>({realMoneyNetwork:'UNAVAILABLE'})}});s.store.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(createHash('sha256').update(session).digest('hex'),owner,Date.now()+1000000);const server=s.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port,paths=[];let lose=true;
 const call=async(path,options={})=>{paths.push(path);const r=await nativeFetch(base+'/api'+path,{...options,headers:{Origin:origin,Cookie:'tw_session='+session,'Content-Type':'application/json',...options.headers}});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error),{httpStatus:r.status});return data;};
 try{
 const a=await call('/launchpad/agent-identities',{method:'POST',headers:{'idempotency-key':'WORKSPACE_IDENTITY_KEY'},body:JSON.stringify({name:'Fixture Agent',character:'frank',strategy:'balanced'})});globalThis.window={TekkworkApiBase:base+'/api',addEventListener(){},dispatchEvent(){}};globalThis.CustomEvent=class{};globalThis.fetch=async(url,options)=>{const r=await nativeFetch(url,{...options,headers:{Origin:origin,Cookie:'tw_session='+session,...options.headers}});paths.push(new URL(url).pathname);if(options.method==='POST'&&lose){lose=false;await r.text();throw TypeError('LOCAL_FIXTURE_RESPONSE_LOST');}return r;};const transport=await import('../public/app/backend.js?workspace-integration');const f=await fixture({context:{state:{session:{address:owner},agents:[a],config:{preview:false}},request:path=>call(path),saveTokenDraft:transport.saveTokenDraft}});await f.hooks.loadContract(a.id);assert.equal(f.hooks.canSaveTokenDraft(a.id),true);
 const actions=createTokenDraftActions({owner,getOwner:f.hooks.getOwner,isCurrent:f.hooks.isCurrent,canSaveTokenDraft:f.hooks.canSaveTokenDraft,saveTokenDraft:f.hooks.saveTokenDraft}),png=await sharp({create:{width:2,height:2,channels:4,background:'#ffda54'}}).png().toBuffer(),input={draft:{name:'Fixture Coin',ticker:'FIX',website:'https://example.invalid/'},tokenImage:'data:image/png;base64,'+png.toString('base64')};await assert.rejects(actions.save(a.id,input),/RESPONSE_LOST/);const unresolved=JSON.stringify({version:2,receipts:{[a.id]:{agentId:a.id,owner,network:'solana:101',status:'Unknown',signature:'LOCAL_FIXTURE_UNVERIFIED_SIGNATURE',broadcastAttempted:true}}});writeFileSync(journal,unresolved);const immutable=await f.hooks.loadContract(a.id);assert.equal(immutable.lifecycle.launch.state,'RECONCILIATION_REQUIRED');assert.equal(f.hooks.canSaveTokenDraft(a.id),false);const result=await actions.save(a.id,input);assert.equal(result.replayed,true);assert.equal(readFileSync(journal,'utf8'),unresolved);assert.ok(!Object.hasOwn(result.draft,'description'));f.ctx.refresh=async()=>{f.ctx.state.agents=[await call('/agents/'+a.id)];};await f.hooks.onTokenSaved(result);assert.equal(f.ctx.state.agents[0].coin.name,'Fixture Coin');assert.ok(!Object.hasOwn(f.ctx.state.agents[0].coin,'description'));assert.equal(f.calls.filter(x=>x[0]==='render').length,1);assert.equal(s.store.db.prepare("SELECT count(*) AS n FROM events WHERE type='token-configured'").get().n,1);assert.equal(s.store.db.prepare('SELECT count(*) AS n FROM launchpad_first_tokens').get().n,1);assert.ok(paths.every(p=>!/(auth|pump-agent-launch|funding|trading)/.test(p)));
 }finally{server.closeAllConnections?.();await new Promise(r=>server.close(r));s.close();Object.assign(globalThis,savedGlobals);if(previousDir===undefined)delete process.env.DATA_DIR;else process.env.DATA_DIR=previousDir;}
});
