import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {publicConfig} from '../server/config.js';
import {fixtureEnvelope} from './fixtures/preview-envelope.mjs';
const source=readFileSync('public/app/workspace.js','utf8');
const between=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a)));
const code=between('function shell()','function paintWallet()')+between('function paintWallet()',"window.addEventListener('tekkwork:public-wallet-changed'")+between('async function refresh()','const worldHero')+between('function renderUnavailable(','window.addEventListener(\'hashchange\'')+between('async function boot()','window.addEventListener(\'pagehide\'');
const valid=(preview=true,network='mainnet')=>({config:preview?{...publicConfig('demo'),preview:true,backendOnline:false,capabilities:{walletAuth:false,persistentAgents:false,devnetMint:false,pumpfun:false,autonomousTrading:false}}:publicConfig(network),session:preview?null:{address:'LOCAL_FIXTURE_OWNER'},agents:preview?[]:[{id:'LOCAL_FIXTURE',coin:null}],events:[],stats:{}});
function fixture(replies){
 const effects=[],nodes={},listeners={},nav=[],walletMounts=[];let intervals=0;
 const node=()=>({innerHTML:'',textContent:'',className:'',disabled:false,dataset:{},classList:{add(){},remove(){},toggle(){}},querySelectorAll:()=>[],querySelector:()=>null});
 const page=node();page.querySelector=()=>nodes.retry??=node();
 const root=node();Object.defineProperty(root,'innerHTML',{get:()=>root.markup??'',set:html=>{root.markup=html;nodes.system=node();nodes.wallet=node();nav.length=0;for(const id of [...html.matchAll(/data-nav="([^"]+)"/g)].map(x=>x[1]))nav.push({dataset:{nav:id},classList:{toggle(){}},setAttribute(){},removeAttribute(){}});}});
 const ctx={state:undefined,workspaceUnavailable:false,bootBusy:false,poll:undefined,routeVersion:0,scenes:[],navigationPresentation:undefined,location:{hash:'#/overview'},root,
 request:async path=>{effects.push('read:'+path);const next=replies.shift();if(next instanceof Error)throw next;return typeof next==='function'?await next():next;},
 $:selector=>selector==='#tw-page'?page:selector==='.tw-system'?nodes.system:selector==='#tw-wallet'?nodes.wallet:selector==='[data-workspace-retry]'?nodes.retry:selector==='.tw-system span'?node():null,
 short:s=>s,enhanceShell:()=>{},publicWalletPresentation:()=>null,openWallet:()=>{},observeExistingWallet:()=>{},walletProviderDisplay:()=>null,disconnectPublicWallet:async()=>effects.push('public-disconnect'),mountWalletBalance:(_,options)=>{walletMounts.push(options);effects.push(options.readOnly?'public-wallet-mount':'wallet-mount');},mountGlassNavigation:()=>{effects.push('navigation-mount');return {destroy(){effects.push('navigation-dispose')}}},
 head:(_,title,copy)=>`<h1>${title}</h1><p>${copy}</p>`,worldHero:(_,title,copy,art,a,b)=>`<h1>${title}</h1><p>${copy}</p>${a}${b}`,routeName:()=>ctx.location.hash.slice(2).split('/')[0]||'overview',
 document:{body:{dataset:{}},querySelectorAll:()=>nav,hidden:false,title:''},window:{addEventListener:(name,fn)=>{(listeners[name]??=[]).push(fn)},scrollTo(){}},
 clearInterval:()=>{intervals=0},setInterval:fn=>{intervals++;ctx.pollCallback=fn;effects.push('poll');return 1},hydrateCharacters:()=>{},
 home:()=>effects.push('home'),agents:()=>effects.push('agents'),tokens:()=>{},launch:()=>{},characters:()=>{},characterAssignment:()=>{},guideLanding:()=>{},mountMarketPage:()=>{},mountWalletWorkspace:()=>{},connectedWalletPresentation:()=>{},mountTradingPage:()=>{},mountPublicTrader:()=>{},detail:()=>{},empty:()=>''};
 vm.runInNewContext(code+"\n"+between("window.addEventListener('hashchange'",'async function boot()'),ctx);
 return {ctx,page,root,nodes,nav,effects,listeners,walletMounts,intervals:()=>intervals};
}
test('rejected bootstrap retains shell/navigation and discards stale owner state',async()=>{const f=fixture([Error('offline')]);const query=f.ctx.$;f.ctx.$=()=>null;assert.doesNotThrow(()=>f.ctx.render());f.ctx.$=query;f.ctx.state=valid();await f.ctx.boot();assert.equal(f.ctx.state,null);assert.equal(f.ctx.workspaceUnavailable,true);assert.match(f.root.innerHTML,/Main navigation/);assert.match(f.root.innerHTML,/Launchpad/);assert.equal(f.nodes.wallet.disabled,false);assert.match(f.page.innerHTML,/unavailable data, not an empty workspace/);assert.doesNotMatch(f.root.innerHTML+f.page.innerHTML,/LOCAL_FIXTURE_OWNER|npm run server|No agents yet/);assert.deepEqual(f.effects,['read:/state','public-wallet-mount','navigation-mount']);assert.equal(f.intervals(),0);});
test('all ten routes and creation/detail deep links remain safely unavailable',async()=>{const f=fixture([Error('offline')]);await f.ctx.boot();for(const route of ['overview','launch','agents','tokens','market','traders','wallet','leaderboard','payroll','how','agent/LOCAL_FIXTURE','agents/new']){f.ctx.location.hash='#/'+route;f.listeners.hashchange[0]();assert.match(f.page.innerHTML,/Workspace API unavailable/);assert.match(f.page.innerHTML,/data-workspace-retry/);}assert.match(f.page.innerHTML,/Owner controls are unavailable/);assert.deepEqual(f.effects,['read:/state','public-wallet-mount','navigation-mount']);assert.equal(f.listeners.hashchange.length,1);});
test('non-JSON error-shaped and malformed successful responses fail closed',async()=>{for(const reply of [{error:'non-JSON'},null,{config:{},agents:[]}]){const f=fixture([reply]);await f.ctx.boot();assert.equal(f.ctx.state,null);assert.match(f.page.innerHTML,/Workspace API unavailable/);assert.equal(f.intervals(),0);assert.ok(!f.effects.includes('wallet-mount'));}});
test('failed retry then valid success restores actual identity-only owner data',async()=>{const data=valid(false);const f=fixture([Error('offline'),Error('offline again'),data]);await f.ctx.boot();await f.nodes.retry.onclick();assert.equal(f.nodes.retry.disabled,false);await f.nodes.retry.onclick();assert.equal(f.ctx.state,data);assert.equal(f.ctx.state.agents[0].coin,null);assert.equal(f.ctx.workspaceUnavailable,false);assert.deepEqual(f.effects.filter(x=>x.startsWith('read:')),['read:/state','read:/state','read:/state']);assert.equal(f.effects.filter(x=>x==='wallet-mount').length,1);assert.equal(f.effects.filter(x=>x==='home').length,1);assert.equal(f.intervals(),1);assert.equal(f.listeners.hashchange.length,1);});
test('busy retry prevents concurrent state reads and always reenables after failure',async()=>{let reject;const f=fixture([Error('offline'),()=>new Promise((_,r)=>reject=r)]);await f.ctx.boot();const pending=f.nodes.retry.onclick();assert.equal(f.nodes.retry.disabled,true);await f.ctx.boot();assert.equal(f.effects.filter(x=>x==='read:/state').length,2);reject(Error('still offline'));await pending;assert.equal(f.ctx.bootBusy,false);assert.equal(f.nodes.retry.disabled,false);});
test('ordinary successful boot preserves owner mount and single existing polling interval',async()=>{const f=fixture([valid(false),valid(false)]);await f.ctx.boot();assert.equal(f.intervals(),1);await f.ctx.boot();assert.equal(f.intervals(),1);assert.equal(f.effects.filter(x=>x==='wallet-mount').length,2);assert.equal(f.listeners.hashchange.length,1);});
test('poll preserves spanless Mainnet safety banner on successful and failed refresh',async()=>{
 for(const reply of [valid(false),Error('offline')]){
  const f=fixture([valid(false),reply]);await f.ctx.boot();const banner=f.nodes.system.textContent;
  assert.match(banner,/MAINNET SAFETY MODE/);await assert.doesNotReject(f.ctx.pollCallback());assert.equal(f.nodes.system.textContent,banner);
 }
});
test('poll tolerates removed shell and does not overwrite controlled launch status',async()=>{
 for(const mode of ['removed','launch','api']){
  const f=fixture([valid(false),valid(false),Error('offline')]);await f.ctx.boot();
  const status={textContent:mode==='api'?'Workspace API online':'Controlled launch',innerHTML:''};
  f.nodes.system.querySelector=()=>status;
  if(mode==='removed'){const query=f.ctx.$;f.ctx.$=s=>s==='.tw-system'?null:query(s);}
  await assert.doesNotReject(f.ctx.pollCallback());await assert.doesNotReject(f.ctx.pollCallback());
  assert.equal(status.textContent,mode==='api'?'Workspace API unavailable':'Controlled launch');
  assert.equal(status.innerHTML,mode==='api'?'<i></i> Workspace API online':'');
 }
});
test('route changes dispose scenes while unavailable without mounting domain handlers',async()=>{const f=fixture([Error('offline')]);await f.ctx.boot();let disposed=0;f.ctx.scenes=[{destroy(){disposed++}}];f.ctx.location.hash='#/wallet';f.ctx.render();assert.equal(disposed,1);assert.equal(f.ctx.scenes.length,0);assert.equal(f.effects.includes('wallet-mount'),false);});
test('API failure retains public address connect/disconnect while owner account events do no work',async()=>{
 const calls=[],callbacks={},options=[];let publicAddress={address:'PUBLIC_BROWSER_ADDRESS',name:'Phantom'};const ctx={workspaceUnavailable:true,state:null,window:{addEventListener:(name,fn)=>callbacks[name]=fn},publicWalletPresentation:()=>publicAddress,$:()=>({}),openWallet:()=>{},mountWalletBalance:(_,value)=>options.push(value),disconnectPublicWallet:async()=>{calls.push('provider-disconnect');publicAddress=null;},observeExistingWallet:()=>calls.push('owner-observe'),refresh:()=>calls.push('owner-read')};vm.runInNewContext(between('function paintWallet()','async function refresh()'),ctx);ctx.paintWallet();assert.equal(options.at(-1).readOnly,true);assert.equal(options.at(-1).owner,'PUBLIC_BROWSER_ADDRESS');await options.at(-1).onDisconnect();assert.equal(options.at(-1).owner,undefined);callbacks['tekkwork:public-wallet-changed']();await callbacks['tekkwork:wallet-account-changed']();assert.deepEqual(calls,['provider-disconnect']);assert.equal(ctx.state,null);
});
test('current local/devnet/mainnet API and actual bootstrap demo envelopes recover',async()=>{
 for(const network of ['local','devnet','mainnet','demo']){const data=network==='demo'?valid(true):valid(false,network);const f=fixture([Error('offline'),data]);await f.ctx.boot();await f.nodes.retry.onclick();assert.equal(f.ctx.state,data,network);assert.equal(f.ctx.workspaceUnavailable,false,network);assert.equal(f.intervals(),network==='demo'?0:1,network);assert.equal(f.effects.filter(x=>x==='home').length,1,network);}
});
test('isolated fixture uses accepted demo contract without changing actual empty data or enabling owner actions',async()=>{
 const original={...valid(false,'local'),session:null,agents:[],events:[]};
 const stale={...original,config:{...original.config,preview:true,capabilities:{walletAuth:false,persistentAgents:false,devnetMint:false,pumpfun:false,autonomousTrading:false}}};
 const before=fixture([stale]);await before.ctx.boot();assert.equal(before.ctx.workspaceUnavailable,true);
 const data=fixtureEnvelope(original,'/api/state');const after=fixture([data]);await after.ctx.boot();assert.equal(after.ctx.workspaceUnavailable,false);assert.equal(after.ctx.state,data);assert.equal(after.intervals(),0);
 assert.equal(data.config.network,'demo');assert.equal(data.config.backendOnline,false);assert.equal(data.config.previewTransportOnline,true);assert.equal(data.config.fixtureApplicationNetwork,'local');assert.equal(data.dataSource,'LOCAL_FIXTURE');assert.equal(data.agents,original.agents);assert.equal(data.events,original.events);assert.equal(data.stats,original.stats);assert.equal(data.session,null);
 assert.ok(Object.values(data.config.capabilities).every(value=>value===false));
 for(const invalid of [{...original,agents:[{id:'existing'}]},{...original,events:[{}]},{...original,session:{address:'owner'}},{...original,agents:null}])assert.throws(()=>fixtureEnvelope(invalid,'/api/state'),/NONEMPTY_OR_INVALID/);
});
test('missing/malformed/contradictory context never restores owner controls, domain mounts or polling',async()=>{
 const cases=[['unknown envelope',{config:{strategies:[]},session:{address:'LOCAL_FIXTURE_OWNER'},agents:[],events:[],stats:{}}]];
 const flagKeys=['preview','backendOnline','mainnetSafetyMode','broadcastEnabled','launchEnabled','tradingEnabled','mainnetLaunchEnabled'];
 for(const key of ['network','characters','networkConfig','capabilities',...flagKeys]){const d=valid(false);delete d.config[key];cases.push(['missing '+key,d]);}
 for(const key of flagKeys){const malformed=valid(false);malformed.config[key]='false';cases.push(['malformed '+key,malformed]);const conflicting=valid(false);conflicting.config[key]=!conflicting.config[key];cases.push(['contradictory '+key,conflicting]);}
 for(const key of ['walletAuth','persistentAgents','devnetMint','pumpfun','autonomousTrading']){const missing=valid(false);delete missing.config.capabilities[key];cases.push(['missing capability '+key,missing]);const malformed=valid(false);malformed.config.capabilities[key]=0;cases.push(['malformed capability '+key,malformed]);const conflicting=valid(false);conflicting.config.capabilities[key]=!conflicting.config.capabilities[key];cases.push(['contradictory capability '+key,conflicting]);}
 for(const network of ['unknown','MAINNET',null]){const d=valid(false);d.config.network=network;cases.push(['unsupported network '+network,d]);}
 for(const [key,value]of [['network','devnet'],['mode','DEVNET'],['walletChain','solana:devnet'],['phantomChain','solana:103'],['genesis',''],['safetyMode',false],['broadcastEnabled',true],['valueMovementEnabled',true]]){const d=valid(false);d.config.networkConfig={...d.config.networkConfig,[key]:value};cases.push(['contradictory declared '+key,d]);}
 const local=valid(false,'local');local.config.networkConfig={network:'mainnet'};cases.push(['local with chain',local]);const demo=valid(true);demo.session={address:'LOCAL_FIXTURE_OWNER'};cases.push(['demo owner',demo]);
 for(const [label,data]of cases){const f=fixture([Error('offline'),data]);await f.ctx.boot();await f.nodes.retry.onclick();assert.equal(f.ctx.workspaceUnavailable,true,label);assert.equal(f.ctx.state,null,label);assert.equal(f.intervals(),0,label);assert.equal(f.nodes.wallet.disabled,false,label);assert.ok(f.walletMounts.every(options=>options.readOnly===true&&options.owner===undefined),label);assert.equal(f.nodes.retry.disabled,false,label);assert.match(f.page.innerHTML,/unavailable data, not an empty workspace/,label);assert.equal(f.effects.some(x=>['wallet-mount','home','agents','poll'].includes(x)),false,label);assert.deepEqual(f.effects.filter(x=>x.startsWith('read:')),['read:/state','read:/state'],label);}
 assert.equal(cases.length,54);
});
test('successful retry uses latest route with validated context',async()=>{let resolve;const f=fixture([Error('offline'),()=>new Promise(r=>resolve=r)]);await f.ctx.boot();const pending=f.nodes.retry.onclick();f.ctx.location.hash='#/agents';f.listeners.hashchange[0]();resolve(valid(false));await pending;assert.equal(f.effects.includes('agents'),true);assert.equal(f.effects.includes('home'),false);assert.equal(f.ctx.bootBusy,false);});
test('rejected context on pending retry retains latest unavailable route',async()=>{let resolve;const f=fixture([Error('offline'),()=>new Promise(r=>resolve=r)]);await f.ctx.boot();const pending=f.nodes.retry.onclick();f.ctx.location.hash='#/wallet';f.listeners.hashchange[0]();resolve({config:{strategies:[]},session:null,agents:[],events:[],stats:{}});await pending;assert.match(f.page.innerHTML,/<h1>Wallet<\/h1>/);assert.equal(f.nodes.retry.disabled,false);assert.equal(f.ctx.state,null);assert.equal(f.intervals(),0);assert.equal(f.effects.includes('wallet-mount'),false);});
test('malformed detail URL retains shell and gives a safe navigation message',async()=>{const f=fixture([valid(false)]);await f.ctx.boot();f.ctx.location.hash='#/skins/assign/%';f.ctx.empty=(title,copy)=>title+' '+copy;assert.doesNotThrow(()=>f.ctx.render());assert.match(f.page.innerHTML,/This link is invalid/);assert.match(f.root.innerHTML,/Main navigation/);});
test('owner invalidation rejects an old state response and masks future stale cookie data',async()=>{const f=fixture([valid(false)]);await f.ctx.boot();let release;f.ctx.request=()=>new Promise(r=>release=r);const pending=f.ctx.refresh();f.ctx.clearOwnerView();release(valid(false));await assert.rejects(pending,/Retired owner response/);assert.equal(f.ctx.state.session,null);assert.equal(f.ctx.state.agents.length,0);f.ctx.request=async()=>valid(false);await f.ctx.refresh();assert.equal(f.ctx.state.session,null);assert.equal(f.ctx.state.agents.length,0);});
test('in-page anchor scrolls to its section without replacing the SPA route',async()=>{const f=fixture([valid(false)]);await f.ctx.boot();let clicked,prevented=false,scrolled=false;const anchor={addEventListener:(name,fn)=>clicked=fn,getAttribute:()=> '#agent-activity'};f.page.querySelectorAll=selector=>selector.startsWith('a[href')?[anchor]:[];f.page.querySelector=()=>({scrollIntoView:()=>scrolled=true});f.ctx.render();clicked({preventDefault:()=>prevented=true});assert.equal(prevented,true);assert.equal(scrolled,true);assert.equal(f.ctx.location.hash,'#/overview');});
