import { chromium } from 'playwright';
import { Keypair } from '@solana/web3.js';
import nacl from 'tweetnacl';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createServer } from '../server/app.js';
const base = process.env.BASE_URL || 'http://127.0.0.1:5188';
const dir = mkdtempSync(join(tmpdir(),'tekkwork-browser-'));
const service = createServer({ dbPath:join(dir,'db.sqlite'), origins:[base],network:'local' });
const server=service.app.listen(0,'127.0.0.1'); await new Promise(r=>server.once('listening',r));
const backend=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch();
let page;
try {
  page=await browser.newPage({viewport:{width:390,height:844}});
  const key=Keypair.generate();
  await page.exposeFunction('testSignMessage',bytes=>Array.from(nacl.sign.detached(Uint8Array.from(bytes),key.secretKey)));
  await page.addInitScript(({owner})=>{
    window.phantom={solana:{isPhantom:true,connect:async()=>{},disconnect:async()=>{},publicKey:{toBase58:()=>owner},signMessage:async bytes=>({signature:Uint8Array.from(await window.testSignMessage(Array.from(bytes)))})}};
  },{owner:key.publicKey.toBase58()});
  await page.route('**/api/**',async route=>{
    const url=new URL(route.request().url());
    const response=await route.fetch({url:backend+url.pathname,headers:{...route.request().headers(),origin:base}});
    await route.fulfill({response});
  });
  await page.goto(base+'/#/agents/new'); await page.locator('#tw-new-connect').click();
  await page.locator('[data-wallet="phantom"]').click(); await page.locator('dialog').waitFor({state:'detached'});
  await page.getByRole('button',{name:'Open navigation'}).click();
  const wallet=page.locator('#tw-wallet');
  assert.match(await wallet.textContent(),/CONNECTED/);
  assert.ok(!(await wallet.textContent()).includes(key.publicKey.toBase58()));
  await wallet.click();
  const popover=page.locator('body > .tw-owner-popover');await popover.waitFor();
  assert.equal(await popover.locator('[data-provider]').textContent(),'Phantom');
  assert.equal(await popover.locator('[data-copy]').count(),0);
  assert.equal(await popover.locator('[data-refresh] span').textContent(),'REFRESH BALANCE');
  assert.equal(await popover.locator('[data-disconnect] svg').count(),1);
  assert.equal(await popover.locator('[data-address]').getAttribute('title'),key.publicKey.toBase58());
  await page.evaluate(()=>{window.copiedWalletAddress='';Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{window.copiedWalletAddress=value;}}});});
  await popover.locator('[data-copy-icon]').click();
  assert.equal(await page.evaluate(()=>window.copiedWalletAddress),key.publicKey.toBase58());
  assert.match(await popover.locator('.tw-owner-copy-feedback').textContent(),/COPIED/);
  await popover.locator('[data-network][data-state="verified"]').waitFor();
  assert.ok((await popover.boundingBox()).width<=390-24);
  await page.keyboard.press('Escape');await popover.waitFor({state:'detached'});
  await wallet.click();await popover.waitFor();
  await page.setViewportSize({width:1440,height:900});
  await page.waitForFunction(()=>{const rail=document.querySelector('.tw-header')?.getBoundingClientRect(),panel=document.querySelector('.tw-owner-popover')?.getBoundingClientRect();return rail&&panel&&panel.left>=rail.right;});
  const rail=await page.locator('.tw-header').boundingBox(),floating=await popover.boundingBox();
  assert.ok(floating.x>=rail.x+rail.width,'desktop wallet popover must open outside sidebar');
  await popover.locator('[data-refresh]').click();await page.waitForFunction(()=>!document.querySelector('.tw-owner-popover [data-refresh]')?.disabled);
  await popover.locator('[data-close]').click();await popover.waitFor({state:'detached'});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#tw-create input[name="name"]').fill('Felix Browser Test');
  await page.locator('#tw-create input[name="tokenName"]').fill('Workspace Token');
  await page.locator('#tw-create input[name="ticker"]').fill('WORK');
  await page.locator('#tw-create input[value="fomy"]').check({force:true});
  await page.locator('#tw-create [data-character-image]').check();
  await page.locator('#tw-create .tw-token-image img').waitFor({state:'visible'});
  assert.equal(await page.locator('#tw-create input[name="name"]').inputValue(),'Felix Browser Test');
  assert.equal(await page.locator('#tw-create input[name="character"]:checked').inputValue(),'fomy');
  await page.locator('[data-next="2"]').click();
  await page.locator('[data-next="3"]').click();
  await page.locator('#tw-create button[type="submit"]').click(); await page.waitForTimeout(1000);
  assert.match(page.url(),/#\/agent\//,await page.locator('#tw-create [role="alert"]').textContent().catch(()=>''));
  await page.locator('.tw-detail h1').waitFor(); assert.equal(await page.locator('.tw-detail h1').textContent(),'Felix Browser Test');
  await page.locator('[data-agent-tab="settings"]').click();
  await page.locator('[data-settings-action="trading"]').click();
  await page.locator('#tw-strategy-center [data-preset="selective"]').click();
  await page.locator('#tw-strategy-center .strategy-advanced > summary').click();
  await page.locator('#tw-strategy-center [data-save]').click();
  await page.locator('[data-settings-save-state]').getByText(/SAVED/).waitFor();
  await page.reload(); await page.locator('[data-agent-tab="settings"]').click(); await page.locator('[data-settings-action="trading"]').click(); await page.locator('#tw-strategy-center [data-preset="selective"]').waitFor();
  assert.equal(await page.locator('#tw-strategy-center [data-preset="selective"]').getAttribute('aria-pressed'),'true');
  await page.goto(base+'/#/agents'); await page.locator('.tw-agent').waitFor(); assert.equal(await page.locator('.tw-agent').count(),1);
  await page.locator('#tw-search').fill('does-not-exist'); await page.getByText('NO AGENTS FOUND').waitFor();
  await page.getByRole('button',{name:'Open navigation'}).click();
  await page.locator('#tw-wallet').click(); await page.locator('[data-disconnect]').click();
  await page.getByText('YOUR WORKFORCE IS EMPTY').waitFor(); assert.equal(await page.locator('.tw-agent').count(),0);
  await page.evaluate(()=>{window.phantom.solana.signMessage=async()=>{throw Error('Unexpected error');};});
  await page.goto(base+'/#/agents/new');await page.locator('#tw-new-connect').click();await page.locator('[data-wallet="phantom"]').click();
  await page.locator('[data-wallet="phantom"] small').getByText('Couldn’t connect').waitFor();
  assert.equal(await page.locator('.tw-connect-details').isVisible(),false);
  assert.equal(await page.locator('[data-wallet="phantom"]').isEnabled(),true);
  assert.equal((await page.request.get(backend+'/api/state')).status(),200);
  console.log('Authenticated browser flow passed: wallet signature, draft save, profile update, reload, search, logout.');
} finally {if(page)await page.unrouteAll({behavior:'ignoreErrors'});await browser.close();await new Promise(r=>server.close(r));service.close();rmSync(dir,{recursive:true,force:true});}
