import 'dotenv/config';
import { resolve } from 'node:path';
import { createServer } from './app.js';
import { backendNetwork } from '../src/networks.js';
import {runtime,logError} from './runtime.js';
const config=runtime();
const selected = backendNetwork(process.env);
const instance = createServer({ dbPath: resolve(process.env.DATA_DIR || (selected.network === 'mainnet' ? 'server/data/mainnet-safety' : 'server/data'), 'tekkwork.sqlite'), vaultKey: process.env.VAULT_KEY_BASE64, origins: (process.env.APP_ORIGINS || 'http://127.0.0.1:5188,http://localhost:5188').split(','), network: selected.network, rpc: selected.rpc, mainnetSafetyMode:selected.safetyMode, production: process.env.NODE_ENV === 'production' });
const server = instance.app.listen(config.port, config.host, () => console.log(JSON.stringify({service:'api',status:'ready',port:config.port,liveTrading:false})));
const reconciliation = setInterval(() => instance.reconcilePending().catch(() => console.error('Reconciliation unavailable; will retry')), 15000);
const paperTrading=setInterval(()=>instance.paperTick().catch(e=>logError('paper-worker',e)),15000);
const close = () => { clearInterval(reconciliation);clearInterval(paperTrading); server.close(() => process.exit(0)); };
process.on('SIGINT', close); process.on('SIGTERM', close);
